<a href="https://colab.research.google.com/github/ESGcompetition/ipnyb/blob/choiyebin/%EA%B3%B5%EB%AA%A8%EC%A0%84_%EA%B0%80%EC%A4%91%EC%B9%98%ED%95%A8%EC%88%98_%EB%AA%A8%EB%93%A0%EC%97%B0%EB%8F%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import

In [1]:
import os, sys
from google.colab import drive
drive.mount('/content/drive')

my_path = '/content/package'
save_path = '/content/drive/MyDrive/Colab Notebooks/package' 

os.symlink(save_path, my_path)
sys.path.insert(0, my_path)

Mounted at /content/drive

In [117]:
import pandas as pd
import numpy as np
import re
import math

# 데이터셋 생성

## JSON 데이터

In [3]:
import requests, json
import pandas as pd

NOTION_TOKEN = "secret_AIc5tovrF5rnoYWC54z9CzwQUNb5d2A1q3HPKwOEqup"
DATABASE_ID = "213b4ff8bb884cfc987139ae53aa4396"

headers = {
    "Authorization": "Bearer " + NOTION_TOKEN,
    "Content-Type": "application/json",
    "Notion-Version": "2022-06-28",
}

In [4]:
DATABASE_ID_LIST = ["db2b026a03f0442f828bc88dcdbf143c", "c238334399d54b10aad0bcb84cb77d5c", "bf7efa466c624f1ca200d05c5cf34f58", "2f0e230f82974dd09841ae871cb558f9", "b708c8576ea34bb385d24aedc5b1277b", "d6211c2113914ecc86332d4bb305a115", "a8b0289c72eb4daaa1063152eb5e787a", "73e5dc61f97f4f2095c0265f2dae70d8", "1a91276509b246dda4c170a248d096c2", "6a374753947e42f7aa57fac3a474b78f"]
YEAR_LIST = [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]

In [5]:
def readDatabase(DATABASE_ID_LIST, YEAR_LIST, headers):
    for id in zip(DATABASE_ID_LIST, YEAR_LIST):
        readUrl = f"https://api.notion.com/v1/databases/{id[0]}/query"
        res = requests.request("POST", readUrl, headers=headers)
        data = res.json()
        print(res.status_code)

        if res.status_code == 200:
            try:
                with open(f"./{id[1]}.json", 'w', encoding='utf8') as f:
                    json.dump(data, f, ensure_ascii=False)
            except:
                continue

In [6]:
readDatabase(DATABASE_ID_LIST, YEAR_LIST, headers)

200
200
200
200
200
200
200
200
200
200

In [7]:
def jsonToDataFrame(YEAR_LIST):
    temp = {}
    year_list = []
    name = []
    birth = []
    registered = []
    fullTime = []
    responsibilities = []
    career = []
    stock = []
    time1 = []
    time2 = []
    position = []

    for year in YEAR_LIST:
        with open(f"./{year}.json", 'r') as f:
            json_data = json.load(f)
            for i in range(len(json_data['results'])):
                properties = json_data['results'][i]['properties']
                year_list.append(year)
                for key in properties:
                    if key == '이름':
                        name.append(properties[key]['title'][0]['text']['content'])
                    elif key == '출생년월':
                        birth.append(properties[key]['rich_text'][0]['text']['content'])
                    elif key == '등기임원 여부':
                        registered.append(properties[key]['rich_text'][0]['text']['content'])
                    elif key == '상근 여부':
                        fullTime.append(properties[key]['rich_text'][0]['text']['content'])
                    elif key == '담당업무':
                        responsibilities.append(properties[key]['rich_text'][0]['text']['content'])
                    elif key == '주요경력':
                        career.append(properties[key]['rich_text'][0]['text']['content'])
                    elif key == '의결권 있는 주식수':
                        stock.append(properties[key]['number'])
                    elif key == '재직기간':
                        time1.append(properties[key]['rich_text'][0]['text']['content'])
                    elif key == '임기만료일':
                        time2.append(properties[key]['rich_text'][0]['text']['content'])
                    elif key == '직위':
                        position.append(properties[key]['rich_text'][0]['text']['content'])

    temp['이름'] = name
    temp['연도'] = year_list
    temp['출생년월'] = birth
    temp['등기임원 여부'] = registered
    temp['상근 여부'] = fullTime
    temp['담당업무'] = responsibilities
    temp['주요경력'] = career
    temp['의결권 있는 주식수'] = stock
    temp['재직기간'] = time1
    temp['임기만료일'] = time2
    temp['직위'] = position
    return temp

In [8]:
dict = jsonToDataFrame(YEAR_LIST)

In [9]:
df = pd.DataFrame.from_dict(data=dict, orient='columns')

In [10]:
df.head()

,이름,연도,출생년월,등기임원 여부,상근 여부,담당업무,주요경력,의결권 있는 주식수,재직기간,임기만료일,직위
0,이현식,2014,1962.05,미등기임원,상근,강북지역본부장,서울대 경영학(석사)\n대신증권 시흥동지점장\n대신증권 명일동지점장\n대신증권 퇴직...,4720.0,2012.04.01~2014.12.31,2015.03.20,전무
1,조윤남,2014,1968.11,미등기임원,상근,리서치센터장,한국과학기술원 화학공학(석사)\n대신증권 투자전략부장,17401.0,2011.04.01~2014.12.31,2015.03.20,상무
2,나재철,2014,1960.01,등기임원,상근,업무총괄,한국외국어대 경영학(석사)\n대신증권 강남지역본부장\n대신증권 WM추진본부장\n대...,23301.0,2004.04.01~2014.12.31,2016.03.31,대표이사
3,이정훈,2014,1947.06,등기임원,비상근,-,서울대 법학(석사)\n대한중재인협회 회장\n법무법인 태평양 대표변호사(현),0.0,2010.05.28~2014.12.31,2015.03.20,사외이사
4,송혁,2014,1964.04,미등기임원,상근,비서/브랜드담당,전북대 회계학\n대신증권 인수공모2부\n대신증권 비서실장,10391.0,2010.04.01~2014.12.31,2015.03.20,전무

## 데이터셋 살펴보기

In [11]:
print(len(df[df['연도']==2014]))
print(len(df[df['연도']==2015]))
print(len(df[df['연도']==2016]))
print(len(df[df['연도']==2017]))
print(len(df[df['연도']==2018]))
print(len(df[df['연도']==2019]))
print(len(df[df['연도']==2020]))
print(len(df[df['연도']==2021]))
print(len(df[df['연도']==2022]))
print(len(df[df['연도']==2023]))

30
31
35
32
33
37
36
38
42
40

In [12]:
df['담당업무'].unique()

array(['강북지역본부장', '리서치센터장', '업무총괄', '-', '비서/브랜드담당', '강남지역본부장',
       'Trading Center장', '서부지역본부장', '인재역량센터장', '동부지역본부장',
       'Wholesale사업단장', '영업부장', '고객자산본부장', '인프라관리본부장', '상근감사위원',
       '금융주치의사업단장', '스마트금융본부장', 'IB사업단장', '금융주치의추진본부장',
       '업무총괄(IB사업단, 고객자산본부 제외)', '울산지점장', '기획본부장', 'IT서비스본부장', '감사위원',
       '구조화상품본부장', '감사위원장', 'IB부문장', '정보보호담당', '감사담당', 'IB부부문장',
       'Wholesale영업본부장', 'Operation&Technology본부장',
       'Research&Strategy본부장', '리스크관리담당', '경영지원본부장', 'IB1부문장',
       'Market\n  Solution부문장', '기획본부장 / 투자금융담당', '준법감시인 / 준법지원담당',
       'Product부문장', '업무총괄(IB사업단,고객자산본부 제외)', 'IB2부문장', '고객자산본부장 / 홍보담당',
       'Advisory본부장', 'Solution&Product사업단장', '비서/브랜드본부',
       'Market Solution부문장', '강남선릉센터장', '스마트Biz본부장', '전략지원담당',
       '준법감시인\n준법지원담당', '고객자산본부장/ 홍보담당', 'PF부문장',
       '업무총괄 (IB사업단,고객자산본부 제외)', 'IT본부장', '경영기획본부장', 'WM사업단장', '경영전략총괄',
       '전략지원부문장/프라이빗라운지 부문장', 'Market Solution 부문장', 'Research Center장',
       '정보보호부문장', '고객자산본부장/ 홍보부문장',
       '업무총괄(IB사업단, 고객자산본부, 경영지원본부, 정보보호부문, 준법지원부문, 감사부문 제외)', '감사부문장',
       '준법감시인/준법지원부문장', '리스크관리부문장', '대신나인원 \n프라이빗라운지장', '동부WM본부장',
       'Wholesale부문장', '대외협력담당', '금융소비자보호 총괄',
       '프라이빗라운지 부문장 /대신나인원 프라이빗라운지장', '전략지원부문장', '서부WM본부장',
       '고객자산본부장/홍보부문장', '재경2WM본부장', 'IPO담당', 'WM추진본부장', '재경1WM본부장',
       'Trading부문장', '재경1WM부문장', '경영기획부문장', 'Coverage본부장', '서부WM부문장',
       '프라이빗부문장, 대신나인원프라이빗라운지장', '동부WM부문장', '금융소비자보호총괄', 'WM추진부문장',
       '디지털부문장', '재경2WM부문장', '준법감시인\n준법지원부문장', 'Sales&Trading총괄',
       '고객자산부문장, 홍보부문장', '경영지원부문장', 'IT부문장', '리테일총괄',
       '프라이빗부문장\n나인원프라이빗라운지장', '기업금융담당', '비서실장', 'PF1본부장',
       '금융소비자보호부문장(COO)', '고객자산부문 부부문장', 'Club1962센터장', '고객자산부문장\n홍보부문장',
       '준법감시인 준법지원부문장', '프라이빗부문장, 나인원프라이빗라운지장', '고객자산부문장', '홍보부문장',
       '금융소비자보호부문장 (COO)'], dtype=object)

In [13]:
df['주요경력'].unique()

array(['서울대 경영학(석사)\n대신증권 시흥동지점장\n대신증권 명일동지점장\n대신증권 퇴직연금컨설팅본부장\n대신증권 퇴직연금본부장',
       '한국과학기술원 화학공학(석사)\n대신증권 투자전략부장',
       '한국외국어대 \xa0경영학(석사)\n대신증권 강남지역본부장\n대신증권 WM추진본부장\n대신증권 Wholesale본부장\n대신증권 Wholesale사업단장\n기획본부장대신증권 \xa0인재역량센터장\n기업금융사업단장',
       '서울대 법학(석사)\n대한중재인협회 회장\n법무법인 태평양 대표변호사(현)',
       '전북대 회계학\n대신증권 인수공모2부\n대신증권 비서실장',
       '성균관대 불어불문학\n대신증권 대치동지점 이사대우지점장\n대신증권 남대문지점 이사대우지점장\n대신증권 종로지점 이사대우지점장\n대신증권 강남지역본부장\n대신증권\xa0중부지역본부장',
       '조지아공대 항공우주학(박사)\n대신증권 파생상품운용부 부장\n대신증권 자산운용본부 이사대우본부장',
       '고려대 법학\n대신증권 화정동지점장\n대신증권 상무지점장\n대신증권 무등지점 이사대우지점장',
       '서강대 경제학\n대신증권 영업기획부 부장\n대신증권 기획실 실장\n대신증권 인재전략부 이사대우부장',
       '고려대 경영대학원(석사)\n금융감독원 부원장보\nLIG손해보험 상근감사위원\n하비스트 대표(현)',
       '성균관대 회계학\n대신증권 무역센터지점장\n대신증권\xa0분당지점장\n대신증권 강남선릉센터 이사대우센터장\n대신증권 강서지역본부장',
       '한국외국어대 무역학(석사)\n우리투자증권 기업분석팀장\n대신증권 리서치센터장\n대신증권 기획본부장',
       '연세대 경영학\n대신증권 법인영업부장\n대신증권 Wholesale1본부장\n대신증권 Wholesale영업본부장',
       '연세대 경제학(석사)\n우리CS자산운용 AI본부장\n대신증권 파생금융본부장\n대신증권 CM본부장\n대신증권\xa0Capital Market 사업단장',
       '대전대 경영학(박사)\n대신증권 관재팀장\n대신증권 총무부장',
       '연세대 경제학(석사)\nSBC WARBURG DILLON READ(현UBS증권) 법인영업이사\n푸르덴셜투자증권 홀세일사업본부장\n메릴린치증권 서울지점 상무',
       '한양대 경영학\n대신증권 송탄지점장\n대신증권 중부지역본부장\n대신증권 강남지역본부장',
       '연세대 정치학(석사)\n한국투자증권 평촌지점 상무\n부영주택 기획관리부 상무\n부영주택 영업부 상무',
       '서울대 경영학(석사)\nIBK투자증권 IB사업부 부사장\n대신증권 IB본부장\n대신증권 기업금융사업단장',
       'KDI국제정책대학원(석사)\n삼성증권 상품개발팀장\n동양증권 상품기획본부장\n대신증권 고객상품본부장',
       '상명여자사범대', '서울대 경영학\n대신투자신탁운용 \xa0상무이사\n대신증권 전무\n대신증권 부사장',
       '울산대 경영학\n대신증권 울산남지점장\n대신증권\xa0무거동지점장\n대신증권 울산지점 이사대우지점장\n대신증권 동부지역본부장\n대신증권 동래지점장',
       '연세대 경영대학원(석사)\n대신증권 홍보실 이사대우실장\n대신증권 브랜드전략실 이사대우실장',
       '홍익대 전자계산학(석사)\n대신증권 전산개발팀장\n대신증권 고객지원부장\n대신증권 IT본부장',
       '중앙대 무역학(박사)\n국세청,관세청,산업통상자원부 정부정책자체평가위원\n기획재정부 국제행사심사위원회 민간위원\n중앙대 상경학부 교수(현)',
       '명지대 경영학\n서울지방국세청장\n재단법인 정평장학회 이사장\n피앤비세무컨설팅 대표(현)',
       '연세대 경영학\n대신증권 장외파생상품부장\n대신증권 파생상품영업부장\n대신증권 해외파생상품부장\n대신증권 파생영업본부장',
       'Brown대 경제학(박사)\nLG경제연구원 금융연구실 실장\n수원대학교 경영학부 교수\nKAIST MBA교수\n자본시장연구원 부원장(현)',
       '전남대 경영학\n대신증권 선릉역지점장\n대신증권 영업부장\n대신증권 금융주치의추진부장\n대신증권 강북지역본부장\n대신증권 IB본부장, 퇴직연금담당',
       '서울대 법학\n대검찰청 검찰총장\n학교법인 현암학원 이사장(현)\n변호사정상명법률사무소 변호사(현)',
       '연세대 정치학(석사)\n한국투자증권\xa0평촌지점 상무\n부영주택 기획관리부 상무\n부영주택 영업부 상무',
       '홍익대 전자계산학(석사)\n대신증권 전산개발팀장\n대신증권 고객지원부장\n대신증권 IT본부장\n대신증권 IT서비스본부장',
       '서울대 경영학\n대신투자신탁운용\xa0상무이사\n대신증권 전무\n대신증권 부사장',
       '성균관대 불어불문학\n대신증권 대치동지점 이사대우지점장\n대신증권 남대문지점 이사대우지점장\n대신증권 종로지점 이사대우지점장\n대신증권\xa0중부지역본부장',
       '서강대 경제학\n대신증권\xa0영업기획부장\n대신증권\xa0기획실장\n대신증권\xa0인재전략부 이사대우부장',
       '한국외국어대 \xa0경영학(석사)\n대신증권 강남지역본부장\n대신증권 WM추진본부장\n대신증권 Wholesale본부장\n대신증권 Wholesale사업단장\n기획본부장대신증권\xa0인재역량센터장, 기업금융사업단장',
       '한국과학기술원 화학공학(석사)\n굿모닝신한증권 기업분석부 연구원\n대신증권 투자전략부장',
       '고려대 경영학(석사)\n대우증권\xa0IB사업부문 전무\n대우증권\xa0해외사업부문 부사장\n대우증권\xa0전략기획본부 부사장',
       '서울대 경영학\n한국물산 경영기획팀장\n우리투자증권\xa0기업금융2팀장\n하이투자증권\xa0주식인수팀 이사',
       '조지아공대 항공우주학(박사)\n대신증권\xa0파생상품운용부장\n대신증권\xa0자산운용본부 이사대우본부장',
       '한양대 세무학(석사)\n국세청 조사과장\n중부지방국세청 조사국장\n세무법인 리앤케이 대표(현)',
       '성균관대 회계학\n대신증권 무역센터지점장\n대신증권 분당지점장\n대신증권 강남선릉센터 이사대우센터장\n대신증권 강서지역본부장',
       '강원대 경영학\n우리투자증권 리서치센터 파트장\n대신증권\xa0Global사업본부 이사대우본부장',
       '한양대 경영학\n대신증권 정자동지점장\n대신증권 송탄지점장\n대신증권 중부지역본부장\n대신증권 강남지역본부장',
       '연세대 경제학(석사)\n대신증권\xa0홍보실 이사대우실장\n대신증권\xa0브랜드전략실 이사대우실장',
       'Brown대 경제학(박사)\nLG경제연구원 금융연구실 실장\n수원대 경영학부 교수\nKAIST MBA교수\n자본시장연구원 부원장(현)',
       '연세대 수학\n대신증권\xa0트레이딩시스템부장\n대신증권\xa0IT개발부장',
       '부경대 무역학\n대신증권 마산지점장\n대신증권 부전동지점장\n대신증권 동래지점장',
       '강원대 경영학\n우리투자증권 리서치센터 파트장\n대신증권\xa0Global사업본부 이사대우본부장\n대신증권 Wholesale영업본부장',
       '영남공업전문대 전자전산학\n대신증권 IT전략부 팀장\n대신증권 IT개발부 팀장\n대신증권 온라인개발부장',
       '경북대 경영학\n대신증권 재무관리부 이사대우부장\n대신증권 리스크관리본부 이사대우본부장\n대신저축은행 준법감시인\n대신증권 리스크관리본부 이사대우본부장',
       '성균관대 회계학\n대신증권 무역센터지점장\n대신증권 강남선릉센터 이사대우센터장\n대신증권 강서지역본부장\n대신증권 동부지역본부장',
       '서강대 경제학\n대신증권\xa0영업기획부장\n대신증권\xa0기획실장\n대신증권\xa0인재전략부 이사대우부장\n대신증권 인재역량센터장',
       '전남대 경영학\n대신증권 영업부장\n대신증권 금융주치의추진부장\n대신증권 강북지역본부장\n대신증권 IB본부장, 퇴직연금담당\n대신증권 IB부문장',
       '동국대 무역학\n우리선물 해외선물부장\n대신증권 Global파생상품부장\n대신증권 구조화상품본부 이사대우본부장',
       '연세대 정치학(석사)\n한국투자증권 온라인사업추진단 부장\n한국투자증권\xa0평촌지점 상무보\n부영주택 기획관리부 상무\n부영주택 영업부 상무\n대신증권 스마트금융본부장',
       '연세대 경제학(석사)\nSBC WARBURG DILLON READ(현UBS증권) 법인영업이사\n푸르덴셜투자증권 홀세일사업본부장\n메릴린치증권 서울지점 상무\n대신증권 감사담당',
       '고려대 경영학\n대신증권 기획실장\n대신자산운용 전무\n대신증권 미래전략담당\n대신에프앤아이 경영기획본부장',
       '중앙대 사법학(석사)\n대신증권 법무실장\n대신자산운용 법무본부 이사대우본부장\n대신증권 법무지원실 이사대우실장\n대신증권 준법지원본부 이사대우본부장',
       '조지아공대 항공우주학(박사)\n대신증권\xa0파생상품운용부장\n대신증권\xa0자산운용본부 이사대우본부장\n대신증권 Trading Center장',
       '연세대 경제학(석사)\n우리CS자산운용 AI본부장\n대신증권 파생금융본부장\n대신증권 CM본부장\n대신증권\xa0Capital Market 사업단장\n대신증권 고객자산본부장',
       '연세대 경영학(석사)\n대신증권 신규업무추진팀장\n대신증권 감사실 팀장\n대신증권 감사실장',
       '전남대 국제경영학(석사)\n대신증권 명일동지점장\n대신증권 부천지점장\n대신증권 금융주치의전략부 이사대우부장',
       '서울대 경영학\n한국물산 경영기획팀장\n우리투자증권\xa0기업금융2팀장\n하이투자증권\xa0주식인수팀 이사\n대신증권 IB부부문장',
       '연세대 경제학(석사)\n대신증권\xa0홍보실 이사대우실장\n대신증권\xa0브랜드전략실 이사대우실장\n대신증권 기획본부장',
       '중앙대 무역학(박사)\n국세청,관세청,산업통상자원부 정부정책자체평가위원\n기획재정부 국제행사심사위원회 민간위원\n중앙대학교 산업ㆍ창업 경영대학원장(경영학부 교수)(현)',
       '카네기멜론대 금융공학(석사)\n우리프라이빗에쿼티 투자팀 이사\n도이치은행 상무대우증권 상무',
       '서울대 경영학(석사)\n안진회계법인\nL&C세무회계사무소 대표 공인회계사(현)',
       '연세대 경영학\n대신증권 장외파생상품부장\n대신증권 해외파생상품부장\n대신증권 파생영업본부장\n대신증권 구조화상품본부장\n대신증권 Wholesale사업단장',
       '카네기멜론대 금융공학(석사)\n우리프라이빗에쿼티 투자팀 이사\n도이치은행 상무\n대우증권 상무\n대신증권 Advisory본부장\n대신증권 \xa0IB3부문장',
       '한국외국어대 경영학(석사)\n대신증권 강남지역본부장\n대신증권 WM추진본부장\n대신증권 Wholesale본부장,\n대신증권 Wholesale사업단장,기획본부장\n대신증권 인재역량센터장, 기업금융사업단장',
       '서울대 경영학\n대신투자신탁운용 상무이사\n대신증권 전무\n대신증권 부사장',
       '홍익대 경영학\n대신증권 금융주치의전략부장\n대신증권 IB솔루션부장\n대신증권 IB2본부장\n대신증권 IB3본부장',
       '동국대 무역학\n우리선물 해외선물부장\n대신증권 Global파생상품부장\n대신증권 구조화상품본부 이사대우본부장\n대신증권 Market Solution부문 이사대우부문장',
       '성균관대 행정학(박사)\n감사원 감사위원\n금융위원회 금융행정인사혁신위원(현)',
       '동국대 경영학(석사)\n대신증권 강남역지점장\n대신증권 강남역삼센터 이사대우센터장\n대신증권 강남선릉센터 이사대우센터장',
       '전남대 회계학\n대신증권 목포지점장\n대신증권 광주지점장\n대신증권 광주센터장',
       '한국외국어대 경영학(석사)\n대신증권 CIC사업전략팀장\n대신증권 스마트금융부장\n대신증권 Operation&Technology본부 이사대우부본부장',
       '경희대 경제학\n대신증권 인사부장\n대신증권 재무관리부장\n대신증권 리스크관리본부 이사대우본부장\n대신저축은행 경영지원본부장\n대신저축은행 대표이사',
       '한양대 경영학\n대신증권 Global사업부장\n대신에프앤아이 경영기획본부 부본부장 /재무관리부장\n대신에프앤아이 경영기획본부장',
       '중앙대 사법학(석사)\n대신증권 법무실장\n대신자산운용 법무본부 이사대우본부장\n대신증권 법무지원실 이사대우실장\n대신증권 준법지원본부 이사대우본부장\n대신증권 준법지원담당 이사대우담당',
       '고려대 법학\n대신증권 화정동지점장\n대신증권 상무지점장\n대신증권 무등지점 이사대우지점장\n대신증권 서부지역본부장',
       '서울대 법학\n대검찰청 감찰부장(검사장)\n서울북부지방검찰청 검사장\n법무법인 (유)동인 변호사(현)',
       '경북대 경영학\n대신증권 SF부 팀장\n대신증권 프로젝트금융본부 이사대우본부장',
       '경북대 경영학\n대신증권 재무관리부 이사대우부장\n대신증권 리스크관리본부 이사대우본부장\n대신저축은행 준법감시인\n대신증권 리스크관리본부 이사대우본부장\n대신증권 리스크관리담당 이사대우담당',
       '연세대 수학\n대신증권\xa0트레이딩시스템부장\n대신증권\xa0IT개발부장\n대신증권 Operation&Technology본부장',
       '조지아공대 항공우주학(박사)\n대신증권\xa0파생상품운용부장\n대신증권\xa0자산운용본부 이사대우본부장\n대신증권 Trading Center장\n대신증권 Product부문장',
       '고려대 경영학\n대신증권 인사부장\n대신증권 원주지점장\n대신증권 리스크관리부장\n대신증권 리스크관리본부 이사대우본부장\n대신에프앤아이 경영기획본부장',
       '성균관대 회계학\n대신증권 무역센터지점장\n대신증권 강남선릉센터 이사대우센터장\n대신증권 강서지역본부장\n대신증권 동부지역본부장\n대신증권 금융주치의사업단장',
       '성균관대 무역학\n대신증권 브랜드전략실장\n대신증권 경영관리부장\n대신증권 경영기획실장\n대신증권 기획본부 이사대우부본부장',
       '고려대 경영학\n대신증권 기획실장\n대신자산운용 전무\n대신증권 미래전략담당\n대신에프앤아이 경영기획본부장\n대신증권 기획본부장/투자금융담당',
       '한양대 세무학(석사)\n국세청 조사과장\n중부지방국세청 조사국장\n세무법인 케이파트너즈 대표(현)',
       '연세대 수학\n대신증권\xa0트레이딩시스템부장\n대신증권\xa0IT개발부장\n대신증권 Operation&Technology본부장\n대신증권 IT본부장',
       '한양대 경영학\n대신증권 Global사업부장\n대신에프앤아이 경영기획본부 부본부장/재무관리부장\n대신에프앤아이 경영기획본부장',
       '홍익대 경영학\n대신증권 재무관리부장/자금부장\n대신증권 재무자금부장\n대신증권 법인금융상품본부장',
       '연세대 경영학\n대신증권 소비재그룹장\n대신증권 알파리서치부 팀장\n대신증권 마켓전략실 팀장\n대신증권 리서치부장\n대신증권 Research&Strategy 본부장',
       '서강대 경제학(석사)\n대신증권 채권운용부장\n대신증권 Trading Center 부센터장\n대신증권 자산운용본부 이사대우본부장',
       '동국대 무역학\n우리선물 해외선물부장\n대신증권 Global파생상품부장\n대신증권 구조화상품본부 이사대우본부장\n대신증권 Market Solution부문\n이사대우부문장\n대신증권 Market Solution부문장',
       '고려대 법학\n대신증권 화정동지점장\n대신증권 상무지점장\n대신증권 무등지점 이사대우지점장\n대신증권 서부지역본부장\n대신증권 강남지역본부장',
       '전남대 경영학\n대신증권 리테일채권부 이사대우부장\n대신증권 영업부 이사대우부장\n대신증권 신탁사업부 이사대우부장\n대신증권 목동WM센터 이사대우센터장',
       '연세대 경영학\n대신증권 장외파생상품부장\n대신증권 해외파생상품부장\n대신증권 파생영업본부장\n대신증권 구조화상품본부장\n대신증권 Wholesale사업단장\n대신증권 Solution&Product사업단장',
       '성균관대 행정학(박사)\n감사원 감사위원\n금융위원회\xa0금융발전심의위원(현)',
       '조지아공대 항공우주학(박사)\n대신증권\xa0파생상품운용부장\n대신증권\xa0자산운용본부 이사대우본부장\n대신증권 Trading Center장\n대신증권 Product부문장\n대신증권 경영기획본부장',
       '중앙대 산업정보학\n대신증권 IT개발부 팀장\n대신증권 WM개발부 팀장\n대신증권 IT개발부장',
       '연세대 인적자원개발학(석사)\n대신증권 인재지원부장\n대신증권 인재전략부장\n대신증권 인사부장',
       '연세대 경영학(석사)\n대신증권 신규업무추진팀장\n대신증권 감사실 팀장\n대신증권 감사실장\n대신증권 감사담당 이사대우담당',
       '한국외국어대\xa0경영학(석사)\n대신증권 강남지역본부장\n대신증권 WM추진본부장\n대신증권 Wholesale본부장,\n대신증권 Wholesale사업단장,기획본부장\n대신증권 인재역량센터장,기업금융사업단장',
       '서강대 경제학\n대신증권\xa0영업기획부장\n대신증권\xa0기획실장\n대신증권\xa0인재전략부 이사대우부장\n대신증권 인재역량센터장\n대신증권 경영지원본부장',
       '서울대 경제학\n메리츠종금증권 심사팀장\n메리츠종금증권 리스크관리본부장',
       '성균관대 법학\n대신증권 대치동지점장\n대신증권 강남대로센터장\n대신증권 청담WM센터장',
       '한국외국어대 경영학(석사)\n대신증권 CIC사업전략팀장\n대신증권 스마트금융부장\n대신증권 Operation&Technology본부\n이사대우부본부장',
       '중앙대 경제학(석사)\n대신증권 브랜드전략실장\n대신저축은행 기획부장\n대신자산운용 경영지원그룹 이사대우그룹장\n대신증권 WM추진부 이사대우부장\n대신증권 준법감시인/준법지원부문장',
       '경희대 경제학\n대신증권 인사부장\n대신증권 재무관리부장\n대신증권 리스크관리본부 이사대우본부장\n대신저축은행 경영지원본부장\n대신저축은행 대표이사\n대신증권 경영지원총괄/IB사업단장',
       '성균관대 행정학(박사)\n감사원 감사위원\n금융위원회\xa0적극행정심의위원(現)',
       '경희대 경제학\n대신증권 인사부장\n대신증권 재무관리부장\n대신증권 리스크관리본부 이사대우본부장\n대신저축은행 경영지원본부장\n대신저축은행 대표이사\n대신증권 경영지원총괄/IB사업단장\n대신증권 부사장',
       '한양대 경영학\n대신증권 Global사업부장\n대신에프앤아이 경영기획본부 부본부장\n대신에프앤아이 경영기획본부장\n대신증권 전략지원부문장',
       '전남대 국제경영학(석사)\n대신증권 명일동지점장\n대신증권 부천지점장\n대신증권 금융주치의전략부 이사대우부장\n대신증권 재경1WM본부장',
       '전북대 회계학\n대신증권 인수공모2부\n대신증권 비서실장\n대신증권 비서/브랜드본부장',
       '성균관대 회계학\n대신증권 무역센터지점장\n대신증권 강남선릉센터 이사대우센터장\n대신증권 강서지역본부장\n대신증권 동부지역본부장\n대신증권 금융주치의사업단장\n대신증권WM사업단장',
       '연세대 경제학(석사)\n대신증권\xa0홍보실 이사대우실장\n대신증권\xa0브랜드전략실 이사대우실장\n대신증권 기획본부장\n대신증권 고객자산본부장/홍보부문장',
       '연세대 경영학(석사)\n대신증권 신규업무추진팀장\n대신증권 감사실 팀장\n대신증권 감사실장\n대신증권 감사담당 이사대우담당\n대신증권 감사부문장',
       '성균관대 경영학\n대신증권 미래전략실장\n대신증권 전략지원실장',
       '성균관대 무역학\n대신증권 전략기획실장\n대신증권 기획본부 이사대우부본부장\n대신증권 영업부장\n대신에프앤아이 경영기획본부장',
       '충북대 전산학\n대신증권 차세대시스템부 팀장\n대신증권 IT시스템부 팀장\n대신증권 IT지원부장',
       '조선대 회계학\n대신자산운용 법무본부장\n대신자산운용 리스크관리본부장/준법감시인\n대신에이엠씨 감사\n대신저축은행 준법감시인\n대신증권 법무지원부문장',
       '한국과학기술원 MBA\n대신증권 IB2본부장\n대신증권 IPO본부 이사대우본부장',
       '서울대 법학\n대검찰청 감찰부장(검사장)\n서울북부지방검찰청 검사장\n법무법인 (유)동인 변호사(現)',
       '연세대 경영학\n대신증권 소비재그룹장\n대신증권 알파리서치부 팀장\n대신증권 마켓전략실 팀장\n대신증권 리서치부장',
       '세종대 회계학\n대신증권 광명센터장\n대신증권 대림동지점장\n대신증권 WM추진부 이사대우부장',
       '서울대 경영학(석사)\n안진회계법인\nL&C세무회계사무소 대표 공인회계사(現)',
       'University of Bath 사회과학대학원(석사)\n서울지방국세청 청장\n법무법인 태평양 고문(現)',
       '서울대 경영학\n대신투자신탁운용 상무이사\n대신증권 전무\n대신증권 부사장\n대신증권 사장',
       '가천대학교 무역학\n대신증권 수지지점장\n대신증권 여의도영업부장',
       '성균관대 행정학(박사)\n감사원 감사위원\n現)금융위원회 적극행정심의위원',
       '중앙대 무역학\n대신증권 채권운용부 팀장\n대신증권 리테일상품팀 팀장\n대신증권 감사실장',
       'Ohio State University 정책대학원(박사)\n한국조세연구원 제9대 원장\n서울시립대 제8대 총장\n現)서울시립대 세무대학원 교수',
       '경희대 경제학\n메리츠증권 투자금융팀 이사\n하나금융투자 커버리지2실 상무대우\nDB금융투자 FAS1팀 이사\nIBK투자증권 Coverage3팀 이사',
       '서울대 기계공학\nSC제일은행 외환파생상품 이사대우\n미래에셋증권 FICC파생운용팀 수석매니저\nKTB투자증권 Financial Market본부 상무',
       '전남대 경영학\n대신증권 리테일채권 이사대우부장\n대신증권 영업부 이사대우부장\n대신증권 신탁사업부 이사대우부장\n대신증권 목동WM센터 이사대우센터장\n신증권 영업부장',
       '충북대학교 전산학\n대신증권 차세대시스템부 팀장\n대신증권 IT시스템부 팀장\n대신증권 IT지원부장',
       '서울대 법학\n대검찰청 감찰부장(검사장)\n서울북부지방검찰청 검사장\n現)법무법인 (유)동인 변호사',
       '동아대 경영학(박사)\n대신증권 사하지점장\n대신증권 부산센터 이사대우센터장',
       '세종대학교 회계학\n대신증권 광명센터장\n대신증권 대림동지점장\n대신증권 WM추진부 이사대우부장',
       '한국외대 경영학(석사)\n대신증권 CIC사업전략팀장\n대신증권 스마트금융부장\n대신증권 Operation&Technology본부 이사대우부본부장',
       '성균관대학교 경영학\n대신증권 미래전략실장\n대신증권 전략지원실장',
       '조선대 회계학\n대신자산운용 법무본부장\n대신자산운용 리스크관리본부장/준법감시인\n대신에이엠씨 감사\n대신저축은행 준법감시인\n대신증권 법무지원부문장\n대신증권 감사부문장',
       'University of Bath 사회과학대학원(석사)\n서울지방국세청 청장\n現)법무법인 태평양 고문',
       '서강대 경제학\n대신증권 영업기획부장\n대신증권 기획실장\n대신증권 인재전략부 이사대우부장\n대신증권 인재역량센터장\n대신증권 경영지원본부장\n대신증권 준법지원부문장',
       '서울대 행정학(석사)\nBank of America 서울지점 지점장\n메리츠증권 자산운용본부 전무',
       'Florida International University 경영대학원(박사)\n한국회계정보학회 회장\n중앙대 제15대 총장\n現)중앙대 경영경제대 경영학부 교수',
       '경희대 경제학\n대신증권 인사부장\n대신증권 재무관리부장\n대신증권 리스크관리본부 이사대우본부장\n대신저축은행 경영지원본부장\n대신저축은행 대표이사\n대신증권 경영지원총괄, IB사업단장\n대신증권 부사장',
       '전북대 회계학\n대신증권 인수공모2부\n대신증권 비서실장\n대신증권 비서/브랜드본부장\n대신증권 WM사업단장,디지털사업단장',
       '가천대학교 무역학\n대신증권 수지지점장\n대신증권 여의도영업부장\n재경1WM부문장',
       '조선대 회계학\n대신자산운용 법무본부장\n대신자산운용 리스크관리본부장/준법감시인대신에이엠씨 감사\n대신저축은행 준법감시인\n대신증권 법무지원부문장\n대신증권 감사부문장',
       '동국대 경영학(석사)\n대신증권 강남역지점장\n대신증권 강남역삼센터 이사대우센터장대신증권 강남선릉센터 이사대우센터장',
       '서강대 사회학\n대신증권 상품전략부장\n대신증권 상품기획부장\n대신증권 리테일기획부장',
       '건국대 법학(박사)\n국가청렴위원회 사무처장\n제58대 법무부장관\n現)재단법인 행복세상 이사장',
       '전북대 회계학\n대신증권 비서실장\n대신증권 비서/브랜드본부장\n대신증권 WM사업단장,디지털사업단장',
       '원광대 통계학\n대신증권 정보보호부장',
       '경북대 경영학\n대신증권 부동산금융본부장\n대신증권 프로젝트금융본부 이사\n대우본부장',
       '중앙대 응용통계학\n대신증권 IB1본부 팀장\n대신증권 ECM본부 이사대우본부장',
       '중앙대 경영학\n대신증권 인사부장\n대신증권 비서실 이사대우실장',
       '연세대 경영학\n대신증권 소비재그룹장\n대신증권 리서치부장',
       '중앙대 산업정보학\n대신증권 WM개발부장\n대신증권 IT개발부장',
       '경희대 경제학\n대신증권 인사부장\n대신증권 재무관리부장\n대신증권 리스크관리본부 이사대우본부장\n대신저축은행 경영지원본부장\n대신저축은행 대표이사\n대신증권 경영지원총괄, IB사업단장',
       '연세대 경영학(석사)\n대신증권 감사실장\n대신증권 감사부문장',
       '중앙대 무역학\n대신증권 리테일상품팀장\n대신증권 감사실장',
       '인하대 정치외교학\nNH투자증권 부동산금융부장\nKB증권 프로젝트금융부 이사',
       '한국외대 경영학(석사)\n대신증권 스마트금융부장\n대신증권 Operation&Technology본부 이사대우부본부장\n대신증권 디지털부문장',
       '고려대 경영학\n대신증권 리스크관리부장\n대신증권 자산운용본부장\n대신증권 멀티운용본부장\n대신증권 패시브운용본부장',
       '세종대학교 회계학\n대신증권 대림동지점장\n대신증권 WM추진부 이사대우부장\nWM추진부문장',
       '동국대 무역학\n대신증권 경영기획실 이사대우실장',
       '인하대 경제통상학\n대신증권 역량개발부장\n대신증권 Club1962 이사대우센터장',
       '경북대 경영학\n대신증권 포항지점장\n대신증권 동대구지점 이사대우지점장',
       '동아대 경영학(박사)\n대신증권 사하지점장\n대신증권 부산센터 이사대우센터장\n대신증권 영업부장',
       '경북대 경영학\n대신증권 부동산금융본부장\n대신증권 프로젝트금융본부 이사대우본부장',
       '한국외국어대 국제금융학(석사)\n대신증권 이촌동지점장\n대신증권 목동WM센터 이사대우센터장',
       '연세대학교 경영대학원(박사)\nArthur Anderson Consulting 컨설던트\n연세대학교 대학원 경영연구소 연구원\n現)학교법인 광운학원 이사장',
       '고려대 경영학\n대신증권 리스크관리부장\n대신증권 자산운용본부장\n대신증권 멀티운용본부장\n대신증권 패시브운용본부장\n대신증권 고객자산부문 부부문장',
       '한양대 신문방송학\n대신증권 홍보실 이사대우실장',
       '중앙대 산업정보학\n대신증권 WM개발부장\n 대신증권 IT개발부장',
       '미시간대학교 경영대학원 MBA\n국세청 조사국 국장\n제22대 국세청장\n現)법무법인(유) 대륙아주 고문'],
      dtype=object)

# 데이터 전처리

In [14]:
#의결권 있는 주식수 Nan 전부 0처리
df['의결권 있는 주식수'].isnull().sum()

11

In [15]:
df['의결권 있는 주식수'].fillna(0.0, inplace=True)

In [16]:
df['의결권 있는 주식수'].isnull().sum()

0

In [17]:
#'\xa0' 처리
df['주요경력']=df['주요경력'].str.replace('\xa0', '')

In [18]:
df['주요경력'].unique()

array(['서울대 경영학(석사)\n대신증권 시흥동지점장\n대신증권 명일동지점장\n대신증권 퇴직연금컨설팅본부장\n대신증권 퇴직연금본부장',
       '한국과학기술원 화학공학(석사)\n대신증권 투자전략부장',
       '한국외국어대 경영학(석사)\n대신증권 강남지역본부장\n대신증권 WM추진본부장\n대신증권 Wholesale본부장\n대신증권 Wholesale사업단장\n기획본부장대신증권 인재역량센터장\n기업금융사업단장',
       '서울대 법학(석사)\n대한중재인협회 회장\n법무법인 태평양 대표변호사(현)',
       '전북대 회계학\n대신증권 인수공모2부\n대신증권 비서실장',
       '성균관대 불어불문학\n대신증권 대치동지점 이사대우지점장\n대신증권 남대문지점 이사대우지점장\n대신증권 종로지점 이사대우지점장\n대신증권 강남지역본부장\n대신증권중부지역본부장',
       '조지아공대 항공우주학(박사)\n대신증권 파생상품운용부 부장\n대신증권 자산운용본부 이사대우본부장',
       '고려대 법학\n대신증권 화정동지점장\n대신증권 상무지점장\n대신증권 무등지점 이사대우지점장',
       '서강대 경제학\n대신증권 영업기획부 부장\n대신증권 기획실 실장\n대신증권 인재전략부 이사대우부장',
       '고려대 경영대학원(석사)\n금융감독원 부원장보\nLIG손해보험 상근감사위원\n하비스트 대표(현)',
       '성균관대 회계학\n대신증권 무역센터지점장\n대신증권분당지점장\n대신증권 강남선릉센터 이사대우센터장\n대신증권 강서지역본부장',
       '한국외국어대 무역학(석사)\n우리투자증권 기업분석팀장\n대신증권 리서치센터장\n대신증권 기획본부장',
       '연세대 경영학\n대신증권 법인영업부장\n대신증권 Wholesale1본부장\n대신증권 Wholesale영업본부장',
       '연세대 경제학(석사)\n우리CS자산운용 AI본부장\n대신증권 파생금융본부장\n대신증권 CM본부장\n대신증권Capital Market 사업단장',
       '대전대 경영학(박사)\n대신증권 관재팀장\n대신증권 총무부장',
       '연세대 경제학(석사)\nSBC WARBURG DILLON READ(현UBS증권) 법인영업이사\n푸르덴셜투자증권 홀세일사업본부장\n메릴린치증권 서울지점 상무',
       '한양대 경영학\n대신증권 송탄지점장\n대신증권 중부지역본부장\n대신증권 강남지역본부장',
       '연세대 정치학(석사)\n한국투자증권 평촌지점 상무\n부영주택 기획관리부 상무\n부영주택 영업부 상무',
       '서울대 경영학(석사)\nIBK투자증권 IB사업부 부사장\n대신증권 IB본부장\n대신증권 기업금융사업단장',
       'KDI국제정책대학원(석사)\n삼성증권 상품개발팀장\n동양증권 상품기획본부장\n대신증권 고객상품본부장',
       '상명여자사범대', '서울대 경영학\n대신투자신탁운용 상무이사\n대신증권 전무\n대신증권 부사장',
       '울산대 경영학\n대신증권 울산남지점장\n대신증권무거동지점장\n대신증권 울산지점 이사대우지점장\n대신증권 동부지역본부장\n대신증권 동래지점장',
       '연세대 경영대학원(석사)\n대신증권 홍보실 이사대우실장\n대신증권 브랜드전략실 이사대우실장',
       '홍익대 전자계산학(석사)\n대신증권 전산개발팀장\n대신증권 고객지원부장\n대신증권 IT본부장',
       '중앙대 무역학(박사)\n국세청,관세청,산업통상자원부 정부정책자체평가위원\n기획재정부 국제행사심사위원회 민간위원\n중앙대 상경학부 교수(현)',
       '명지대 경영학\n서울지방국세청장\n재단법인 정평장학회 이사장\n피앤비세무컨설팅 대표(현)',
       '연세대 경영학\n대신증권 장외파생상품부장\n대신증권 파생상품영업부장\n대신증권 해외파생상품부장\n대신증권 파생영업본부장',
       'Brown대 경제학(박사)\nLG경제연구원 금융연구실 실장\n수원대학교 경영학부 교수\nKAIST MBA교수\n자본시장연구원 부원장(현)',
       '전남대 경영학\n대신증권 선릉역지점장\n대신증권 영업부장\n대신증권 금융주치의추진부장\n대신증권 강북지역본부장\n대신증권 IB본부장, 퇴직연금담당',
       '서울대 법학\n대검찰청 검찰총장\n학교법인 현암학원 이사장(현)\n변호사정상명법률사무소 변호사(현)',
       '연세대 정치학(석사)\n한국투자증권평촌지점 상무\n부영주택 기획관리부 상무\n부영주택 영업부 상무',
       '홍익대 전자계산학(석사)\n대신증권 전산개발팀장\n대신증권 고객지원부장\n대신증권 IT본부장\n대신증권 IT서비스본부장',
       '서울대 경영학\n대신투자신탁운용상무이사\n대신증권 전무\n대신증권 부사장',
       '성균관대 불어불문학\n대신증권 대치동지점 이사대우지점장\n대신증권 남대문지점 이사대우지점장\n대신증권 종로지점 이사대우지점장\n대신증권중부지역본부장',
       '서강대 경제학\n대신증권영업기획부장\n대신증권기획실장\n대신증권인재전략부 이사대우부장',
       '한국외국어대 경영학(석사)\n대신증권 강남지역본부장\n대신증권 WM추진본부장\n대신증권 Wholesale본부장\n대신증권 Wholesale사업단장\n기획본부장대신증권인재역량센터장, 기업금융사업단장',
       '한국과학기술원 화학공학(석사)\n굿모닝신한증권 기업분석부 연구원\n대신증권 투자전략부장',
       '고려대 경영학(석사)\n대우증권IB사업부문 전무\n대우증권해외사업부문 부사장\n대우증권전략기획본부 부사장',
       '서울대 경영학\n한국물산 경영기획팀장\n우리투자증권기업금융2팀장\n하이투자증권주식인수팀 이사',
       '조지아공대 항공우주학(박사)\n대신증권파생상품운용부장\n대신증권자산운용본부 이사대우본부장',
       '한양대 세무학(석사)\n국세청 조사과장\n중부지방국세청 조사국장\n세무법인 리앤케이 대표(현)',
       '성균관대 회계학\n대신증권 무역센터지점장\n대신증권 분당지점장\n대신증권 강남선릉센터 이사대우센터장\n대신증권 강서지역본부장',
       '강원대 경영학\n우리투자증권 리서치센터 파트장\n대신증권Global사업본부 이사대우본부장',
       '한양대 경영학\n대신증권 정자동지점장\n대신증권 송탄지점장\n대신증권 중부지역본부장\n대신증권 강남지역본부장',
       '연세대 경제학(석사)\n대신증권홍보실 이사대우실장\n대신증권브랜드전략실 이사대우실장',
       'Brown대 경제학(박사)\nLG경제연구원 금융연구실 실장\n수원대 경영학부 교수\nKAIST MBA교수\n자본시장연구원 부원장(현)',
       '연세대 수학\n대신증권트레이딩시스템부장\n대신증권IT개발부장',
       '부경대 무역학\n대신증권 마산지점장\n대신증권 부전동지점장\n대신증권 동래지점장',
       '강원대 경영학\n우리투자증권 리서치센터 파트장\n대신증권Global사업본부 이사대우본부장\n대신증권 Wholesale영업본부장',
       '영남공업전문대 전자전산학\n대신증권 IT전략부 팀장\n대신증권 IT개발부 팀장\n대신증권 온라인개발부장',
       '경북대 경영학\n대신증권 재무관리부 이사대우부장\n대신증권 리스크관리본부 이사대우본부장\n대신저축은행 준법감시인\n대신증권 리스크관리본부 이사대우본부장',
       '성균관대 회계학\n대신증권 무역센터지점장\n대신증권 강남선릉센터 이사대우센터장\n대신증권 강서지역본부장\n대신증권 동부지역본부장',
       '서강대 경제학\n대신증권영업기획부장\n대신증권기획실장\n대신증권인재전략부 이사대우부장\n대신증권 인재역량센터장',
       '전남대 경영학\n대신증권 영업부장\n대신증권 금융주치의추진부장\n대신증권 강북지역본부장\n대신증권 IB본부장, 퇴직연금담당\n대신증권 IB부문장',
       '동국대 무역학\n우리선물 해외선물부장\n대신증권 Global파생상품부장\n대신증권 구조화상품본부 이사대우본부장',
       '연세대 정치학(석사)\n한국투자증권 온라인사업추진단 부장\n한국투자증권평촌지점 상무보\n부영주택 기획관리부 상무\n부영주택 영업부 상무\n대신증권 스마트금융본부장',
       '연세대 경제학(석사)\nSBC WARBURG DILLON READ(현UBS증권) 법인영업이사\n푸르덴셜투자증권 홀세일사업본부장\n메릴린치증권 서울지점 상무\n대신증권 감사담당',
       '고려대 경영학\n대신증권 기획실장\n대신자산운용 전무\n대신증권 미래전략담당\n대신에프앤아이 경영기획본부장',
       '중앙대 사법학(석사)\n대신증권 법무실장\n대신자산운용 법무본부 이사대우본부장\n대신증권 법무지원실 이사대우실장\n대신증권 준법지원본부 이사대우본부장',
       '조지아공대 항공우주학(박사)\n대신증권파생상품운용부장\n대신증권자산운용본부 이사대우본부장\n대신증권 Trading Center장',
       '연세대 경제학(석사)\n우리CS자산운용 AI본부장\n대신증권 파생금융본부장\n대신증권 CM본부장\n대신증권Capital Market 사업단장\n대신증권 고객자산본부장',
       '연세대 경영학(석사)\n대신증권 신규업무추진팀장\n대신증권 감사실 팀장\n대신증권 감사실장',
       '전남대 국제경영학(석사)\n대신증권 명일동지점장\n대신증권 부천지점장\n대신증권 금융주치의전략부 이사대우부장',
       '서울대 경영학\n한국물산 경영기획팀장\n우리투자증권기업금융2팀장\n하이투자증권주식인수팀 이사\n대신증권 IB부부문장',
       '연세대 경제학(석사)\n대신증권홍보실 이사대우실장\n대신증권브랜드전략실 이사대우실장\n대신증권 기획본부장',
       '중앙대 무역학(박사)\n국세청,관세청,산업통상자원부 정부정책자체평가위원\n기획재정부 국제행사심사위원회 민간위원\n중앙대학교 산업ㆍ창업 경영대학원장(경영학부 교수)(현)',
       '카네기멜론대 금융공학(석사)\n우리프라이빗에쿼티 투자팀 이사\n도이치은행 상무대우증권 상무',
       '서울대 경영학(석사)\n안진회계법인\nL&C세무회계사무소 대표 공인회계사(현)',
       '연세대 경영학\n대신증권 장외파생상품부장\n대신증권 해외파생상품부장\n대신증권 파생영업본부장\n대신증권 구조화상품본부장\n대신증권 Wholesale사업단장',
       '카네기멜론대 금융공학(석사)\n우리프라이빗에쿼티 투자팀 이사\n도이치은행 상무\n대우증권 상무\n대신증권 Advisory본부장\n대신증권 IB3부문장',
       '한국외국어대 경영학(석사)\n대신증권 강남지역본부장\n대신증권 WM추진본부장\n대신증권 Wholesale본부장,\n대신증권 Wholesale사업단장,기획본부장\n대신증권 인재역량센터장, 기업금융사업단장',
       '홍익대 경영학\n대신증권 금융주치의전략부장\n대신증권 IB솔루션부장\n대신증권 IB2본부장\n대신증권 IB3본부장',
       '동국대 무역학\n우리선물 해외선물부장\n대신증권 Global파생상품부장\n대신증권 구조화상품본부 이사대우본부장\n대신증권 Market Solution부문 이사대우부문장',
       '성균관대 행정학(박사)\n감사원 감사위원\n금융위원회 금융행정인사혁신위원(현)',
       '동국대 경영학(석사)\n대신증권 강남역지점장\n대신증권 강남역삼센터 이사대우센터장\n대신증권 강남선릉센터 이사대우센터장',
       '전남대 회계학\n대신증권 목포지점장\n대신증권 광주지점장\n대신증권 광주센터장',
       '한국외국어대 경영학(석사)\n대신증권 CIC사업전략팀장\n대신증권 스마트금융부장\n대신증권 Operation&Technology본부 이사대우부본부장',
       '경희대 경제학\n대신증권 인사부장\n대신증권 재무관리부장\n대신증권 리스크관리본부 이사대우본부장\n대신저축은행 경영지원본부장\n대신저축은행 대표이사',
       '한양대 경영학\n대신증권 Global사업부장\n대신에프앤아이 경영기획본부 부본부장 /재무관리부장\n대신에프앤아이 경영기획본부장',
       '중앙대 사법학(석사)\n대신증권 법무실장\n대신자산운용 법무본부 이사대우본부장\n대신증권 법무지원실 이사대우실장\n대신증권 준법지원본부 이사대우본부장\n대신증권 준법지원담당 이사대우담당',
       '고려대 법학\n대신증권 화정동지점장\n대신증권 상무지점장\n대신증권 무등지점 이사대우지점장\n대신증권 서부지역본부장',
       '서울대 법학\n대검찰청 감찰부장(검사장)\n서울북부지방검찰청 검사장\n법무법인 (유)동인 변호사(현)',
       '경북대 경영학\n대신증권 SF부 팀장\n대신증권 프로젝트금융본부 이사대우본부장',
       '경북대 경영학\n대신증권 재무관리부 이사대우부장\n대신증권 리스크관리본부 이사대우본부장\n대신저축은행 준법감시인\n대신증권 리스크관리본부 이사대우본부장\n대신증권 리스크관리담당 이사대우담당',
       '연세대 수학\n대신증권트레이딩시스템부장\n대신증권IT개발부장\n대신증권 Operation&Technology본부장',
       '조지아공대 항공우주학(박사)\n대신증권파생상품운용부장\n대신증권자산운용본부 이사대우본부장\n대신증권 Trading Center장\n대신증권 Product부문장',
       '고려대 경영학\n대신증권 인사부장\n대신증권 원주지점장\n대신증권 리스크관리부장\n대신증권 리스크관리본부 이사대우본부장\n대신에프앤아이 경영기획본부장',
       '성균관대 회계학\n대신증권 무역센터지점장\n대신증권 강남선릉센터 이사대우센터장\n대신증권 강서지역본부장\n대신증권 동부지역본부장\n대신증권 금융주치의사업단장',
       '성균관대 무역학\n대신증권 브랜드전략실장\n대신증권 경영관리부장\n대신증권 경영기획실장\n대신증권 기획본부 이사대우부본부장',
       '고려대 경영학\n대신증권 기획실장\n대신자산운용 전무\n대신증권 미래전략담당\n대신에프앤아이 경영기획본부장\n대신증권 기획본부장/투자금융담당',
       '한양대 세무학(석사)\n국세청 조사과장\n중부지방국세청 조사국장\n세무법인 케이파트너즈 대표(현)',
       '연세대 수학\n대신증권트레이딩시스템부장\n대신증권IT개발부장\n대신증권 Operation&Technology본부장\n대신증권 IT본부장',
       '한양대 경영학\n대신증권 Global사업부장\n대신에프앤아이 경영기획본부 부본부장/재무관리부장\n대신에프앤아이 경영기획본부장',
       '홍익대 경영학\n대신증권 재무관리부장/자금부장\n대신증권 재무자금부장\n대신증권 법인금융상품본부장',
       '연세대 경영학\n대신증권 소비재그룹장\n대신증권 알파리서치부 팀장\n대신증권 마켓전략실 팀장\n대신증권 리서치부장\n대신증권 Research&Strategy 본부장',
       '서강대 경제학(석사)\n대신증권 채권운용부장\n대신증권 Trading Center 부센터장\n대신증권 자산운용본부 이사대우본부장',
       '동국대 무역학\n우리선물 해외선물부장\n대신증권 Global파생상품부장\n대신증권 구조화상품본부 이사대우본부장\n대신증권 Market Solution부문\n이사대우부문장\n대신증권 Market Solution부문장',
       '고려대 법학\n대신증권 화정동지점장\n대신증권 상무지점장\n대신증권 무등지점 이사대우지점장\n대신증권 서부지역본부장\n대신증권 강남지역본부장',
       '전남대 경영학\n대신증권 리테일채권부 이사대우부장\n대신증권 영업부 이사대우부장\n대신증권 신탁사업부 이사대우부장\n대신증권 목동WM센터 이사대우센터장',
       '연세대 경영학\n대신증권 장외파생상품부장\n대신증권 해외파생상품부장\n대신증권 파생영업본부장\n대신증권 구조화상품본부장\n대신증권 Wholesale사업단장\n대신증권 Solution&Product사업단장',
       '성균관대 행정학(박사)\n감사원 감사위원\n금융위원회금융발전심의위원(현)',
       '조지아공대 항공우주학(박사)\n대신증권파생상품운용부장\n대신증권자산운용본부 이사대우본부장\n대신증권 Trading Center장\n대신증권 Product부문장\n대신증권 경영기획본부장',
       '중앙대 산업정보학\n대신증권 IT개발부 팀장\n대신증권 WM개발부 팀장\n대신증권 IT개발부장',
       '연세대 인적자원개발학(석사)\n대신증권 인재지원부장\n대신증권 인재전략부장\n대신증권 인사부장',
       '연세대 경영학(석사)\n대신증권 신규업무추진팀장\n대신증권 감사실 팀장\n대신증권 감사실장\n대신증권 감사담당 이사대우담당',
       '한국외국어대경영학(석사)\n대신증권 강남지역본부장\n대신증권 WM추진본부장\n대신증권 Wholesale본부장,\n대신증권 Wholesale사업단장,기획본부장\n대신증권 인재역량센터장,기업금융사업단장',
       '서강대 경제학\n대신증권영업기획부장\n대신증권기획실장\n대신증권인재전략부 이사대우부장\n대신증권 인재역량센터장\n대신증권 경영지원본부장',
       '서울대 경제학\n메리츠종금증권 심사팀장\n메리츠종금증권 리스크관리본부장',
       '성균관대 법학\n대신증권 대치동지점장\n대신증권 강남대로센터장\n대신증권 청담WM센터장',
       '한국외국어대 경영학(석사)\n대신증권 CIC사업전략팀장\n대신증권 스마트금융부장\n대신증권 Operation&Technology본부\n이사대우부본부장',
       '중앙대 경제학(석사)\n대신증권 브랜드전략실장\n대신저축은행 기획부장\n대신자산운용 경영지원그룹 이사대우그룹장\n대신증권 WM추진부 이사대우부장\n대신증권 준법감시인/준법지원부문장',
       '경희대 경제학\n대신증권 인사부장\n대신증권 재무관리부장\n대신증권 리스크관리본부 이사대우본부장\n대신저축은행 경영지원본부장\n대신저축은행 대표이사\n대신증권 경영지원총괄/IB사업단장',
       '성균관대 행정학(박사)\n감사원 감사위원\n금융위원회적극행정심의위원(現)',
       '경희대 경제학\n대신증권 인사부장\n대신증권 재무관리부장\n대신증권 리스크관리본부 이사대우본부장\n대신저축은행 경영지원본부장\n대신저축은행 대표이사\n대신증권 경영지원총괄/IB사업단장\n대신증권 부사장',
       '한양대 경영학\n대신증권 Global사업부장\n대신에프앤아이 경영기획본부 부본부장\n대신에프앤아이 경영기획본부장\n대신증권 전략지원부문장',
       '전남대 국제경영학(석사)\n대신증권 명일동지점장\n대신증권 부천지점장\n대신증권 금융주치의전략부 이사대우부장\n대신증권 재경1WM본부장',
       '전북대 회계학\n대신증권 인수공모2부\n대신증권 비서실장\n대신증권 비서/브랜드본부장',
       '성균관대 회계학\n대신증권 무역센터지점장\n대신증권 강남선릉센터 이사대우센터장\n대신증권 강서지역본부장\n대신증권 동부지역본부장\n대신증권 금융주치의사업단장\n대신증권WM사업단장',
       '연세대 경제학(석사)\n대신증권홍보실 이사대우실장\n대신증권브랜드전략실 이사대우실장\n대신증권 기획본부장\n대신증권 고객자산본부장/홍보부문장',
       '연세대 경영학(석사)\n대신증권 신규업무추진팀장\n대신증권 감사실 팀장\n대신증권 감사실장\n대신증권 감사담당 이사대우담당\n대신증권 감사부문장',
       '성균관대 경영학\n대신증권 미래전략실장\n대신증권 전략지원실장',
       '성균관대 무역학\n대신증권 전략기획실장\n대신증권 기획본부 이사대우부본부장\n대신증권 영업부장\n대신에프앤아이 경영기획본부장',
       '충북대 전산학\n대신증권 차세대시스템부 팀장\n대신증권 IT시스템부 팀장\n대신증권 IT지원부장',
       '조선대 회계학\n대신자산운용 법무본부장\n대신자산운용 리스크관리본부장/준법감시인\n대신에이엠씨 감사\n대신저축은행 준법감시인\n대신증권 법무지원부문장',
       '한국과학기술원 MBA\n대신증권 IB2본부장\n대신증권 IPO본부 이사대우본부장',
       '서울대 법학\n대검찰청 감찰부장(검사장)\n서울북부지방검찰청 검사장\n법무법인 (유)동인 변호사(現)',
       '연세대 경영학\n대신증권 소비재그룹장\n대신증권 알파리서치부 팀장\n대신증권 마켓전략실 팀장\n대신증권 리서치부장',
       '세종대 회계학\n대신증권 광명센터장\n대신증권 대림동지점장\n대신증권 WM추진부 이사대우부장',
       '서울대 경영학(석사)\n안진회계법인\nL&C세무회계사무소 대표 공인회계사(現)',
       'University of Bath 사회과학대학원(석사)\n서울지방국세청 청장\n법무법인 태평양 고문(現)',
       '서울대 경영학\n대신투자신탁운용 상무이사\n대신증권 전무\n대신증권 부사장\n대신증권 사장',
       '가천대학교 무역학\n대신증권 수지지점장\n대신증권 여의도영업부장',
       '성균관대 행정학(박사)\n감사원 감사위원\n現)금융위원회 적극행정심의위원',
       '중앙대 무역학\n대신증권 채권운용부 팀장\n대신증권 리테일상품팀 팀장\n대신증권 감사실장',
       'Ohio State University 정책대학원(박사)\n한국조세연구원 제9대 원장\n서울시립대 제8대 총장\n現)서울시립대 세무대학원 교수',
       '경희대 경제학\n메리츠증권 투자금융팀 이사\n하나금융투자 커버리지2실 상무대우\nDB금융투자 FAS1팀 이사\nIBK투자증권 Coverage3팀 이사',
       '서울대 기계공학\nSC제일은행 외환파생상품 이사대우\n미래에셋증권 FICC파생운용팀 수석매니저\nKTB투자증권 Financial Market본부 상무',
       '전남대 경영학\n대신증권 리테일채권 이사대우부장\n대신증권 영업부 이사대우부장\n대신증권 신탁사업부 이사대우부장\n대신증권 목동WM센터 이사대우센터장\n신증권 영업부장',
       '충북대학교 전산학\n대신증권 차세대시스템부 팀장\n대신증권 IT시스템부 팀장\n대신증권 IT지원부장',
       '서울대 법학\n대검찰청 감찰부장(검사장)\n서울북부지방검찰청 검사장\n現)법무법인 (유)동인 변호사',
       '동아대 경영학(박사)\n대신증권 사하지점장\n대신증권 부산센터 이사대우센터장',
       '세종대학교 회계학\n대신증권 광명센터장\n대신증권 대림동지점장\n대신증권 WM추진부 이사대우부장',
       '한국외대 경영학(석사)\n대신증권 CIC사업전략팀장\n대신증권 스마트금융부장\n대신증권 Operation&Technology본부 이사대우부본부장',
       '성균관대학교 경영학\n대신증권 미래전략실장\n대신증권 전략지원실장',
       '조선대 회계학\n대신자산운용 법무본부장\n대신자산운용 리스크관리본부장/준법감시인\n대신에이엠씨 감사\n대신저축은행 준법감시인\n대신증권 법무지원부문장\n대신증권 감사부문장',
       'University of Bath 사회과학대학원(석사)\n서울지방국세청 청장\n現)법무법인 태평양 고문',
       '서강대 경제학\n대신증권 영업기획부장\n대신증권 기획실장\n대신증권 인재전략부 이사대우부장\n대신증권 인재역량센터장\n대신증권 경영지원본부장\n대신증권 준법지원부문장',
       '서울대 행정학(석사)\nBank of America 서울지점 지점장\n메리츠증권 자산운용본부 전무',
       'Florida International University 경영대학원(박사)\n한국회계정보학회 회장\n중앙대 제15대 총장\n現)중앙대 경영경제대 경영학부 교수',
       '경희대 경제학\n대신증권 인사부장\n대신증권 재무관리부장\n대신증권 리스크관리본부 이사대우본부장\n대신저축은행 경영지원본부장\n대신저축은행 대표이사\n대신증권 경영지원총괄, IB사업단장\n대신증권 부사장',
       '전북대 회계학\n대신증권 인수공모2부\n대신증권 비서실장\n대신증권 비서/브랜드본부장\n대신증권 WM사업단장,디지털사업단장',
       '가천대학교 무역학\n대신증권 수지지점장\n대신증권 여의도영업부장\n재경1WM부문장',
       '조선대 회계학\n대신자산운용 법무본부장\n대신자산운용 리스크관리본부장/준법감시인대신에이엠씨 감사\n대신저축은행 준법감시인\n대신증권 법무지원부문장\n대신증권 감사부문장',
       '동국대 경영학(석사)\n대신증권 강남역지점장\n대신증권 강남역삼센터 이사대우센터장대신증권 강남선릉센터 이사대우센터장',
       '서강대 사회학\n대신증권 상품전략부장\n대신증권 상품기획부장\n대신증권 리테일기획부장',
       '건국대 법학(박사)\n국가청렴위원회 사무처장\n제58대 법무부장관\n現)재단법인 행복세상 이사장',
       '전북대 회계학\n대신증권 비서실장\n대신증권 비서/브랜드본부장\n대신증권 WM사업단장,디지털사업단장',
       '원광대 통계학\n대신증권 정보보호부장',
       '경북대 경영학\n대신증권 부동산금융본부장\n대신증권 프로젝트금융본부 이사\n대우본부장',
       '중앙대 응용통계학\n대신증권 IB1본부 팀장\n대신증권 ECM본부 이사대우본부장',
       '중앙대 경영학\n대신증권 인사부장\n대신증권 비서실 이사대우실장',
       '연세대 경영학\n대신증권 소비재그룹장\n대신증권 리서치부장',
       '중앙대 산업정보학\n대신증권 WM개발부장\n대신증권 IT개발부장',
       '경희대 경제학\n대신증권 인사부장\n대신증권 재무관리부장\n대신증권 리스크관리본부 이사대우본부장\n대신저축은행 경영지원본부장\n대신저축은행 대표이사\n대신증권 경영지원총괄, IB사업단장',
       '연세대 경영학(석사)\n대신증권 감사실장\n대신증권 감사부문장',
       '중앙대 무역학\n대신증권 리테일상품팀장\n대신증권 감사실장',
       '인하대 정치외교학\nNH투자증권 부동산금융부장\nKB증권 프로젝트금융부 이사',
       '한국외대 경영학(석사)\n대신증권 스마트금융부장\n대신증권 Operation&Technology본부 이사대우부본부장\n대신증권 디지털부문장',
       '고려대 경영학\n대신증권 리스크관리부장\n대신증권 자산운용본부장\n대신증권 멀티운용본부장\n대신증권 패시브운용본부장',
       '세종대학교 회계학\n대신증권 대림동지점장\n대신증권 WM추진부 이사대우부장\nWM추진부문장',
       '동국대 무역학\n대신증권 경영기획실 이사대우실장',
       '인하대 경제통상학\n대신증권 역량개발부장\n대신증권 Club1962 이사대우센터장',
       '경북대 경영학\n대신증권 포항지점장\n대신증권 동대구지점 이사대우지점장',
       '동아대 경영학(박사)\n대신증권 사하지점장\n대신증권 부산센터 이사대우센터장\n대신증권 영업부장',
       '경북대 경영학\n대신증권 부동산금융본부장\n대신증권 프로젝트금융본부 이사대우본부장',
       '한국외국어대 국제금융학(석사)\n대신증권 이촌동지점장\n대신증권 목동WM센터 이사대우센터장',
       '연세대학교 경영대학원(박사)\nArthur Anderson Consulting 컨설던트\n연세대학교 대학원 경영연구소 연구원\n現)학교법인 광운학원 이사장',
       '고려대 경영학\n대신증권 리스크관리부장\n대신증권 자산운용본부장\n대신증권 멀티운용본부장\n대신증권 패시브운용본부장\n대신증권 고객자산부문 부부문장',
       '한양대 신문방송학\n대신증권 홍보실 이사대우실장',
       '중앙대 산업정보학\n대신증권 WM개발부장\n 대신증권 IT개발부장',
       '미시간대학교 경영대학원 MBA\n국세청 조사국 국장\n제22대 국세청장\n現)법무법인(유) 대륙아주 고문'],
      dtype=object)

In [19]:
#대학, 전공 피처 생성
temp=df['주요경력'].str.split('\n')
colleges=temp.str.get(0)

#추가로 처리해줘야될 대학 form 맞춰주기
colleges[colleges== 'University of Bath 사회과학대학원(석사)'] ='UniversityofBath 사회과학대학원(석사)'
colleges[colleges== 'Florida International University 경영대학원(박사)']='FloridaInternationalUniversity 경영대학원(박사)'
colleges[colleges== 'Ohio State University 정책대학원(박사)'] = 'OhioStateUniversity 정책대학원(박사)'
colleges[colleges== 'KDI국제정책대학원(석사)'] = 'KDI 국제정책대학원(석사)'
colleges[colleges== '상명여자사범대'] = '상명여자사범대 교육학'
colleges[colleges== '한국외국어대경영학(석사)'] = '한국외국어대 경영학(석사)'
colleges[colleges== '미시간대학교 경영대학원 MBA'] = '미시간대학교 경영대학원MBA'

#대학, 전공으로 나누기
ttemp = colleges.str.split() 

#대학 피처 생성
df['대학교']=ttemp.str.get(0)

#전공 피처 생성
tttemp = ttemp.str.get(1)
tttemp=tttemp.replace(r'\([^)]*\)', '', regex=True)
df['전공']=tttemp

In [20]:
df['대학교'].unique()

array(['서울대', '한국과학기술원', '한국외국어대', '전북대', '성균관대', '조지아공대', '고려대', '서강대',
       '연세대', '대전대', '한양대', 'KDI', '상명여자사범대', '울산대', '홍익대', '중앙대', '명지대',
       'Brown대', '전남대', '강원대', '부경대', '영남공업전문대', '경북대', '동국대', '카네기멜론대',
       '경희대', '충북대', '조선대', '세종대', 'UniversityofBath', '가천대학교',
       'OhioStateUniversity', '충북대학교', '동아대', '세종대학교', '한국외대', '성균관대학교',
       'FloridaInternationalUniversity', '건국대', '원광대', '인하대', '연세대학교',
       '미시간대학교'], dtype=object)

In [21]:
df['전공'].unique()

array(['경영학', '화학공학', '법학', '회계학', '불어불문학', '항공우주학', '경제학', '경영대학원',
       '무역학', '정치학', '국제정책대학원', '교육학', '전자계산학', '세무학', '수학', '전자전산학',
       '사법학', '국제경영학', '금융공학', '행정학', '산업정보학', '인적자원개발학', '전산학', 'MBA',
       '사회과학대학원', '정책대학원', '기계공학', '사회학', '통계학', '응용통계학', '정치외교학',
       '경제통상학', '국제금융학', '신문방송학', '경영대학원MBA'], dtype=object)

In [22]:
df['재직기간'].unique()

array(['2012.04.01~2014.12.31', '2011.04.01~2014.12.31',
       '2004.04.01~2014.12.31', '2010.05.28~2014.12.31',
       '2010.04.01~2014.12.31', '2013.04.01~2014.12.31',
       '2014.01.01~2014.12.31', '2013.06.07~2014.12.31',
       '2007.05.02~2014.12.31', '2007.06.22~2014.12.31',
       '2011.05.27~2014.12.31', '2014.01.16~2014.12.31',
       '2009.04.01~2014.12.31', '2004.09.24~2014.12.31',
       '2007.10.01~2014.12.31', '2007.04.01~2014.12.31',
       '2011.04.01~2015.12.31', '2015.03.20~2015.12.31',
       '2013.06.07~2015.12.31', '2014.01.16~2015.12.31',
       '2007.06.22~2015.12.31', '2007.04.01~2015.12.31',
       '2007.10.01~2015.12.31', '2013.04.01~2015.12.31',
       '2014.01.01~2015.12.31', '2004.04.01~2015.12.31',
       '2015.01.01~2015.12.31', '2004.09.24~2015.12.31',
       '2015.03.09~2015.12.31', '2010.04.01~2015.12.31',
       '2012.04.01~2015.12.31', '2011.05.27~2015.12.31',
       '2015.01.01~2016.12.31', '2010.04.01~2016.12.31',
       '2016.01.01~2016.12.31', '2015.03.20~2016.12.31',
       '2016.12.01~2016.12.31', '2016.10.31~2016.12.31',
       '2013.04.01~2016.12.31', '2012.04.01~2016.12.31',
       '2004.09.24~2016.12.31', '2014.01.01~2016.12.31',
       '2004.04.01~2016.12.31', '2011.04.01~2016.12.31',
       '2014.01.16~2016.12.31', '2016.04.01~2016.12.31',
       '2007.06.22~2016.12.31', '2013.06.07~2016.12.31',
       '2007.10.01~2016.12.31', '2015.03.09~2016.12.31',
       '2016.04.18~2016.12.31', '2016.03.18~2016.12.31',
       '2004.09.24~2017.12.31', '2013.04.01~2017.12.31',
       '2015.01.01~2017.12.31', '2016.04.18~2017.12.31',
       '2013.06.07~2017.12.31', '2014.01.01~2017.12.31',
       '2016.12.01~2017.12.31', '2016.01.01~2017.12.31',
       '2010.04.01~2017.12.31', '2016.03.18~2017.12.31',
       '2016.04.01~2017.12.31', '2011.04.01~2017.12.31',
       '2016.10.31~2017.12.31', '2015.03.20~2017.12.31',
       '2015.03.09~2017.12.31', '2012.04.01~2017.12.31',
       '2004.04.01~2017.12.31', '2007.10.01~2017.12.31',
       '2016.12.01~2018.12.31', '2018.01.01~2018.12.31',
       '2016.01.01~2018.12.31', '2015.01.01~2018.12.31',
       '2018.03.23~2018.12.31', '2018.12.03~2018.12.31',
       '2018.08.16~2018.12.31', '2016.04.01~2018.12.31',
       '2004.09.24~2018.12.31', '2011.04.01~2018.12.31',
       '2013.04.01~2018.12.31', '2014.01.01~2018.12.31',
       '2016.03.18~2018.12.31', '2016.10.31~2018.12.31',
       '2007.10.01~2018.12.31', '2004.04.01~2018.12.31',
       '2010.04.01~2018.12.31', '2015.03.20~2018.12.31',
       '2015.01.01~2019.12.31', '2018.08.16~2019.12.31',
       '2018.01.01~2019.12.31', '2019.11.25~2019.12.31',
       '2019.01.01~2019.12.31', '2016.12.01~2019.12.31',
       '2015.03.20~2019.12.31', '2013.04.01~2019.12.31',
       '2014.01.01~2019.12.31', '2011.04.01~2019.12.31',
       '2018.03.23~2019.12.31', '2016.01.01~2019.12.31',
       '2016.03.18~2019.12.31', '2007.10.01~2019.12.31',
       '2004.09.24~2019.12.31', '2004.04.01~2019.12.31',
       '2019.04.01~2019.12.31', '2010.04.01~2019.12.31',
       '2018.12.03~2019.12.31', '2018.03.23~2020.12.31',
       '2018.12.03~2020.12.31', '2016.01.01~2020.12.31',
       '2018.08.16~2020.12.31', '2019.04.01~2020.12.31',
       '2010.04.01~2020.12.31', '2019.11.25~2020.12.31',
       '2013.04.01~2020.12.31', '2014.01.01~2020.12.31',
       '2016.12.01~2020.12.31', '2018.01.01~2020.12.31',
       '2020.11.23~2020.12.31', '2019.01.01~2020.12.31',
       '2020.01.21~2020.12.31', '2004.09.24~2020.12.31',
       '2016.03.18~2020.12.31', '2007.10.01~2020.12.31',
       '2020.03.20~2020.12.31', '2004.09.24~2021.12.31',
       '2007.10.01~2021.12.31', '2020.11.23~2021.12.31',
       '2016.01.01~2021.12.31', '2018.03.23~2021.12.31',
       '2021.11.22~2021.12.31', '2021.03.19~2021.12.31',
       '2018.08.16~2021.12.31', '2021.06.01~2021.12.31',
       '2021.12.27~2021.12.31', '2019.01.01~2021.12.31',
       '2018.01.01~2021.12.31', '2016.12.01~2021.12.31',
       '2019.11.25~2021.12.31', '2020.01.21~2021.12.31',
       '2020.03.20~2021.12.31', '2014.01.01~2021.12.31',
       '2021.03.02~2021.12.31', '2018.12.03~2021.12.31',
       '2019.04.01~2021.12.31', '2010.04.01~2021.12.31',
       '2021.12.27~2022.12.31', '2020.11.23~2022.12.31',
       '2020.01.21~2022.12.31', '2018.01.01~2022.12.31',
       '2018.03.23~2022.12.31', '2016.01.01~2022.12.31',
       '2022.11.21~2022.12.31', '2019.11.25~2022.12.31',
       '2019.04.01~2022.12.31', '2022.03.18~2022.12.31',
       '2010.04.01~2022.12.31', '2021.11.22~2022.12.31',
       '2019.01.01~2022.12.31', '2021.06.01~2022.12.31',
       '2018.12.03~2022.12.31', '2016.12.01~2022.12.31',
       '2022.07.01~2022.12.31', '2004.09.24~2022.12.31',
       '2007.10.01~2022.12.31', '2021.03.19~2022.12.31',
       '2022.06.02~2022.12.31', '2021.11.22~2023.03.31',
       '2022.03.18~2023.03.31', '2007.10.01~2023.03.31',
       '2020.11.23~2023.03.31', '2020.01.21~2023.03.31',
       '2018.01.01~2023.03.31', '2022.11.21~2023.03.31',
       '2021.12.27~2023.03.31', '2010.04.01~2023.03.31',
       '2021.03.19~2023.03.31', '2019.11.25~2023.03.31',
       '2022.07.01~2023.03.31', '2022.06.02~2023.03.31',
       '2023.01.19~2023.03.31', '2019.01.01~2023.03.31',
       '2023.03.24~2023.03.31', '2018.12.03~2023.03.31',
       '2021.06.01~2023.03.31', '2004.09.24~2023.03.31',
       '2019.04.01~2023.03.31', '2016.01.01~2023.03.31'], dtype=object)

In [23]:
#근속연수 생성
def create_work_years(x):
  temp = re.split(r'~|~\n', x)
  temp[0] = temp[0].strip()
  temp[1] = temp[1].strip()
  return int(temp[1][:4]) - int(temp[0][:4])

df['근속연수'] = df['재직기간'].apply(lambda x : create_work_years(x))

In [24]:
df['근속연수'].unique()

array([ 2,  3, 10,  4,  1,  0,  7,  5,  8, 11,  6, 12,  9, 13, 14, 15, 16,
       17, 18, 19])

In [27]:
'''
#주요경력 전처리
def replace_career(x):
  temp = [string.split() for string in re.split(r'\n |\n', x)]
  if len(temp)==1 :
    return temp
  else:
    return set(list(zip(*temp[1:]))[0])

df['주요경력요약'] = df['주요경력'].apply(lambda x : replace_career(x))
'''

#주요경력에 하나만 있어서 안나눠지는거 확인.
#전부 한사람 이어룡씨(대신증권 회장)이어서 집합을 {대신증권으로 바꿈.}
def classify_value(value):
    if isinstance(value, set):
        return False
    elif isinstance(value, list):
        return True
    else:
        return 'Unknown'

temp = df['주요경력요약'].apply(classify_value)
df[temp]

Empty DataFrame
Columns: [이름, 연도, 출생년월, 등기임원 여부, 상근 여부, 담당업무, 주요경력, 의결권 있는 주식수, 재직기간, 임기만료일, 직위, 대학교, 전공, 근속연수, 주요경력요약]
Index: []

In [26]:
#주요경력 전처리
def replace_career(x):
  temp = [string.split() for string in re.split(r'\n |\n', x)]
  if len(temp)==1 :
    return {'대신증권'}
  else:
    return set(list(zip(*temp[1:]))[0])

df['주요경력요약'] = df['주요경력'].apply(lambda x : replace_career(x))

In [28]:
df['주요경력요약'].head(50)

0                                   {대신증권}
1                                   {대신증권}
2              {기업금융사업단장, 기획본부장대신증권, 대신증권}
3                          {법무법인, 대한중재인협회}
4                                   {대신증권}
5                      {대신증권중부지역본부장, 대신증권}
6                                   {대신증권}
7                                   {대신증권}
8                                   {대신증권}
9                   {하비스트, LIG손해보험, 금융감독원}
10                       {대신증권분당지점장, 대신증권}
11                          {우리투자증권, 대신증권}
12                                  {대신증권}
13           {대신증권Capital, 우리CS자산운용, 대신증권}
14                                  {대신증권}
15                 {푸르덴셜투자증권, 메릴린치증권, SBC}
16                                  {대신증권}
17                          {한국투자증권, 부영주택}
18                         {IBK투자증권, 대신증권}
19                      {동양증권, 삼성증권, 대신증권}
20                                  {대신증권}
21                        {대신투자신탁운용, 대신증권}
22                      {대신증권, 대신증권무거동지점장}
23                                  {대신증권}
24                                  {대신증권}
25           {중앙대, 국세청,관세청,산업통상자원부, 기획재정부}
26              {재단법인, 서울지방국세청장, 피앤비세무컨설팅}
27                                  {대신증권}
28        {LG경제연구원, 자본시장연구원, KAIST, 수원대학교}
29                                  {대신증권}
30                                  {대신증권}
31               {학교법인, 변호사정상명법률사무소, 대검찰청}
32           {중앙대, 국세청,관세청,산업통상자원부, 기획재정부}
33                      {한국투자증권평촌지점, 부영주택}
34           {대신증권Capital, 우리CS자산운용, 대신증권}
35                                  {대신증권}
36                    {대신증권, 대신투자신탁운용상무이사}
37                                  {대신증권}
38                     {대신증권중부지역본부장, 대신증권}
39                 {푸르덴셜투자증권, 메릴린치증권, SBC}
40                                  {대신증권}
41                                  {대신증권}
42       {대신증권영업기획부장, 대신증권기획실장, 대신증권인재전략부}
43               {기획본부장대신증권인재역량센터장,, 대신증권}
44                         {굿모닝신한증권, 대신증권}
45    {대우증권전략기획본부, 대우증권해외사업부문, 대우증권IB사업부문}
46                                  {대신증권}
47                                  {대신증권}
48      {한국물산, 우리투자증권기업금융2팀장, 하이투자증권주식인수팀}
49              {대신증권자산운용본부, 대신증권파생상품운용부장}
Name: 주요경력요약, dtype: object

In [29]:
df.head()

,이름,연도,출생년월,등기임원 여부,상근 여부,담당업무,주요경력,의결권 있는 주식수,재직기간,임기만료일,직위,대학교,전공,근속연수,주요경력요약
0,이현식,2014,1962.05,미등기임원,상근,강북지역본부장,서울대 경영학(석사)\n대신증권 시흥동지점장\n대신증권 명일동지점장\n대신증권 퇴직...,4720.0,2012.04.01~2014.12.31,2015.03.20,전무,서울대,경영학,2,{대신증권}
1,조윤남,2014,1968.11,미등기임원,상근,리서치센터장,한국과학기술원 화학공학(석사)\n대신증권 투자전략부장,17401.0,2011.04.01~2014.12.31,2015.03.20,상무,한국과학기술원,화학공학,3,{대신증권}
2,나재철,2014,1960.01,등기임원,상근,업무총괄,한국외국어대 경영학(석사)\n대신증권 강남지역본부장\n대신증권 WM추진본부장\n대신...,23301.0,2004.04.01~2014.12.31,2016.03.31,대표이사,한국외국어대,경영학,10,"{기업금융사업단장, 기획본부장대신증권, 대신증권}"
3,이정훈,2014,1947.06,등기임원,비상근,-,서울대 법학(석사)\n대한중재인협회 회장\n법무법인 태평양 대표변호사(현),0.0,2010.05.28~2014.12.31,2015.03.20,사외이사,서울대,법학,4,"{법무법인, 대한중재인협회}"
4,송혁,2014,1964.04,미등기임원,상근,비서/브랜드담당,전북대 회계학\n대신증권 인수공모2부\n대신증권 비서실장,10391.0,2010.04.01~2014.12.31,2015.03.20,전무,전북대,회계학,4,{대신증권}

# 데이터셋 연도별 분리

In [30]:
df_2014 = df[df['연도']==2014].reset_index(drop=True)
df_2015 = df[df['연도']==2015].reset_index(drop=True)
df_2016 = df[df['연도']==2016].reset_index(drop=True)
df_2017 = df[df['연도']==2017].reset_index(drop=True)
df_2018 = df[df['연도']==2018].reset_index(drop=True)
df_2019 = df[df['연도']==2019].reset_index(drop=True)
df_2020 = df[df['연도']==2020].reset_index(drop=True)
df_2021 = df[df['연도']==2021].reset_index(drop=True)
df_2022 = df[df['연도']==2022].reset_index(drop=True)
df_2023 = df[df['연도']==2023].reset_index(drop=True)

In [31]:
df_2022

,이름,연도,출생년월,등기임원 여부,상근 여부,담당업무,주요경력,의결권 있는 주식수,재직기간,임기만료일,직위,대학교,전공,근속연수,주요경력요약
0,박정환,2022,1975.07,미등기,상근,Trading부문장,서울대 기계공학\nSC제일은행 외환파생상품 이사대우\n미래에셋증권 FICC파생운용팀...,0.0,2021.12.27~2022.12.31,2024.3.31,상무,서울대,기계공학,1,"{KTB투자증권, SC제일은행, 미래에셋증권}"
1,강준규,2022,1972.02,미등기,상근,디지털부문장,가천대학교 무역학\n대신증권 수지지점장\n대신증권 여의도영업부장\n재경1WM부문장,4349.0,2020.11.23~2022.12.31,2024.3.31,상무,가천대학교,무역학,2,"{재경1WM부문장, 대신증권}"
2,최근영,2022,1963.12,미등기,상근,준법감시인\n준법지원부문장,조선대 회계학\n대신자산운용 법무본부장\n대신자산운용 리스크관리본부장/준법감시인대신...,10437.0,2020.01.21~2022.12.31,2023.12.31,상무,조선대,회계학,2,"{대신저축은행, 대신자산운용, 대신증권}"
3,이순남,2022,1969.05,미등기,상근,프라이빗부문장\n나인원프라이빗라운지장,동국대 경영학(석사)\n대신증권 강남역지점장\n대신증권 강남역삼센터 이사대우센터장대...,10953.0,2018.01.01~2022.12.31,2024.3.31,상무,동국대,경영학,4,{대신증권}
4,김병철,2022,1958.09,사외이사,비상근,감사위원장,성균관대 행정학(박사)\n감사원 감사위원\n現)금융위원회 적극행정심의위원,0.0,2018.03.23~2022.12.31,2023.3.31,사외이사,성균관대,행정학,4,"{現)금융위원회, 감사원}"
5,이정화,2022,1968.11,미등기,상근,-,부경대 무역학\n대신증권 마산지점장\n대신증권 부전동지점장\n대신증권 동래지점장,9442.0,2016.01.01~2022.12.31,2023.3.31,전무,부경대,무역학,6,{대신증권}
6,최광철,2022,1973.12,미등기,상근,WM추진부문장,서강대 사회학\n대신증권 상품전략부장\n대신증권 상품기획부장\n대신증권 리테일기획부장,0.0,2022.11.21~2022.12.31,2024.3.31,상무,서강대,사회학,0,{대신증권}
7,이재우,2022,1972.08,미등기,상근,Wholesale부문장,홍익대 경영학\n대신증권 재무관리부장/자금부장\n대신증권 재무자금부장\n대신증권 법...,22924.0,2019.11.25~2022.12.31,2024.3.31,전무,홍익대,경영학,3,{대신증권}
8,길기모,2022,1968.12,미등기,상근,리스크관리부문장,서울대 경제학\n메리츠종금증권 심사팀장\n메리츠종금증권 리스크관리본부장,3532.0,2019.04.01~2022.12.31,2023.3.31,전무,서울대,경제학,3,{메리츠종금증권}
9,김성호,2022,1950.03,사외이사,비상근,감사위원,건국대 법학(박사)\n국가청렴위원회 사무처장\n제58대 법무부장관\n現)재단법인 행...,0.0,2022.03.18~2022.12.31,2024.3.31,사외이사,건국대,법학,0,"{국가청렴위원회, 제58대, 現)재단법인}"
10,송혁,2022,1964.04,미등기,상근,리테일총괄,전북대 회계학\n대신증권 비서실장\n대신증권 비서/브랜드본부장\n대신증권 WM사업단...,29146.0,2010.04.01~2022.12.31,2024.3.31,부사장,전북대,회계학,12,{대신증권}
11,김봉진,2022,1969.07,미등기,상근,영업부장,동아대 경영학(박사)\n대신증권 사하지점장\n대신증권 부산센터 이사대우센터장,73.0,2021.11.22~2022.12.31,2024.3.31,상무보,동아대,경영학,1,{대신증권}
12,정회민,2022,1971.12,미등기,상근,정보보호부문장,원광대 통계학\n대신증권 정보보호부장,3542.0,2022.11.21~2022.12.31,2023.12.31,이사대우부문장,원광대,통계학,0,{대신증권}
13,권택현,2022,1972.02,미등기,상근,PF부문장,경북대 경영학\n대신증권 부동산금융본부장\n대신증권 프로젝트금융본부 이사\n대우본부장,126200.0,2018.01.01~2022.12.31,2024.3.31,전무,경북대,경영학,4,"{대우본부장, 대신증권}"
14,김수창,2022,1968.1,미등기,상근,경영지원부문장,연세대 인적자원개발학(석사)\n대신증권 인재지원부장\n대신증권 인재전략부장\n대신증...,7184.0,2019.11.25~2022.12.31,2024.3.31,상무,연세대,인적자원개발학,3,{대신증권}
15,박석원,2022,1973.02,미등기,상근,기업금융담당,중앙대 응용통계학\n대신증권 IB1본부 팀장\n대신증권 ECM본부 이사대우본부장,2128.0,2022.11.21~2022.12.31,2024.3.31,상무,중앙대,응용통계학,0,{대신증권}
16,김성균,2022,1973.03,미등기,상근,비서실장,중앙대 경영학\n대신증권 인사부장\n대신증권 비서실 이사대우실장,1139.0,2022.11.21~2022.12.31,2024.3.31,상무,중앙대,경영학,0,{대신증권}
17,정연우,2022,1972.08,미등기,상근,Research Center장,연세대 경영학\n대신증권 소비재그룹장\n대신증권 리서치부장,8871.0,2019.01.01~2022.12.31,2024.3.31,전무,연세대,경영학,3,{대신증권}
18,홍종국,2022,1971.06,미등기,상근,IT부문장,중앙대 산업정보학\n대신증권 WM개발부장\n대신증권 IT개발부장,8292.0,2019.11.25~2022.12.31,2024.3.31,상무,중앙대,산업정보학,3,{대신증권}
19,이정훈,2022,1970.01,미등기,상근,Coverage본부장,경희대 경제학\n메리츠증권 투자금융팀 이사\n하나금융투자 커버리지2실 상무대우\nD...,1831.0,2021.06.01~2022.12.31,2024.3.31,상무보,경희대,경제학,1,"{IBK투자증권, 메리츠증권, 하나금융투자, DB금융투자}"
20,오익근,2022,1963.07,사내이사,상근,업무총괄,경희대 경제학\n대신증권 인사부장\n대신증권 재무관리부장\n대신증권 리스크관리본부 ...,73785.0,2018.12.03~2022.12.31,2024.3.31,대표이사,경희대,경제학,4,"{대신저축은행, 대신증권}"
21,김성원,2022,1964.06,미등기,상근,-,연세대 경영학(석사)\n대신증권 감사실장\n대신증권 감사부문장,7644.0,2016.12.01~2022.12.31,2023.3.31,상무,연세대,경영학,6,{대신증권}
22,이성영,2022,1969.06,미등기,상근,감사부문장,중앙대 무역학\n대신증권 리테일상품팀장\n대신증권 감사실장,2793.0,2021.11.22~2022.12.31,2023.12.31,이사대우부문장,중앙대,무역학,1,{대신증권}
23,김상혁,2022,1974.12,미등기,상근,PF1본부장,인하대 정치외교학\nNH투자증권 부동산금융부장\nKB증권 프로젝트금융부 이사,0.0,2022.07.01~2022.12.31,2024.3.31,상무보,인하대,정치외교학,0,"{NH투자증권, KB증권}"
24,김상원,2022,1972.07,미등기,상근,금융소비자보호부문장(COO),한국외대 경영학(석사)\n대신증권 스마트금융부장\n대신증권 Operation&Tec...,9590.0,2018.01.01~2022.12.31,2024.3.31,상무,한국외대,경영학,4,{대신증권}
25,나유석,2022,1974.02,미등기,상근,IPO담당,한국과학기술원 MBA\n대신증권 IB2본부장\n대신증권 IPO본부 이사대우본부장,33662.0,2020.11.23~2022.12.31,2024.3.31,상무,한국과학기술원,MBA,2,{대신증권}
26,이어룡,2022,1953.09,사내이사,상근,-,상명여자사범대,1271697.0,2004.09.24~2022.12.31,2023.3.31,회장,상명여자사범대,교육학,18,{대신증권}
27,양홍석,2022,1981.04,사내이사,상근,-,서울대 경영학\n대신투자신탁운용 상무이사\n대신증권 전무\n대신증권 부사장\n대신증...,5175034.0,2007.10.01~2022.12.31,2024.3.31,부회장,서울대,경영학,15,"{대신투자신탁운용, 대신증권}"
28,최대경,2022,1974.01,미등기,상근,고객자산부문 부부문장,고려대 경영학\n대신증권 리스크관리부장\n대신증권 자산운용본부장\n대신증권 멀티운용...,0.0,2022.11.21~2022.12.31,2024.3.31,상무,고려대,경영학,0,{대신증권}
29,임민수,2022,1971.06,미등기,상근,재경2WM부문장,성균관대 법학\n대신증권 대치동지점장\n대신증권 강남대로센터장\n대신증권 청담WM센터장,6262.0,2019.11.25~2022.12.31,2024.3.31,상무,성균관대,법학,3,{대신증권}
30,정연규,2022,1967.11,미등기,상근,서부WM부문장,전남대 회계학\n대신증권 목포지점장\n대신증권 광주지점장\n대신증권 광주센터장,9817.0,2018.01.01~2022.12.31,2024.3.31,전무,전남대,회계학,4,{대신증권}
31,강윤기,2022,1974.08,미등기,상근,전략지원부문장,성균관대학교 경영학\n대신증권 미래전략실장\n대신증권 전략지원실장,3255.0,2020.11.23~2022.12.31,2024.3.31,상무,성균관대학교,경영학,2,{대신증권}
32,김범철,2022,1963.08,미등기,상근,경영전략총괄,고려대 경영학\n대신증권 기획실장\n대신자산운용 전무\n대신증권 미래전략담당\n대신...,31241.0,2016.01.01~2022.12.31,2024.3.31,부사장,고려대,경영학,6,"{대신에프앤아이, 대신자산운용, 대신증권}"
33,이창세,2022,1962.01,사외이사,비상근,-,서울대 법학\n대검찰청 감찰부장(검사장)\n서울북부지방검찰청 검사장\n現)법무법인 ...,0.0,2018.03.23~2022.12.31,2023.3.31,사외이사,서울대,법학,4,"{대검찰청, 서울북부지방검찰청, 現)법무법인}"
34,신재범,2022,1970.02,미등기,상근,재경1WM부문장,세종대학교 회계학\n대신증권 대림동지점장\n대신증권 WM추진부 이사대우부장\nWM추...,7689.0,2020.11.23~2022.12.31,2024.3.31,상무,세종대학교,회계학,2,"{WM추진부문장, 대신증권}"
35,김창수,2022,1958.08,사외이사,비상근,감사위원,Florida International University 경영대학원(박사)\n한국...,0.0,2021.03.19~2022.12.31,2023.3.31,사외이사,FloridaInternationalUniversity,경영대학원,1,"{중앙대, 한국회계정보학회, 現)중앙대}"
36,송종원,2022,1973.1,미등기,상근,경영기획부문장,동국대 무역학\n대신증권 경영기획실 이사대우실장,3.0,2022.06.02~2022.12.31,2024.3.31,상무,동국대,무역학,0,{대신증권}
37,박성준,2022,1973.02,미등기,상근,IB부문장,홍익대 경영학\n대신증권 금융주치의전략부장\n대신증권 IB솔루션부장\n대신증권 IB...,58693.0,2018.01.01~2022.12.31,2024.3.31,전무,홍익대,경영학,4,{대신증권}
38,김광혁,2022,1973.08,미등기,상근,Club1962센터장,인하대 경제통상학\n대신증권 역량개발부장\n대신증권 Club1962 이사대우센터장,0.0,2022.11.21~2022.12.31,2024.3.31,상무,인하대,경제통상학,0,{대신증권}
39,김경렬,2022,1971.01,미등기,상근,동부WM부문장,경북대 경영학\n대신증권 포항지점장\n대신증권 동대구지점 이사대우지점장,0.0,2022.11.21~2022.12.31,2024.3.31,상무,경북대,경영학,0,{대신증권}
40,원윤희,2022,1957.09,사외이사,비상근,-,Ohio State University 정책대학원(박사)\n한국조세연구원 제9대 원...,0.0,2021.03.19~2022.12.31,2023.3.31,사외이사,OhioStateUniversity,정책대학원,1,"{現)서울시립대, 한국조세연구원, 서울시립대}"
41,김호중,2022,1967.08,미등기,상근,고객자산부문장\n홍보부문장,성균관대 무역학\n대신증권 전략기획실장\n대신증권 기획본부 이사대우부본부장\n대신증...,3524.0,2020.11.23~2022.12.31,2023.3.31,전무,성균관대,무역학,2,"{대신에프앤아이, 대신증권}"

# 가중치 함수

## 대학교

In [33]:
#학교 거리 계산
def cal_college(df1, df2, alpha = 0.7):
  #지역별로 나눔
  college_dict = {'서울경기':['상명여자사범대', '서울대', '홍익대', '성균관대', '연세대', '연세대학교', '동국대', '중앙대', '한국외대', '한국외국어대', '세종대학교', '세종대', '성균관대학교', '경희대', '서강대', '고려대', '건국대', '가천대', '가천대학교', '한양대', '명지대'],
                   '광역시':['부경대', '경북대', '전남대', '조선대', '한국과학기술원', '가천대', '인하대', '동아대', '대전대', '울산대', '영남공업전문대'],
                   '그외한국':['전북대', '원광대', '충북대', '충북대학교', '강원대', 'KDI'],
                   '해외':['FloridaInternationalUniversity', 'OhioStateUniversity', 'UniversityofBath', '조지아공대', 'Brown대', '카네기멜론대', '미시간대학교']}

  #키값 찾기
  for key, val in college_dict.items() :
    if df1['대학교'] in val :
      df1_key = key
    if df2['대학교'] in val :
      df2_key = key
          
  #k값 구하기
  if df1['대학교'] == df2['대학교'] :
    k=0
  elif df1_key == df2_key :
    k=1
  elif df1_key != df2_key :
    k=2

  return alpha ** k

(시별로 나누면 같은 지역이 너무 많고 지역마다 학교도 적어서 일단 아래처럼 나눔) \
1. 경기=>서울통합 \
2. 광역시통합 \
3. 광역시 제외 남은 도? (기타 한국) \
4. 해외

## 학과

In [34]:
df['전공'].unique()

array(['경영학', '화학공학', '법학', '회계학', '불어불문학', '항공우주학', '경제학', '경영대학원',
       '무역학', '정치학', '국제정책대학원', '교육학', '전자계산학', '세무학', '수학', '전자전산학',
       '사법학', '국제경영학', '금융공학', '행정학', '산업정보학', '인적자원개발학', '전산학', 'MBA',
       '사회과학대학원', '정책대학원', '기계공학', '사회학', '통계학', '응용통계학', '정치외교학',
       '경제통상학', '국제금융학', '신문방송학', '경영대학원MBA'], dtype=object)

In [35]:
#학과 거리 계산
def cal_department(df1, df2, alpha = 0.7):
  department_dict={'경영경제':['회계학', '세무학', '경제학', '국제경영학', '경영학', '무역학', 'MBA', '경제통상학', '경영대학원', '경영대학원MBA', '산업정보학', '금융공학', '국제금융학'],
                   '사회과학':['사회학', '사회과학대학원', '행정학', '정치외교학', '정치학', '신문방송학'],
                   '법률':['법학', '사법학', '정책대학원', '국제정책대학원'],
                   '인문':['불어불문학'],
                   '기타':['교육학', '인적자원개발학'],
                   '자연':['응용통계학', '통계학', '수학'],
                   '공학':['기계공학', '화학공학', '전자계산학', '전자전산학', '전산학', '항공우주학']}

  #키값 찾기
  for key, val in department_dict.items() :
    if df1['전공'] in val :
      df1_key = key
    if df2['전공'] in val :
      df2_key = key
          
  #k값 구하기
  if df1['전공'] == df2['전공'] :
    k=0
  elif df1_key == df2_key :
    k=1
  elif df1_key != df2_key :
    k=2

  return alpha ** k

## 직위

In [36]:
df['직위'].unique()

array(['전무', '상무', '대표이사', '사외이사', '상무보', '감사위원', '회장', '사장', '부사장',
       '이사대우담당', '이사대우부문장', '부회장'], dtype=object)

In [37]:
#직위 거리 계산
def cal_position(df1, df2, alpha = 0.7):
  position_dict={'회장':0, '대표이사':1, '부회장':2, '사장':3, '부사장':4, '전무':5, '상무': 6, '상무보':7, '이사대우부문장':8, '이사대우담당':8, '사외이사':99, '감사위원':99}

  #value값 찾기
  df1_value = position_dict[df1['직위']]
  df2_value = position_dict[df2['직위']]

  #k값 구하기
  if df1['직위'] == df2['직위'] :
    k=0
  elif df1_value == 99 or df2_value == 99 : #사외이사 혹은 감사인원(회사밖 인물)은 모두와 거리 4(최대차이의 중간값// 회장, 이사대우담당과의 거리)
    k=4
  else :
    k=abs(df1_value - df2_value) #값 차이만큼 거리

  return alpha ** k

대신증권 계급도 못찾겠음..

## 근속연수

In [38]:
# 근속연수 거리 계산
def cal_work_years(df1, df2, alpha = 0.7):
  #k값 구하기
  if df1['근속연수'] == df2['근속연수'] :
    k=0
  else :
    if abs(df1['근속연수'] - df2['근속연수']) % 5 ==0:    #근속연수 차이 5년 기준으로 1씩 증가 (차이 1~5/6~10/11~15/...같은그룹)
      k= abs(df1['근속연수'] - df2['근속연수']) // 5 
    else:
      k= 1 + abs(df1['근속연수'] - df2['근속연수']) // 5 

  return alpha ** k

## 담당업무

In [39]:
df['담당업무'].unique()

array(['강북지역본부장', '리서치센터장', '업무총괄', '-', '비서/브랜드담당', '강남지역본부장',
       'Trading Center장', '서부지역본부장', '인재역량센터장', '동부지역본부장',
       'Wholesale사업단장', '영업부장', '고객자산본부장', '인프라관리본부장', '상근감사위원',
       '금융주치의사업단장', '스마트금융본부장', 'IB사업단장', '금융주치의추진본부장',
       '업무총괄(IB사업단, 고객자산본부 제외)', '울산지점장', '기획본부장', 'IT서비스본부장', '감사위원',
       '구조화상품본부장', '감사위원장', 'IB부문장', '정보보호담당', '감사담당', 'IB부부문장',
       'Wholesale영업본부장', 'Operation&Technology본부장',
       'Research&Strategy본부장', '리스크관리담당', '경영지원본부장', 'IB1부문장',
       'Market\n  Solution부문장', '기획본부장 / 투자금융담당', '준법감시인 / 준법지원담당',
       'Product부문장', '업무총괄(IB사업단,고객자산본부 제외)', 'IB2부문장', '고객자산본부장 / 홍보담당',
       'Advisory본부장', 'Solution&Product사업단장', '비서/브랜드본부',
       'Market Solution부문장', '강남선릉센터장', '스마트Biz본부장', '전략지원담당',
       '준법감시인\n준법지원담당', '고객자산본부장/ 홍보담당', 'PF부문장',
       '업무총괄 (IB사업단,고객자산본부 제외)', 'IT본부장', '경영기획본부장', 'WM사업단장', '경영전략총괄',
       '전략지원부문장/프라이빗라운지 부문장', 'Market Solution 부문장', 'Research Center장',
       '정보보호부문장', '고객자산본부장/ 홍보부문장',
       '업무총괄(IB사업단, 고객자산본부, 경영지원본부, 정보보호부문, 준법지원부문, 감사부문 제외)', '감사부문장',
       '준법감시인/준법지원부문장', '리스크관리부문장', '대신나인원 \n프라이빗라운지장', '동부WM본부장',
       'Wholesale부문장', '대외협력담당', '금융소비자보호 총괄',
       '프라이빗라운지 부문장 /대신나인원 프라이빗라운지장', '전략지원부문장', '서부WM본부장',
       '고객자산본부장/홍보부문장', '재경2WM본부장', 'IPO담당', 'WM추진본부장', '재경1WM본부장',
       'Trading부문장', '재경1WM부문장', '경영기획부문장', 'Coverage본부장', '서부WM부문장',
       '프라이빗부문장, 대신나인원프라이빗라운지장', '동부WM부문장', '금융소비자보호총괄', 'WM추진부문장',
       '디지털부문장', '재경2WM부문장', '준법감시인\n준법지원부문장', 'Sales&Trading총괄',
       '고객자산부문장, 홍보부문장', '경영지원부문장', 'IT부문장', '리테일총괄',
       '프라이빗부문장\n나인원프라이빗라운지장', '기업금융담당', '비서실장', 'PF1본부장',
       '금융소비자보호부문장(COO)', '고객자산부문 부부문장', 'Club1962센터장', '고객자산부문장\n홍보부문장',
       '준법감시인 준법지원부문장', '프라이빗부문장, 나인원프라이빗라운지장', '고객자산부문장', '홍보부문장',
       '금융소비자보호부문장 (COO)'], dtype=object)

In [111]:
#담당업무 거리 계산
def cal_task(df1, df2, alpha = 0.7):
  task_dict={'IT계열': {'IT':['IT부문장', 'IT본부장', 'IT서비스본부장', '디지털부문장', '스마트Biz본부장', 'Operation&Technology본부장'], '정보보호':['정보보호부문장', '정보보호담당']},
             '본사영업':{'Wolesale':['Wholesale부문장','Wholesale영업본부장', 'Wholesale사업단장', 'Trading부문장', 'Trading Center장', 'Sales&Trading총괄', '대외협력담당'], 
                     'IB':['IB사업단장', 'IB부문장', 'IB부부문장', 'IB1부문장', 'IB2부문장', 'IPO담당',  'PF부문장', 'PF1본부장', '구조화상품본부장'], 
                     '영업':['영업부장']},
             '본사관리':{'리테일':['리테일총괄', 'Club1962센터장','WM추진부문장', 'WM추진본부장', 'WM사업단장'],
                     '리스크':['리스크관리부문장', '리스크관리담당'] ,
                     '경영':['경영전략총괄', '전략지원부문장', '전략지원담당', '경영지원본부장', '경영지원부문장', '경영기획부문장', '경영기획본부장', '기획본부장', '기획본부장 / 투자금융담당', '전략지원부문장/프라이빗라운지 부문장'], 
                     '상품':['Product부문장', 'Solution&Product사업단장'],
                     '업무':['업무총괄',  '업무총괄(IB사업단, 고객자산본부 제외)', '업무총괄(IB사업단,고객자산본부 제외)', '업무총괄 (IB사업단,고객자산본부 제외)', '업무총괄(IB사업단, 고객자산본부, 경영지원본부, 정보보호부문, 준법지원부문, 감사부문 제외)'], 
                     '금융':['기업금융담당', '스마트금융본부장', '금융주치의추진본부장', '금융주치의사업단장'], 
                     '인사,인프라':['인재역량센터장', '인프라관리본부장'],
                     '법률':['준법감시인\n 준법지원부문장', '준법감시인 준법지원부문장', '준법감시인\n준법지원부문장', '준법감시인\n준법지원담당', '준법감시인/준법지원부문장', '준법감시인 / 준법지원담당', 'Advisory본부장'], 
                     '감사':['감사위원장', '감사부문장', '감사위원', '상근감사위원', '감사담당'], 
                     '언론홍보':['홍보부문장', 'Coverage본부장']},
             '리서치': {'리서치센터':['Research Center장', '리서치센터장', 'Market\n  Solution부문장', 'Research&Strategy본부장', 'Market Solution부문장', 'Market Solution 부문장']},
             '고객':{'고객자산':['고객자산부문장', '고객자산부문 부부문장', '고객자산본부장', '고객자산본부장 / 홍보담당', '고객자산본부장/ 홍보담당', '고객자산본부장/ 홍보부문장', '고객자산본부장/홍보부문장', '고객자산부문장, 홍보부문장', '고객자산부문장\n홍보부문장'],
                   'WM':['서부WM부문장', '서부WM본부장', '재경1WM부문장', '재경1WM본부장', '재경2WM본부장', '재경2WM부문장', '동부WM부문장', '동부WM본부장'],
                   '프라이빗':['프라이빗부문장,\n 나인원프라이빗라운지장', '프라이빗부문장, 나인원프라이빗라운지장', '대신나인원 \n프라이빗라운지장', '프라이빗라운지 부문장 /대신나인원 프라이빗라운지장', '프라이빗부문장, 대신나인원프라이빗라운지장', '프라이빗부문장\n나인원프라이빗라운지장',], 
                   '소비자보호':['금융소비자보호부문장\n(COO)', '금융소비자보호부문장(COO)', '금융소비자보호부문장 (COO)', '금융소비자보호 총괄', '금융소비자보호총괄']},
             '기타':{'지점':['강북지역본부장', '강남지역본부장', '강남선릉센터장', '서부지역본부장', '동부지역본부장', '울산지점장'],
                   '비서':['비서실장', '비서/브랜드본부', '비서/브랜드담당'], '공란':['-']}}

   #키값 찾기
  for outerKey in task_dict.keys() :
    for key, val in task_dict[outerKey].items() :
      if df1['담당업무'] in val :
        df1_outerKey = outerKey
        df1_innerKey = key
      if df2['담당업무'] in val :
        df2_outerKey = outerKey
        df2_innerKey = key
          
          
  #k값 구하기
  if df1['담당업무'] == df2['담당업무'] : #같은업무
    k=0
  elif df1_outerKey == df2_outerKey and df1_innerKey == df2_innerKey: #상위하위 혹은 비슷한업무
    k=1
  elif df1_outerKey == df2_outerKey : #같은계열업무
    k=2
  elif df1_outerKey != df2_outerKey :
    k=3 #다른계열업무
  return alpha ** k

http://money2.daishin.co.kr/company/recruit/job_introduce.shtml

http://www.educe.co.kr/company/jobinfo_view.php?sma_no=60&keyword=&search_txt2=

겸직은 그냥 앞에꺼에 넣음(대체적으로 앞에꺼가 좀 더 중요한 업무 같아서)

## 주요경력

In [202]:
#경력 거리 계산
def cal_career(df1, df2, alpha = 0.7):
  career_dict={1:['대신증권', '대신증권WM사업단장', 'WM추진부문장', '재경1WM부문장', '대신증권중부지역본부장', '기획본부장대신증권', '대신증권분당지점장', '대신증권무거동지점장', '대신증권Capital', 
                  '이사대우부본부장', '기획본부장대신증권인재역량센터장', '대신증권인재전략부', '대신증권파생상품운용부장', '대신증권자산운용본부', '대신증권영업기획부장', '대신증권기획실장', 
                  '대신증권홍보실', '대신증권브랜드전략실', '대신증권IT개발부장', '대신증권트레이딩시스템부장', '대신증권Global사업본부', '신증권', '기업금융사업단장'], #대신증권
               0:['대신에프앤아이', '대신투자신탁운용', '대신투자신탁운용상무이사', '대신에이엠씨', '대신자산운용', '대신저축은행'], #대신증권 자회사
               2:['메리츠종금증권', '메리츠증권', '미래에셋증권', 'KTB투자증권', 'SC제일은행', '하나금융투자', 'IBK투자증권', 'DB금융투자', 'NH투자증권', 'KB증권', 'LIG손해보험', '굿모닝신한증권', '메릴린치증권', 
                  '삼성증권', '동양증권', '한국투자증권', '한국투자증권평촌지점', '대우증권', '대우본부장', '대우증권전략기획본부', '대우증권해외사업부문', '대우증권IB사업부문', 
                  '우리투자증권', '우리CS자산운용', '우리투자증권기업금융2팀장', '우리프라이빗에쿼티', '푸르덴셜투자증권', '하이투자증권주식인수팀',  '하이투자증권주식인수팀', 'SBC', 'Bank', '도이치은행'], #타증권사
               3:['금융감독원', '금융위원회', '現)금융위원회', '감사원', '대검찰청', '법무법인', '現)법무법인', '세무법인', '국세청', '중부지방국세청', '서울북부지방검찰청','서울지방국세청장', '서울지방국세청', 
                  '제58대', '제22대', '기획재정부', '국세청,관세청,산업통상자원부', '자본시장연구원', '한국조세연구원', '국가청렴위원회', '대한중재인협회', '한국회계정보학회', 
                  '금융위원회금융발전심의위원(현)', '금융위원회적극행정심의위원(現)', '안진회계법인',  'L&C세무회계사무소', '변호사정상명법률사무소', '피앤비세무컨설팅', '現)법무법인(유)'], #법,정책
               4:['중앙대', '중앙대학교', '現)중앙대', '연세대학교', 'KAIST', '수원대', '수원대학교', '서울시립대', '現)서울시립대', '학교법인', '現)학교법인', '재단법인', '現)재단법인'], #학교, 교수, 재단
               5:['하비스트', '한국물산', '우리선물', '부영주택', 'LG경제연구원', 'Arthur'] #기타
               }
  
  #경력 여부 빈리스트 생성
  df1_list = [0,0,0,0,0,0] #0번인덱스: 대신증권, 1번인덱스: 대신증권 자회사, 2번인덱스: 타증권사, 3번인덱스: 기타
  df2_list = [0,0,0,0,0,0]

  #리스트에 각 업종에 종사했었으면 1, 아니면 0
  for career in df1['주요경력요약'] :
    for key, val in career_dict.items() :
      if career in val :
        df1_list[key]=1

  for career in df2['주요경력요약'] :
    for key, val in career_dict.items() :
      if career in val :
        df2_list[key]=1

  #df1_list 와 df2_list 합 구하기(요소가 0-> 둘다 종사 안했음, 1-> 한쪽만 종사함, 2-> 둘다 종사함)
  sum_list = [x + y for x, y in zip(df1_list, df2_list)]

  #k값 구하기
  if df1_list == df2_list : #전체 같으면 0
    k=0

  elif (sum_list[0]==0 and sum_list[1]==0 and sum_list[2]==0): #기타만 있을 때 (법률, 학교, 기타) 
    count2 = sum_list.count(2) #2인 요소 개수 찾기(df1, df2 같은거 개수)
    k = 0.6 * (1 + count2) 

  else : #기타만 있는거 아니고, 
    #법률, 학교, 기타 전부 기타로 통합. 범주는 3으로.
    if sum(df1_list[3:]) > 0 :
      df1_list[3] = 1
      df1_list[4] = 0
      df1_list[5] = 0
    if sum(df2_list[3:]) > 0 :
      df2_list[3] = 1
      df2_list[4] = 0
      df2_list[5] = 0

    #수정한 df1_list, df2_list로 sum_list 다시 생성
    sum_list = [x + y for x, y in zip(df1_list, df2_list)]

    #df1_list, df2_list에서 1인 인덱스 뽑기
    index1 = [i for i in range(len(df1_list)) if df1_list[i] == 1]
    index2 = [i for i in range(len(df2_list)) if df2_list[i] == 1]

    min = 10
    max = 0

    for i in index1 :
      for j in index2 :
        if i != j: #두 사람 간에, 다른 업종끼리 최대거리 최소 거리 구하기

          if (i==3 and j != 3) or (j==3 and i != 3) : #기타와 다른 업종
            max = 4 #기타는 모두와 거리 4 고정 (최대거리 구하기)
            temp = 4
          else : #최대거리 구하기
            temp = abs(i-j)
            if temp > max:
              max = temp
          if temp < min: #최소거리 구하기
            min = temp
    
    k=float((max+min)/2) #거리는 최대거리, 최소거리의 평균
    k= k- (0.5 * sum_list.count(2)) # 같은 업종 있으면, 있는 만큼 거리 -0.5
  
  return alpha ** k

0. 대신증권
1. 대신증권 자회사
2. 타증권사
3. 법, 정책
4. 학교, 교수, 재단
5. 기타 다른분야

## 주식수

In [126]:
#보유 주식수별 거리 계산
def cal_stock(df1, df2, alpha = 0.7):
  #k값 구하기
  if df1['의결권 있는 주식수'] == df2['의결권 있는 주식수'] :
    k=0
  else :
    k= abs(df1['의결권 있는 주식수'] - df2['의결권 있는 주식수'])//100 #차이로 보기=> 차이가 거리가 됨(너무 차이 크면 거리 멀어짐), 100개 단위로 끊어서 보기
    k=math.log10(1+k) #로그스케일
  return alpha ** k

## 가중치함수 통합

In [206]:
#가중치 함수
def weight_sum(df1, df2):
  wt_college = cal_college(df1, df2)
  wt_department = cal_department(df1, df2)
  wt_position = cal_position(df1, df2)
  wt_task = cal_task(df1, df2)
  wt_work_years = cal_work_years(df1, df2)
  wt_career = cal_career(df1, df2)
  wt_stock = cal_stock(df1, df2)
  return wt_college + wt_department + wt_position + wt_task + wt_work_years + wt_career + wt_stock

## 기타 테스트

In [207]:
cal_college(df_2021.iloc[1], df_2021.iloc[2])

0.7

In [208]:
cal_department(df_2021.iloc[1], df_2021.iloc[2])

0.7

In [209]:
cal_position(df_2022.iloc[1], df_2022.iloc[2])

1.0

In [210]:
cal_work_years(df_2022.iloc[0], df_2022.iloc[3])

0.7

In [211]:
cal_task(df_2022.iloc[33], df_2022.iloc[35])

0.3429999999999999

In [212]:
pd.set_option('display.max_rows', None)
print(df['주요경력요약'])

0                                        {대신증권}
1                                        {대신증권}
2                   {기업금융사업단장, 기획본부장대신증권, 대신증권}
3                               {법무법인, 대한중재인협회}
4                                        {대신증권}
5                           {대신증권중부지역본부장, 대신증권}
6                                        {대신증권}
7                                        {대신증권}
8                                        {대신증권}
9                        {하비스트, LIG손해보험, 금융감독원}
10                            {대신증권분당지점장, 대신증권}
11                               {우리투자증권, 대신증권}
12                                       {대신증권}
13                {대신증권Capital, 우리CS자산운용, 대신증권}
14                                       {대신증권}
15                      {푸르덴셜투자증권, 메릴린치증권, SBC}
16                                       {대신증권}
17                               {한국투자증권, 부영주택}
18                              {IBK투자증권, 대신증권}
19                           {동양증권, 삼성증권, 대신증권}
20                                       {대신증권}
21                             {대신투자신탁운용, 대신증권}
22                           {대신증권, 대신증권무거동지점장}
23                                       {대신증권}
24                                       {대신증권}
25                {중앙대, 국세청,관세청,산업통상자원부, 기획재정부}
26                   {재단법인, 서울지방국세청장, 피앤비세무컨설팅}
27                                       {대신증권}
28             {LG경제연구원, 자본시장연구원, KAIST, 수원대학교}
29                                       {대신증권}
30                                       {대신증권}
31                    {학교법인, 변호사정상명법률사무소, 대검찰청}
32                {중앙대, 국세청,관세청,산업통상자원부, 기획재정부}
33                           {한국투자증권평촌지점, 부영주택}
34                {대신증권Capital, 우리CS자산운용, 대신증권}
35                                       {대신증권}
36                         {대신증권, 대신투자신탁운용상무이사}
37                                       {대신증권}
38                          {대신증권중부지역본부장, 대신증권}
39                      {푸르덴셜투자증권, 메릴린치증권, SBC}
40                                       {대신증권}
41                                       {대신증권}
42            {대신증권영업기획부장, 대신증권기획실장, 대신증권인재전략부}
43                    {기획본부장대신증권인재역량센터장,, 대신증권}
44                              {굿모닝신한증권, 대신증권}
45         {대우증권전략기획본부, 대우증권해외사업부문, 대우증권IB사업부문}
46                                       {대신증권}
47                                       {대신증권}
48           {한국물산, 우리투자증권기업금융2팀장, 하이투자증권주식인수팀}
49                   {대신증권자산운용본부, 대신증권파생상품운용부장}
50                         {국세청, 중부지방국세청, 세무법인}
51                                       {대신증권}
52                                       {대신증권}
53                     {우리투자증권, 대신증권Global사업본부}
54                                       {대신증권}
55                           {동양증권, 삼성증권, 대신증권}
56                                       {대신증권}
57                       {하비스트, LIG손해보험, 금융감독원}
58                        {대신증권홍보실, 대신증권브랜드전략실}
59               {LG경제연구원, 자본시장연구원, 수원대, KAIST}
60                  {대신증권트레이딩시스템부장, 대신증권IT개발부장}
61                  {대신증권트레이딩시스템부장, 대신증권IT개발부장}
62                                       {대신증권}
63                                       {대신증권}
64               {우리투자증권, 대신증권Global사업본부, 대신증권}
65                         {국세청, 중부지방국세청, 세무법인}
66                                       {대신증권}
67                               {대신저축은행, 대신증권}
68                                       {대신증권}
69                           {동양증권, 삼성증권, 대신증권}
70                                       {대신증권}
71                                       {대신증권}
72      {대신증권영업기획부장, 대신증권기획실장, 대신증권, 대신증권인재전략부}
73                    {기획본부장대신증권인재역량센터장,, 대신증권}
74                                       {대신증권}
75                                       {대신증권}
76                                 {우리선물, 대신증권}
77             {한국투자증권평촌지점, 한국투자증권, 부영주택, 대신증권}
78         {대우증권전략기획본부, 대우증권해외사업부문, 대우증권IB사업부문}
79                {푸르덴셜투자증권, 메릴린치증권, SBC, 대신증권}
80                      {대신에프앤아이, 대신자산운용, 대신증권}
81                               {대신자산운용, 대신증권}
82             {대신증권자산운용본부, 대신증권파생상품운용부장, 대신증권}
83                {대신증권Capital, 우리CS자산운용, 대신증권}
84                    {학교법인, 변호사정상명법률사무소, 대검찰청}
85                       {하비스트, LIG손해보험, 금융감독원}
86                                       {대신증권}
87                             {대신투자신탁운용, 대신증권}
88                                       {대신증권}
89     {한국물산, 대신증권, 우리투자증권기업금융2팀장, 하이투자증권주식인수팀}
90                  {대신증권홍보실, 대신증권, 대신증권브랜드전략실}
91              {중앙대학교, 국세청,관세청,산업통상자원부, 기획재정부}
92                          {대신증권중부지역본부장, 대신증권}
93                           {우리프라이빗에쿼티, 도이치은행}
94                         {안진회계법인, L&C세무회계사무소}
95                                       {대신증권}
96                                       {대신증권}
97                                       {대신증권}
98               {우리투자증권, 대신증권Global사업본부, 대신증권}
99               {대신증권, 우리프라이빗에쿼티, 대우증권, 도이치은행}
100        {대우증권전략기획본부, 대우증권해외사업부문, 대우증권IB사업부문}
101             {중앙대학교, 국세청,관세청,산업통상자원부, 기획재정부}
102                 {대신증권홍보실, 대신증권, 대신증권브랜드전략실}
103                                      {대신증권}
104                                      {대신증권}
105                     {대신에프앤아이, 대신자산운용, 대신증권}
106                                      {대신증권}
107                        {안진회계법인, L&C세무회계사무소}
108                              {대신자산운용, 대신증권}
109                                      {대신증권}
110                                      {대신증권}
111                         {대신증권중부지역본부장, 대신증권}
112                              {대신저축은행, 대신증권}
113                   {학교법인, 변호사정상명법률사무소, 대검찰청}
114            {대신증권자산운용본부, 대신증권파생상품운용부장, 대신증권}
115                                      {대신증권}
116                                {우리선물, 대신증권}
117                                      {대신증권}
118     {대신증권영업기획부장, 대신증권기획실장, 대신증권, 대신증권인재전략부}
119                 {대신증권트레이딩시스템부장, 대신증권IT개발부장}
120                                      {대신증권}
121                      {하비스트, LIG손해보험, 금융감독원}
122                                      {대신증권}
123                        {국세청, 중부지방국세청, 세무법인}
124    {한국물산, 대신증권, 우리투자증권기업금융2팀장, 하이투자증권주식인수팀}
125                          {동양증권, 삼성증권, 대신증권}
126                                      {대신증권}
127                            {대신투자신탁운용, 대신증권}
128                                      {대신증권}
129                                      {대신증권}
130                                {우리선물, 대신증권}
131              {우리투자증권, 대신증권Global사업본부, 대신증권}
132                                {금융위원회, 감사원}
133                                      {대신증권}
134                                      {대신증권}
135                                      {대신증권}
136                              {대신저축은행, 대신증권}
137                             {대신에프앤아이, 대신증권}
138                              {대신자산운용, 대신증권}
139                                      {대신증권}
140                                      {대신증권}
141                                      {대신증권}
142                     {법무법인, 대검찰청, 서울북부지방검찰청}
143                 {대신증권홍보실, 대신증권, 대신증권브랜드전략실}
144                                      {대신증권}
145                                      {대신증권}
146     {대신증권영업기획부장, 대신증권기획실장, 대신증권, 대신증권인재전략부}
147                                      {대신증권}
148                        {안진회계법인, L&C세무회계사무소}
149                              {대신저축은행, 대신증권}
150                            {대신투자신탁운용, 대신증권}
151           {대신증권트레이딩시스템부장, 대신증권IT개발부장, 대신증권}
152            {대신증권자산운용본부, 대신증권파생상품운용부장, 대신증권}
153                                      {대신증권}
154                             {대신에프앤아이, 대신증권}
155                                      {대신증권}
156                                      {대신증권}
157                                      {대신증권}
158                     {대신에프앤아이, 대신자산운용, 대신증권}
159                        {국세청, 중부지방국세청, 세무법인}
160                                      {대신증권}
161           {대신증권트레이딩시스템부장, 대신증권IT개발부장, 대신증권}
162                             {대신에프앤아이, 대신증권}
163                                      {대신증권}
164                                      {대신증권}
165                                      {대신증권}
166                                      {대신증권}
167                       {우리선물, 대신증권, 이사대우부문장}
168                        {국세청, 중부지방국세청, 세무법인}
169                                      {대신증권}
170                                      {대신증권}
171                 {대신증권홍보실, 대신증권, 대신증권브랜드전략실}
172                                      {대신증권}
173                     {감사원, 금융위원회금융발전심의위원(현)}
174                                      {대신증권}
175                                      {대신증권}
176            {대신증권자산운용본부, 대신증권파생상품운용부장, 대신증권}
177                                      {대신증권}
178                        {안진회계법인, L&C세무회계사무소}
179                                      {대신증권}
180                                      {대신증권}
181                                      {대신증권}
182                     {대신에프앤아이, 대신자산운용, 대신증권}
183                            {대신투자신탁운용, 대신증권}
184                                      {대신증권}
185                                      {대신증권}
186                                      {대신증권}
187                     {법무법인, 대검찰청, 서울북부지방검찰청}
188     {대신증권영업기획부장, 대신증권기획실장, 대신증권, 대신증권인재전략부}
189                                   {메리츠종금증권}
190                                      {대신증권}
191                                      {대신증권}
192                                      {대신증권}
193                                      {대신증권}
194                                      {대신증권}
195                            {이사대우부본부장, 대신증권}
196                      {대신저축은행, 대신자산운용, 대신증권}
197                              {대신저축은행, 대신증권}
198                     {금융위원회적극행정심의위원(現), 감사원}
199                              {대신저축은행, 대신증권}
200                                      {대신증권}
201                             {대신에프앤아이, 대신증권}
202                                   {메리츠종금증권}
203                                      {대신증권}
204                                      {대신증권}
205                                      {대신증권}
206                          {대신증권, 대신증권WM사업단장}
207                 {대신증권홍보실, 대신증권, 대신증권브랜드전략실}
208                                      {대신증권}
209                                      {대신증권}
210                                      {대신증권}
211                                      {대신증권}
212                     {대신에프앤아이, 대신자산운용, 대신증권}
213                                      {대신증권}
214                             {대신에프앤아이, 대신증권}
215                                      {대신증권}
216                                      {대신증권}
217              {대신에이엠씨, 대신저축은행, 대신자산운용, 대신증권}
218                                      {대신증권}
219                                      {대신증권}
220                                      {대신증권}
221                     {법무법인, 대검찰청, 서울북부지방검찰청}
222                                      {대신증권}
223              {대신에이엠씨, 대신저축은행, 대신자산운용, 대신증권}
224                                      {대신증권}
225                                      {대신증권}
226     {대신증권영업기획부장, 대신증권기획실장, 대신증권, 대신증권인재전략부}
227                                      {대신증권}
228                        {안진회계법인, L&C세무회계사무소}
229                                      {대신증권}
230                            {대신투자신탁운용, 대신증권}
231                             {법무법인, 서울지방국세청}
232                                      {대신증권}
233                                      {대신증권}
234                                      {대신증권}
235                            {대신투자신탁운용, 대신증권}
236                                      {대신증권}
237                     {대신에프앤아이, 대신자산운용, 대신증권}
238                              {現)금융위원회, 감사원}
239                                      {대신증권}
240                   {現)서울시립대, 한국조세연구원, 서울시립대}
241                             {대신에프앤아이, 대신증권}
242            {IBK투자증권, 메리츠증권, 하나금융투자, DB금융투자}
243                   {KTB투자증권, SC제일은행, 미래에셋증권}
244                                 {신증권, 대신증권}
245                                      {대신증권}
246                                      {대신증권}
247                                      {대신증권}
248                                      {대신증권}
249                   {대검찰청, 서울북부지방검찰청, 現)법무법인}
250                                      {대신증권}
251                                      {대신증권}
252                                      {대신증권}
253                                      {대신증권}
254                                      {대신증권}
255                                      {대신증권}
256                                      {대신증권}
257                                      {대신증권}
258              {대신에이엠씨, 대신저축은행, 대신자산운용, 대신증권}
259                           {서울지방국세청, 現)법무법인}
260                                      {대신증권}
261                               {메리츠증권, Bank}
262                             {대신에프앤아이, 대신증권}
263                      {중앙대, 한국회계정보학회, 現)중앙대}
264                                      {대신증권}
265                              {대신저축은행, 대신증권}
266                                      {대신증권}
267                                   {메리츠종금증권}
268                                      {대신증권}
269                                      {대신증권}
270                                      {대신증권}
271                                      {대신증권}
272                   {KTB투자증권, SC제일은행, 미래에셋증권}
273                            {재경1WM부문장, 대신증권}
274                      {대신저축은행, 대신자산운용, 대신증권}
275                                      {대신증권}
276                              {現)금융위원회, 감사원}
277                                      {대신증권}
278                                      {대신증권}
279                                      {대신증권}
280                                   {메리츠종금증권}
281                     {국가청렴위원회, 제58대, 現)재단법인}
282                                      {대신증권}
283                                      {대신증권}
284                                      {대신증권}
285                               {대우본부장, 대신증권}
286                                      {대신증권}
287                                      {대신증권}
288                                      {대신증권}
289                                      {대신증권}
290                                      {대신증권}
291            {IBK투자증권, 메리츠증권, 하나금융투자, DB금융투자}
292                              {대신저축은행, 대신증권}
293                                      {대신증권}
294                                      {대신증권}
295                              {NH투자증권, KB증권}
296                                      {대신증권}
297                                      {대신증권}
298                                      {대신증권}
299                            {대신투자신탁운용, 대신증권}
300                                      {대신증권}
301                                      {대신증권}
302                                      {대신증권}
303                                      {대신증권}
304                     {대신에프앤아이, 대신자산운용, 대신증권}
305                   {대검찰청, 서울북부지방검찰청, 現)법무법인}
306                             {WM추진부문장, 대신증권}
307                      {중앙대, 한국회계정보학회, 現)중앙대}
308                                      {대신증권}
309                                      {대신증권}
310                                      {대신증권}
311                                      {대신증권}
312                   {現)서울시립대, 한국조세연구원, 서울시립대}
313                             {대신에프앤아이, 대신증권}
314                                      {대신증권}
315                     {국가청렴위원회, 제58대, 現)재단법인}
316                            {대신투자신탁운용, 대신증권}
317                            {재경1WM부문장, 대신증권}
318              {대신에이엠씨, 대신저축은행, 대신자산운용, 대신증권}
319                                      {대신증권}
320                             {WM추진부문장, 대신증권}
321                                      {대신증권}
322                                      {대신증권}
323                                      {대신증권}
324                   {KTB투자증권, SC제일은행, 미래에셋증권}
325                                      {대신증권}
326                                      {대신증권}
327                      {중앙대, 한국회계정보학회, 現)중앙대}
328                                      {대신증권}
329                                      {대신증권}
330                              {NH투자증권, KB증권}
331                                      {대신증권}
332                                      {대신증권}
333                                      {대신증권}
334                                      {대신증권}
335                                      {대신증권}
336                                      {대신증권}
337                     {現)학교법인, 연세대학교, Arthur}
338                   {現)서울시립대, 한국조세연구원, 서울시립대}
339                                      {대신증권}
340                              {대신저축은행, 대신증권}
341                                      {대신증권}
342                                      {대신증권}
343                                      {대신증권}
344                                      {대신증권}
345            {IBK투자증권, 메리츠증권, 하나금융투자, DB금융투자}
346                                      {대신증권}
347                                      {대신증권}
348                                      {대신증권}
349                                      {대신증권}
350                                   {메리츠종금증권}
351                     {대신에프앤아이, 대신자산운용, 대신증권}
352                                      {대신증권}
353                      {국세청, 제22대, 現)법무법인(유)}
Name: 주요경력요약, dtype: object

In [213]:
cal_career(df.iloc[2], df.iloc[48])

0.409963413001697

In [214]:
cal_stock(df_2022.iloc[37], df_2022.iloc[7])

0.40215966791391633

# 가중치 행렬

In [215]:
# 인물 가중치행렬
col = []
row = []
matrixs = []
dataFrames = [df_2014, df_2015, df_2016, df_2017, df_2018, df_2019, df_2020, df_2021, df_2022, df_2023]

for dataframe in dataFrames:
  for i in range(len(dataframe)):
      col.append(dataframe.loc[i, '이름'])
      row.append(dataframe.loc[i, '이름'])
  weight_matrix = pd.DataFrame(columns=col, index=row)
  matrixs.append(weight_matrix)
  col=[]
  row=[]

#matrixs[0]->2014년도 인물 가중치행렬
#matrixs[1]->2015년도 인물 가중치행렬
#matrixs[2]->2016년도 인물 가중치행렬
#matrixs[3]->2017년도 인물 가중치행렬
#matrixs[4]->2018년도 인물 가중치행렬
#....

In [216]:
matrixs[9]

,김봉진,김성호,양홍석,강준규,최근영,권택현,신재범,정회민,이순남,박석원,...,윤태림,이정훈,김수창,김상원,이어룡,홍종국,길기모,김범철,김성균,한승희
김봉진,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
김성호,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
양홍석,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강준규,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
최근영,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
권택현,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
신재범,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
정회민,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
이순남,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
박석원,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
박정환,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
송혁,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강윤기,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
김창수,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
이재우,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
최광철,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
김상혁,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
송종원,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
박성준,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
이성영,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
박성희,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
나유석,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
정연우,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
조선영,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
원윤희,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
임민수,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
오익근,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
김광혁,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
정연규,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
최대경,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
윤태림,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
이정훈,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
김수창,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
김상원,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
이어룡,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
홍종국,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
길기모,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
김범철,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
김성균,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
한승희,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [218]:
#가중치 계산
for t, dataframe in enumerate(dataFrames):
  for i in range(0, len(dataframe)):
    for j in range(0, len(dataframe)):
      matrixs[t].iloc[i, j] = weight_sum(dataframe.iloc[i], dataframe.iloc[j])

## 2014년

In [220]:
matrixs[0]

,이현식,조윤남,나재철,이정훈,송혁,하창룡,이동훈,박동현,홍대한,박찬수,...,이어룡,양홍석,김봉규,조경순,김병철,김창봉,박찬욱,배영훈,이인형,장우철
이현식,7.0,4.19519,4.21819,3.7092,4.914579,4.861587,4.092733,4.914002,4.649258,3.789064,...,3.588858,4.568487,4.970461,4.66199,4.731925,3.4722,3.9192,5.161228,3.2622,4.883848
조윤남,4.19519,7.0,3.511418,2.952513,4.239698,4.520211,4.616196,4.507891,4.573793,3.122376,...,3.182097,3.401603,4.424536,4.55473,4.499945,2.952513,2.952513,4.482228,3.252513,5.014473
나재철,4.21819,3.511418,7.0,2.93274,3.733585,3.651241,3.371974,3.644073,4.033667,3.312604,...,4.484759,4.625657,3.89758,4.025667,3.964636,3.28974,3.44274,4.268639,3.07974,3.941995
이정훈,3.7092,2.952513,2.93274,7.0,3.437232,3.363614,2.868746,3.890365,3.184817,5.176974,...,3.410747,3.211984,3.160445,3.192063,3.180408,4.884805,5.841805,3.121235,4.674805,3.029555
송혁,4.914579,4.239698,3.733585,3.437232,7.0,4.494002,4.098336,4.441587,4.544227,3.517096,...,3.379153,3.758539,4.466805,4.613507,4.604807,3.200232,3.647232,4.666057,3.200232,4.493474
하창룡,4.861587,4.520211,3.651241,3.363614,4.494002,7.0,4.396198,5.540848,4.787516,3.833478,...,3.538623,3.40152,5.119763,4.817587,4.263638,3.516614,3.363614,4.360309,3.006614,4.647002
이동훈,4.092733,4.616196,3.371974,2.868746,4.098336,4.396198,7.0,4.394628,4.700896,3.038609,...,3.18476,3.192054,4.095604,4.699494,4.101779,2.868746,2.868746,4.275757,3.078746,4.541244
박동현,4.914002,4.507891,3.644073,3.890365,4.441587,5.540848,4.394628,7.0,4.761992,4.150228,...,3.53854,3.401505,5.08,4.782,4.24199,3.533365,3.380365,4.356093,3.023365,4.802342
홍대한,4.649258,4.573793,4.033667,3.184817,4.544227,4.787516,4.700896,4.761992,7.0,3.56468,...,3.391857,3.758561,4.475235,5.562122,4.434518,3.541817,3.394817,4.5838,3.631817,4.755576
박찬수,3.789064,3.122376,3.312604,5.176974,3.517096,3.833478,3.038609,4.150228,3.56468,7.0,...,3.580611,3.081848,3.840309,3.871927,3.140272,5.029974,5.386974,3.501099,4.519974,3.409418
신인식,5.071587,4.521063,3.861718,3.362692,5.008735,6.19,4.396298,5.534764,4.99945,4.042555,...,3.538628,3.611521,5.314619,5.027587,4.265235,3.725692,3.572692,4.570309,3.215692,4.852521
구희진,4.736591,4.150121,4.410221,3.151967,4.55966,4.035403,4.093632,4.026339,4.280939,3.401867,...,3.489336,4.13197,3.82185,4.268585,4.889825,3.451967,3.361967,4.901797,3.151967,4.380754
박규상,4.804587,4.520211,4.11082,3.216614,4.347002,4.933,4.243298,4.577764,4.69945,3.596478,...,3.356334,4.018621,5.257619,5.027587,4.263638,3.426614,3.726614,5.407309,3.516614,5.299521
유승덕,4.667955,3.968476,3.941596,3.095434,4.466051,3.953015,3.802242,3.950705,4.469939,3.345334,...,3.490912,4.13224,3.741992,4.467959,4.7713,3.095434,3.305434,5.030585,3.395434,4.160004
김송규,4.745329,5.073638,4.119543,2.978337,4.572081,4.589945,4.400244,4.560544,5.329763,3.3582,...,3.181826,4.058556,4.997516,5.119763,4.380387,3.335337,3.488337,4.971767,3.635337,5.573348
김경식,3.9321,3.712413,3.74964,3.7132,3.660132,3.676514,3.328646,3.693265,4.301717,3.970074,...,3.213647,3.614546,3.683345,4.308963,3.640308,4.2802,3.9232,4.391135,4.6702,3.999455
장광수,5.849751,4.192927,4.363726,3.26965,4.761992,4.497726,4.092455,4.544227,4.793414,3.649513,...,3.441843,4.415485,4.604807,4.805579,4.728539,3.62665,3.77965,5.160303,3.41665,4.866751
김경찬,3.681964,3.582276,3.127153,3.760074,3.409996,3.846378,3.798509,3.863128,4.26158,3.8161,...,2.765865,3.018848,3.943209,4.568827,3.390172,3.907074,3.760074,3.840999,3.697074,3.659318
임홍재,5.723175,4.030145,4.263748,3.567716,4.600008,4.336605,4.076208,4.38493,4.484009,3.727616,...,3.488508,4.431825,4.444247,4.496358,4.56603,3.477716,3.777716,5.354193,3.267716,5.065741
권인섭,4.431247,4.313514,3.397486,3.402941,4.264379,4.373056,4.226068,4.6028,4.484257,3.442841,...,3.017907,3.411794,4.08102,4.492257,4.032428,3.339941,3.192941,3.969871,3.339941,4.400298
이어룡,3.588858,3.182097,4.484759,3.410747,3.379153,3.538623,3.18476,3.53854,3.391857,3.580611,...,7.0,3.619427,3.293297,3.391789,3.652319,2.753747,3.410747,3.44332,2.543747,3.18152
양홍석,4.568487,3.401603,4.625657,3.211984,3.758539,3.40152,3.192054,3.401505,3.758561,3.081848,...,3.619427,7.0,3.598615,3.758549,4.058568,3.058984,3.421984,4.268742,3.058984,3.911501
김봉규,4.970461,4.424536,3.89758,3.160445,4.466805,5.119763,4.095604,5.08,4.475235,3.840309,...,3.293297,3.598615,7.0,4.499945,3.833348,3.523445,3.670445,4.448426,3.223445,5.100387
조경순,4.66199,4.55473,4.025667,3.192063,4.613507,4.817587,4.699494,4.782,5.562122,3.871927,...,3.391789,3.758549,4.499945,7.0,4.347002,3.549063,3.402063,4.879801,3.339063,4.773638
김병철,4.731925,4.499945,3.964636,3.180408,4.604807,4.263638,4.101779,4.24199,4.434518,3.140272,...,3.652319,4.058568,3.833348,4.347002,7.0,2.970408,3.180408,4.676626,2.970408,4.236396
김창봉,3.4722,2.952513,3.28974,4.884805,3.200232,3.516614,2.868746,3.533365,3.541817,5.029974,...,2.753747,3.058984,3.523445,3.549063,2.970408,7.0,5.443,3.331235,5.116231,3.239555
박찬욱,3.9192,2.952513,3.44274,5.841805,3.647232,3.363614,2.868746,3.380365,3.394817,5.386974,...,3.410747,3.421984,3.670445,3.402063,3.180408,5.443,7.0,3.631235,4.759231,3.539555
배영훈,5.161228,4.482228,4.268639,3.121235,4.666057,4.360309,4.275757,4.356093,4.5838,3.501099,...,3.44332,4.268742,4.448426,4.879801,4.676626,3.331235,3.631235,7.0,3.421235,5.311836
이인형,3.2622,3.252513,3.07974,4.674805,3.200232,3.006614,3.078746,3.023365,3.631817,4.519974,...,2.543747,3.058984,3.223445,3.339063,2.970408,5.116231,4.759231,3.421235,7.0,3.539555
장우철,4.883848,5.014473,3.941995,3.029555,4.493474,4.647002,4.541244,4.802342,4.755576,3.409418,...,3.18152,3.911501,5.100387,4.773638,4.236396,3.239555,3.539555,5.311836,3.539555,7.0

## 2015년

In [221]:
matrixs[1]

,박규상,정상명,김창봉,김경찬,유승덕,김병철,양홍석,김송규,하창룡,김경식,...,신인식,송혁,김재중,이현식,권인섭,장광수,박찬수,조경순,이인형,최명재
박규상,7.0,3.188943,3.398943,4.118706,4.437211,4.356751,4.017505,5.102342,4.507018,4.408743,...,4.717018,4.38745,4.696815,4.748579,4.041803,4.744279,3.568806,5.249751,3.488943,4.725317
정상명,3.188943,7.0,5.233,3.907074,2.861096,2.968832,3.147839,3.123552,3.215692,4.3702,...,3.214783,2.988091,3.527819,3.560449,3.549941,3.414716,4.876974,3.338427,4.549231,3.620574
김창봉,3.398943,5.233,7.0,3.760074,3.071096,2.968832,2.910839,3.186552,3.662692,3.9232,...,3.871783,3.345091,3.437819,3.617449,3.192941,3.477716,5.029974,3.401427,5.416231,3.320574
김경찬,4.118706,3.907074,3.760074,7.0,3.870896,3.598595,3.120603,3.753316,4.145455,4.666974,...,4.144546,3.617855,4.237619,3.890213,4.559741,4.254479,3.9631,4.86819,3.550074,4.550338
유승덕,4.437211,2.861096,3.071096,3.870896,7.0,4.738931,4.13131,4.437568,3.924108,5.027556,...,4.134192,4.435981,4.081409,4.641191,4.081631,4.640955,3.320996,4.736856,3.371096,4.219339
김병철,4.356751,2.968832,2.968832,3.598595,4.738931,7.0,4.057421,4.680387,4.260544,4.188632,...,4.262075,4.604807,3.819034,4.730211,4.030708,4.727719,3.138695,4.33827,2.968832,4.349506
양홍석,4.017505,3.147839,2.910839,3.120603,4.13131,4.057421,7.0,4.204408,3.400373,3.653301,...,3.610374,3.757393,3.563645,4.567342,3.410649,4.414339,3.227703,3.757401,2.910839,3.40032
김송규,5.102342,3.123552,3.186552,3.753316,4.437568,4.680387,4.204408,7.0,4.287726,4.553352,...,4.497726,4.872081,4.547257,5.043245,4.186166,5.187233,3.503416,4.804619,3.486552,4.212245
하창룡,4.507018,3.215692,3.662692,4.145455,3.924108,4.260544,3.400373,4.287726,7.0,4.135492,...,6.19,4.48527,4.368886,4.861587,4.371989,4.497726,3.685555,4.814807,3.152692,4.761992
김경식,4.408743,4.3702,3.9232,4.666974,5.027556,4.188632,3.653301,4.553352,4.135492,7.0,...,4.344583,4.417891,4.794279,4.690249,4.396401,4.844516,4.327074,5.068227,4.0132,4.840374
배영훈,5.390819,3.103824,3.313824,4.033587,4.987309,4.647618,4.267678,5.244641,4.336928,4.833624,...,4.547108,4.641035,4.608273,5.140816,3.951703,5.140337,3.483687,4.853009,3.403824,4.627097
장우철,5.217544,3.025776,3.235776,3.955539,4.132547,4.236396,3.910357,5.273348,4.651735,4.155576,...,4.861735,4.493474,5.048391,4.877764,4.395706,4.857002,3.405639,4.775235,3.535776,4.583474
홍대한,4.854518,3.331248,3.394248,4.561012,4.438018,4.423,3.757412,5.069342,4.787516,4.761048,...,4.99945,4.54827,4.544797,4.649258,4.483633,4.793414,3.711112,5.862122,3.484248,4.719311
나재철,4.10758,2.921661,3.131661,3.166495,3.903566,3.939253,4.624542,4.169328,3.633977,3.591561,...,3.843977,3.714435,3.600854,4.204372,3.385581,4.350212,3.448525,4.003663,2.921661,3.468447
조윤남,4.108422,2.922368,2.922368,3.632168,4.406439,4.537403,3.410879,4.830308,4.003648,4.278828,...,4.003648,4.312242,4.143851,4.291818,4.144836,4.29064,3.172268,4.016591,3.222368,3.984822
정태영,4.408743,4.0132,3.9232,4.009974,4.127556,3.888632,4.016301,4.406352,3.925492,5.443,...,4.134583,4.117891,5.031279,4.690249,4.039401,4.697516,4.270074,4.111227,3.7132,4.330374
이어룡,3.353976,2.604247,3.408247,2.79866,3.48959,3.649783,3.618495,3.229715,3.536102,2.992117,...,3.536102,3.376629,2.86839,3.586346,3.015404,3.439332,2.921111,3.389256,3.198247,3.24181
박동현,4.475235,3.74219,3.67919,4.161953,3.92279,4.239698,3.400359,4.259046,5.540848,4.15199,...,5.534764,4.436945,4.387321,4.914002,4.601391,4.544227,4.002053,4.780249,3.16919,4.787516
한여선,4.775706,4.360074,3.970074,4.933,3.570896,3.388595,3.680703,3.906316,3.845455,4.519974,...,4.054546,3.617855,4.894619,4.490213,3.902741,4.197479,4.0261,4.03119,3.760074,4.250338
이동훈,4.204759,2.832894,2.832894,4.062658,3.727996,4.058564,3.191448,4.057936,4.356191,3.752694,...,4.356234,4.057143,4.546632,4.054676,4.189792,4.054511,3.002758,4.657582,3.042894,4.353654
신재국,3.398943,5.841805,5.094805,3.907074,3.071096,2.968832,3.057839,3.333552,3.215692,4.5802,...,3.424783,3.198091,3.737819,3.470449,3.339941,3.924716,5.086974,3.548427,4.884805,3.620574
신인식,4.717018,3.214783,3.871783,4.144546,4.134192,4.262075,3.610374,4.497726,6.19,4.344583,...,7.0,4.999521,4.577882,5.071587,4.371989,4.70557,3.894646,5.027587,3.361783,4.760661
송혁,4.38745,2.988091,3.345091,3.617855,4.435981,4.604807,3.757393,4.872081,4.48527,4.417891,...,4.999521,7.0,4.46966,4.91173,4.261977,4.760661,3.367955,4.633,3.345091,4.227349
김재중,4.696815,3.527819,3.437819,4.237619,4.081409,3.819034,3.563645,4.547257,4.368886,4.794279,...,4.577882,4.46966,7.0,4.630134,5.039751,4.638891,3.687719,4.552479,3.437819,4.804424
이현식,4.748579,3.560449,3.617449,3.890213,4.641191,4.730211,4.567342,5.043245,4.861587,4.690249,...,5.071587,4.91173,4.630134,7.0,4.426605,5.849751,3.640313,4.66199,3.407449,4.540374
권인섭,4.041803,3.549941,3.192941,4.559741,4.081631,4.030708,3.410649,4.186166,4.371989,4.396401,...,4.371989,4.261977,5.039751,4.426605,7.0,4.793189,3.589841,4.491551,3.192941,4.52411
장광수,4.744279,3.414716,3.477716,4.254479,4.640955,4.727719,4.414339,5.187233,4.497726,4.844516,...,4.70557,4.760661,4.638891,5.849751,4.793189,7.0,3.794579,4.805579,3.267716,4.557002
박찬수,3.568806,4.876974,5.029974,3.9631,3.320996,3.138695,3.227703,3.503416,3.685555,4.327074,...,3.894646,3.367955,3.687719,3.640313,3.589841,3.794579,7.0,3.71829,4.519974,3.490438
조경순,5.249751,3.338427,3.401427,4.86819,4.736856,4.33827,3.757401,4.804619,4.814807,5.068227,...,5.027587,4.633,4.552479,4.66199,4.491551,4.805579,3.71829,7.0,3.491427,5.028539
이인형,3.488943,4.549231,5.416231,3.550074,3.371096,2.968832,2.910839,3.486552,3.152692,4.0132,...,3.361783,3.345091,3.437819,3.407449,3.192941,3.267716,4.519974,3.491427,7.0,3.110574
최명재,4.725317,3.620574,3.320574,4.550338,4.219339,4.349506,3.40032,4.212245,4.761992,4.840374,...,4.760661,4.227349,4.804424,4.540374,4.52411,4.557002,3.490438,5.028539,3.110574,7.0

## 2016년

In [222]:
matrixs[2]

,최명재,송혁,이정화,김재중,신재국,정태암,이문수,박동현,권인섭,이어룡,...,김성원,양홍석,정재중,한여선,조경순,김창봉,하창룡,최범진,이지원,배영훈
최명재,7.0,4.227349,4.656751,4.804424,3.620574,4.41764,3.891895,4.487516,4.22411,3.239367,...,4.921193,3.399887,4.921193,4.330374,5.028539,3.320574,4.461992,4.330374,3.320574,4.614642
송혁,4.227349,7.0,4.393813,4.46966,3.198091,3.6558,3.790129,4.736945,4.561977,3.374152,...,3.868492,3.756957,4.373414,3.697891,4.633,3.345091,4.78527,3.907891,2.988091,4.625477
이정화,4.656751,4.393813,7.0,4.643678,3.271635,4.634227,4.648783,4.680176,4.141467,3.176447,...,4.651735,3.399902,5.728735,3.981435,4.745329,3.718635,4.638435,4.791435,3.571635,4.316806
김재중,4.804424,4.46966,4.643678,7.0,3.737819,4.030167,4.24199,4.087321,4.739751,2.865952,...,4.510508,3.563212,4.720508,4.843281,4.552479,3.437819,4.068886,4.794279,3.737819,4.449338
신재국,3.620574,3.198091,3.271635,3.737819,7.0,3.136951,3.371479,3.23219,3.339941,2.601812,...,3.89547,3.057406,3.32847,4.270074,3.401427,5.094805,3.215692,3.8602,5.8,3.449091
정태암,4.41764,3.6558,4.634227,4.030167,3.136951,7.0,4.9028,3.91154,3.914178,2.969339,...,5.129751,3.014952,4.802342,3.846751,4.004536,3.136951,3.888576,4.146751,3.436951,3.747056
이문수,3.891895,3.790129,4.648783,4.24199,3.371479,4.9028,7.0,3.927279,3.735576,2.806252,...,5.355735,3.835341,4.610298,4.234279,4.12223,3.224479,3.914178,4.266941,3.971479,4.247821
박동현,4.487516,4.736945,4.680176,4.087321,3.23219,3.91154,3.927279,7.0,4.601391,3.583983,...,4.126793,3.546925,4.632631,3.73199,4.482,3.67919,5.540848,3.94199,3.23219,4.620234
권인섭,4.22411,4.561977,4.141467,4.739751,3.339941,3.914178,3.735576,4.601391,7.0,3.063386,...,4.021782,3.557215,4.231782,3.788403,4.044551,3.192941,4.371989,4.396401,3.339941,4.386679
이어룡,3.239367,3.374152,3.176447,2.865952,2.601812,2.969339,2.806252,3.583983,3.063386,7.0,...,3.179357,3.618531,3.176363,2.693966,3.386776,3.405812,3.584054,2.729261,2.601812,3.43908
신인식,4.460661,5.152521,4.491435,4.277882,3.571783,3.88736,4.25966,5.177764,4.728989,3.437059,...,4.459355,3.903939,4.459355,3.924583,4.727587,3.724783,5.833,4.281583,3.571783,4.979378
홍대한,4.719311,4.54827,4.733685,4.544797,3.541248,3.995143,4.245735,4.461992,4.183633,3.386834,...,4.564891,3.756976,4.717891,4.104048,5.715122,3.394248,4.487516,4.551048,3.541248,4.685769
나재철,3.454685,3.6935,3.45847,3.587995,3.119143,3.157764,3.66435,3.683465,3.444602,4.480126,...,4.025565,4.624156,3.454483,3.399592,3.83443,3.119143,3.687477,3.297013,3.419143,4.364088
장우철,4.283474,4.793474,4.754227,4.601391,3.235776,4.126793,4.612401,4.829751,4.395706,3.22697,...,4.434435,4.056922,5.001435,4.392576,4.475235,3.235776,4.651735,4.155576,3.535776,5.219712
박규상,4.725317,4.38745,4.442226,4.549815,3.398943,4.211499,4.624176,4.265235,3.831803,3.351499,...,5.234536,4.017069,4.424536,4.855743,5.249751,3.398943,4.297018,4.108743,3.698943,5.227398
이환목,3.690482,3.146883,4.197444,4.32764,3.642196,4.349737,4.548072,3.397553,3.754193,2.466287,...,4.719716,3.088286,3.999716,4.400784,3.706285,3.942196,3.377453,4.105085,3.942196,3.453222
김경찬,4.630374,3.844891,4.218435,4.333281,3.760074,3.636751,3.514279,4.08899,3.998403,3.533261,...,4.12827,3.053206,4.27527,4.933,4.801227,4.417074,4.072492,4.513,3.760074,4.101891
정태영,4.330374,4.117891,3.981435,4.884279,4.2232,3.596851,3.870041,4.45199,4.249401,3.061712,...,4.29837,4.015868,4.03827,5.233,4.111227,3.9232,4.135492,4.723,4.2232,4.521891
김경식,4.977034,4.701551,4.475095,4.957619,4.2232,3.836411,3.787279,4.73565,4.712741,3.783342,...,4.53793,3.620206,4.53193,4.818662,5.057887,4.5802,4.719152,4.76966,3.9232,4.958551
김범철,4.322291,4.431247,4.666465,4.459355,3.588034,4.044895,5.08064,5.267853,4.400348,3.126652,...,4.91866,4.367265,4.620453,4.240834,4.530453,3.441034,4.727047,4.483496,4.188034,5.114026
최정석,4.10866,3.569189,4.240121,3.736813,3.375779,4.700298,5.249342,4.429411,3.950661,3.016234,...,5.0622,3.535337,4.196909,3.938579,4.114176,3.528779,4.084782,4.271241,3.675779,3.94729
이동훈,4.33316,4.03527,4.333614,4.169396,2.959762,4.03301,3.808119,4.034279,4.01647,3.186121,...,3.97011,3.338582,4.333135,3.522562,4.635534,2.812762,4.034693,4.389562,2.959762,4.405079
유승덕,4.228563,4.593796,4.077237,4.090373,3.079956,3.361108,3.439901,4.379858,4.39064,4.143327,...,4.081381,4.130768,4.075472,3.675418,4.747776,3.736956,4.381479,3.926416,3.079956,5.054197
정상명,3.620574,2.988091,3.061635,3.527819,5.541805,3.136951,3.161479,3.74219,3.549941,2.601812,...,3.68547,3.147406,3.11847,4.360074,3.191427,5.233,3.215692,3.6502,5.841805,3.239091
박찬수,3.490438,3.514955,3.588498,3.687719,4.729974,3.306814,3.394343,4.149053,3.442841,3.575675,...,3.708333,3.08027,3.645333,4.268762,3.57129,5.686974,3.832555,3.760074,4.729974,3.471954
김성원,4.921193,3.868492,4.651735,4.510508,3.89547,5.129751,5.355735,4.126793,4.021782,3.179357,...,7.0,3.881955,5.023,4.54827,4.726909,3.53847,4.102355,4.48527,4.49547,4.914407
양홍석,3.399887,3.756957,3.399902,3.563212,3.057406,3.014952,3.835341,3.546925,3.557215,3.618531,...,3.881955,7.0,3.399885,3.760306,3.609966,2.910406,3.546938,3.295868,3.657406,4.41432
정재중,4.921193,4.373414,5.728735,4.720508,3.32847,4.802342,4.610298,4.632631,4.231782,3.176363,...,5.023,3.399885,7.0,4.03827,4.727719,3.47547,4.607661,4.84827,3.62847,4.314524
한여선,4.330374,3.697891,3.981435,4.843281,4.270074,3.846751,4.234279,3.73199,3.788403,2.693966,...,4.54827,3.760306,4.03827,7.0,4.111227,3.970074,3.715492,4.423,4.570074,4.101891
조경순,5.028539,4.633,4.745329,4.552479,3.401427,4.004536,4.12223,4.482,4.044551,3.386776,...,4.726909,3.609966,4.727719,4.111227,7.0,3.401427,4.517587,4.411227,3.401427,4.836799
김창봉,3.320574,3.345091,3.718635,3.437819,5.094805,3.136951,3.224479,3.67919,3.192941,3.405812,...,3.53847,2.910406,3.47547,3.970074,3.401427,7.0,3.662692,3.7132,5.094805,3.302091
하창룡,4.461992,4.78527,4.638435,4.068886,3.215692,3.888576,3.914178,5.540848,4.371989,3.584054,...,4.102355,3.546938,4.607661,3.715492,4.517587,3.662692,7.0,3.925492,3.215692,4.622378
최범진,4.330374,3.907891,4.791435,4.794279,3.8602,4.146751,4.266941,3.94199,4.396401,2.729261,...,4.48527,3.295868,4.84827,4.423,4.411227,3.7132,3.925492,7.0,4.1602,4.158891
이지원,3.320574,2.988091,3.571635,3.737819,5.8,3.436951,3.971479,3.23219,3.339941,2.601812,...,4.49547,3.657406,3.62847,4.570074,3.401427,5.094805,3.215692,4.1602,7.0,3.749091
배영훈,4.614642,4.625477,4.316806,4.449338,3.449091,3.747056,4.247821,4.620234,4.386679,3.43908,...,4.914407,4.41432,4.314524,4.101891,4.836799,3.302091,4.622378,4.158891,3.749091,7.0

## 2017년

In [223]:
matrixs[3]

,이어룡,박동현,김재중,최범진,정태영,김창봉,조경순,김성원,정태암,김범철,...,홍대한,최명재,정재중,박찬수,박규상,신재국,한여선,권인섭,나재철,양홍석
이어룡,7.0,3.581246,2.863579,3.520485,3.059448,2.746376,3.38394,3.176824,2.966824,3.123906,...,3.383969,3.236825,3.173825,2.91624,3.348905,3.256376,2.691625,3.060906,4.477236,3.619061
박동현,3.581246,7.0,4.17493,4.70666,4.491435,4.0132,4.529805,4.576,4.366,5.36966,...,4.507018,4.933,5.08,4.483063,4.220211,3.8602,3.824227,5.06966,3.68696,3.546754
김재중,2.863579,4.17493,7.0,4.84827,4.788395,3.32847,4.849002,4.47493,3.96493,4.54827,...,4.741782,4.77493,4.68493,3.57837,4.589825,3.62847,5.118662,4.54827,3.610842,3.563114
최범진,3.520485,4.70666,4.84827,7.0,4.118095,3.7132,4.666465,4.85966,4.64966,4.933,...,4.643678,4.85966,5.51666,3.9631,4.266871,4.3702,4.129889,4.723,3.30459,3.263094
정태영,3.059448,4.491435,4.788395,4.118095,7.0,3.481635,4.290387,4.241535,3.521535,4.887097,...,4.357619,4.281435,3.981435,3.828509,4.480249,3.781635,4.866751,4.118095,3.864842,4.015792
김창봉,2.746376,4.0132,3.32847,3.7132,3.481635,7.0,3.520005,4.2802,3.5032,4.0702,...,3.644218,3.7132,3.7132,5.386974,3.420411,5.094805,3.581301,3.6502,3.28406,3.057294
조경순,3.38394,4.529805,4.849002,4.666465,4.290387,3.520005,7.0,4.829805,4.109805,4.576465,...,5.767619,5.129805,4.829805,3.689868,4.969355,3.520005,4.412342,4.156465,3.832636,3.609778
김성원,3.176824,4.576,4.47493,4.85966,4.241535,4.2802,4.829805,7.0,5.323,5.36966,...,4.654018,5.023,5.023,4.450063,5.240211,3.9232,4.544227,4.34966,4.039214,3.881824
정태암,2.966824,4.366,3.96493,4.64966,3.521535,3.5032,4.109805,5.323,7.0,4.50266,...,4.087018,4.66,5.023,3.673063,4.220211,3.5032,3.824227,4.20266,3.172214,3.014824
김범철,3.123906,5.36966,4.54827,4.933,4.887097,4.0702,4.576465,5.36966,4.50266,7.0,...,4.910678,4.76966,5.06966,4.540063,4.566871,3.9232,4.334227,4.87,4.03362,4.367094
송혁,3.371246,5.17,4.59493,4.70666,4.191435,3.7132,4.529805,4.366,4.156,4.85966,...,4.507018,4.723,4.87,3.883063,4.220211,3.8602,3.824227,5.06966,3.68696,3.756754
이지원,2.599376,3.7132,3.62847,4.0132,3.781635,5.751805,3.520005,4.8802,3.8032,4.6702,...,3.644218,3.7132,4.0132,5.086974,3.720411,5.443,4.181301,3.6502,3.43706,3.657294
최정석,3.013484,4.62266,3.82827,4.513,3.617197,4.1602,4.156465,5.51666,5.15966,5.023,...,4.280678,4.55966,4.64966,4.030063,4.266871,3.7132,4.034227,4.423,3.365874,3.535164
이정화,3.173825,5.08,4.68493,5.51666,3.981435,4.0132,4.829805,5.023,5.023,5.06966,...,4.807018,5.023,6.1,3.883063,4.430211,3.8602,4.034227,4.55966,3.46793,3.399754
배영훈,3.436484,4.611557,4.450833,4.148217,4.526439,3.448757,4.824759,4.911557,3.744557,5.105217,...,4.672592,4.611557,4.311557,3.61862,5.222652,3.301757,4.104173,4.385217,4.339031,4.41421
하창룡,3.581246,5.89,4.17493,4.70666,4.191435,4.0132,4.529805,4.576,4.366,5.06966,...,4.507018,4.933,5.08,4.183063,4.220211,3.8602,3.824227,4.85966,3.68696,3.546754
이문수,2.803484,4.20266,4.33827,4.723,3.917197,3.8602,4.156465,5.81666,5.36966,5.323,...,4.280678,4.34966,5.06966,4.030063,4.566871,3.7132,4.334227,4.213,3.665874,3.835164
정상명,3.256376,4.3702,3.41847,4.1602,3.571635,5.233,3.310005,3.7132,3.5032,3.7132,...,3.287218,4.0132,3.6502,4.519974,3.210411,5.841805,3.971301,3.7132,2.78006,3.000294
이동훈,3.184483,4.025971,4.163119,4.372631,3.516866,2.953171,4.626544,3.962971,4.025971,4.009631,...,4.773715,4.325971,4.325971,3.123035,4.027913,2.806171,3.516459,4.009631,3.436775,3.338728
장우철,3.224381,4.604807,4.759401,4.351467,4.99,3.295007,4.69064,4.457807,4.157807,4.951467,...,4.776515,4.304807,5.024807,3.464871,5.00314,3.295007,4.57,4.441467,3.996157,4.056782
이환목,2.463934,3.444782,4.259741,4.094807,3.793063,3.851882,3.977614,4.611782,4.191782,4.157807,...,4.06349,3.591782,3.891782,3.754907,3.963115,3.551882,4.428662,3.437807,2.888386,3.088192
신인식,3.434246,5.533,4.38493,4.76966,4.401435,4.3702,4.739805,4.933,4.366,5.42666,...,4.864018,4.933,4.933,4.540063,4.430211,3.9232,4.034227,5.21666,4.04396,3.903754
홍대한,3.383969,4.507018,4.741782,4.643678,4.357619,3.644218,5.767619,4.654018,4.087018,4.910678,...,7.0,4.807018,4.807018,3.814082,4.679046,3.497218,4.313507,4.280678,3.981735,3.756784
최명재,3.236825,4.933,4.77493,4.85966,4.281435,3.7132,5.129805,5.023,4.66,4.76966,...,4.807018,7.0,5.023,3.883063,4.730211,4.0132,4.334227,4.55966,3.46793,3.399754
정재중,3.173825,5.08,4.68493,5.51666,3.981435,3.7132,4.829805,5.023,5.023,5.06966,...,4.807018,5.023,7.0,3.883063,4.430211,3.8602,4.034227,4.55966,3.46793,3.399754
박찬수,2.91624,4.483063,3.57837,3.9631,3.828509,5.386974,3.689868,4.450063,3.673063,4.540063,...,3.814082,3.883063,3.883063,7.0,3.590274,4.729974,3.879989,3.9001,3.453923,3.227157
박규상,3.348905,4.220211,4.589825,4.266871,4.480249,3.420411,4.969355,5.240211,4.220211,4.566871,...,4.679046,4.730211,4.430211,3.590274,7.0,3.420411,4.900165,3.846871,4.104076,4.016932
신재국,3.256376,3.8602,3.62847,4.3702,3.781635,5.094805,3.520005,3.9232,3.5032,3.9232,...,3.497218,4.0132,3.8602,4.729974,3.420411,7.0,3.881301,3.5032,2.99006,2.910294
한여선,2.691625,3.824227,5.118662,4.129889,4.866751,3.581301,4.412342,4.544227,3.824227,4.334227,...,4.313507,4.334227,4.034227,3.879989,4.900165,3.881301,7.0,3.709889,3.423761,3.760215
권인섭,3.060906,5.06966,4.54827,4.723,4.118095,3.6502,4.156465,4.34966,4.20266,4.87,...,4.280678,4.55966,4.55966,3.9001,3.846871,3.5032,3.709889,7.0,3.46062,3.557094
나재철,4.477236,3.68696,3.610842,3.30459,3.864842,3.28406,3.832636,4.039214,3.172214,4.03362,...,3.981735,3.46793,3.46793,3.453923,4.104076,2.99006,3.423761,3.46062,7.0,4.623973
양홍석,3.619061,3.546754,3.563114,3.263094,4.015792,3.057294,3.609778,3.881824,3.014824,4.367094,...,3.756784,3.399754,3.399754,3.227157,4.016932,2.910294,3.760215,3.557094,4.623973,7.0

## 2018년

In [224]:
matrixs[4]

,정태암,박성준,이환목,김재중,김병철,이순남,정연규,김상원,오익근,진승욱,...,최명재,이동훈,나재철,이득원,신인식,송혁,김호중,김범철,신재국,이정화
정태암,7.0,4.116695,3.609201,3.89866,3.5032,4.723,4.723,4.87,4.20266,4.34966,...,4.503515,4.023798,3.14948,4.34966,4.209515,3.999515,4.723,4.346175,3.5032,4.866515
박성준,4.116695,7.0,4.270612,4.98493,3.616895,5.346695,5.136695,5.346695,5.240355,5.483355,...,4.844227,4.3243,3.959827,5.483355,4.75827,4.33827,5.193695,4.89493,3.526895,4.844227
이환목,3.609201,4.270612,7.0,4.667469,3.269301,4.239201,4.029201,3.939201,4.142226,4.442226,...,4.031254,3.61236,2.957438,4.442226,3.941254,3.521254,4.239201,4.444279,3.479301,4.631254
김재중,3.89866,4.98493,4.667469,7.0,3.0522,4.61866,4.61866,4.61866,4.182,4.782,...,4.712291,4.161407,3.590739,4.782,4.324176,4.534176,4.31866,4.487516,3.5622,4.622291
김병철,3.5032,3.616895,3.269301,3.0522,7.0,4.0132,3.8032,4.0132,4.0132,4.1602,...,3.556715,2.950998,2.904326,4.1602,4.003715,3.136715,4.3132,3.703715,5.59,3.346715
이순남,4.723,5.346695,4.239201,4.61866,4.0132,7.0,5.59,6.043,5.06966,5.57966,...,4.776515,4.023798,3.904775,5.57966,4.776515,4.503515,5.743,4.913175,3.9232,5.133515
정연규,4.723,5.136695,4.029201,4.61866,3.8032,5.59,7.0,5.233,5.06966,5.36966,...,4.866515,4.323798,3.445196,5.36966,5.076515,5.013515,5.233,4.613175,3.7132,5.643515
김상원,4.87,5.346695,3.939201,4.61866,4.0132,6.043,5.233,7.0,5.06966,5.57966,...,5.133515,4.023798,4.204775,5.57966,4.776515,4.356515,5.743,4.913175,3.9232,4.776515
오익근,4.20266,5.240355,4.142226,4.182,4.0132,5.06966,5.06966,5.06966,7.0,5.443,...,4.613175,3.860458,3.563886,5.443,5.123175,4.703175,5.21666,5.286515,3.9232,4.613175
진승욱,4.34966,5.483355,4.442226,4.782,4.1602,5.57966,5.36966,5.57966,5.443,7.0,...,4.913175,4.517458,3.938856,6.19,4.970175,4.403175,5.27966,5.643515,4.3702,4.913175
최정석,4.85966,4.373355,4.232226,3.972,3.8602,5.06966,4.55966,5.06966,4.723,5.08,...,4.613175,4.007458,3.378435,5.08,4.550175,3.983175,5.06966,5.013515,3.8602,4.703175
이어룡,2.964145,3.23424,2.521415,2.860987,2.596697,3.345851,3.171146,3.198851,3.121227,3.070806,...,3.234153,3.181381,4.474893,3.070806,3.431578,3.368578,3.198851,3.121238,2.596697,3.171153
배영훈,3.73463,4.604052,3.806256,4.442858,3.01883,4.39163,4.09163,4.39163,4.43829,4.58529,...,4.601812,4.185734,4.341442,4.79529,4.958903,4.601903,4.09163,5.095563,3.43883,4.301812
박동현,4.209515,4.54827,3.731254,4.112291,3.556715,4.923515,4.923515,4.566515,4.913175,4.613175,...,4.933,4.023838,3.66474,4.913175,5.533,5.17,4.566515,5.36966,3.556715,5.08
이창세,3.5032,3.616895,3.269301,3.0522,5.89,4.0132,3.8032,4.0132,4.0132,4.1602,...,3.556715,2.950998,2.904326,4.1602,3.703715,3.136715,4.0132,3.703715,5.89,3.346715
조경순,3.953469,4.922342,3.978975,4.408741,3.300669,4.520469,4.520469,4.520469,5.167129,4.567129,...,4.829805,4.324401,3.879795,4.567129,5.039805,4.829805,4.520469,4.876465,3.510669,4.529805
김성원,5.323,4.836695,4.029201,4.40866,4.0702,5.443,4.723,5.443,4.62266,5.21666,...,4.866515,3.960798,4.01648,5.21666,4.776515,4.209515,5.143,5.213175,4.2802,4.866515
권택현,4.132013,5.604183,3.946739,4.788828,3.212213,4.942013,5.152013,4.942013,4.835673,5.078673,...,4.432409,4.330771,3.902505,5.078673,4.342409,4.132409,4.789013,4.47907,3.122213,4.852409
홍대한,3.935231,4.815122,3.992544,4.459401,3.429431,4.502231,4.502231,4.502231,5.148891,4.905891,...,4.507018,4.681543,4.028135,4.695891,5.166529,4.809529,4.502231,5.213189,3.639431,4.507018
정재중,4.866515,4.844227,4.331254,4.622291,3.346715,5.133515,5.943515,4.776515,4.613175,4.913175,...,5.023,4.323838,3.44571,4.913175,4.933,4.87,4.776515,5.06966,3.556715,6.1
이지원,3.8032,3.826895,3.779301,3.5622,5.233,4.3702,3.8602,4.2232,3.9232,4.2232,...,3.556715,2.803998,3.267326,4.2232,3.766715,3.493715,3.9232,4.366715,5.443,4.003715
이문수,5.06966,4.673355,4.232226,4.482,3.6502,5.36966,4.97966,5.36966,4.723,5.38,...,4.403175,4.007458,3.678435,5.38,4.550175,4.193175,5.06966,5.313515,3.8602,5.123175
양홍석,3.012863,3.760813,3.261195,3.561171,2.698333,3.657893,3.250793,3.657893,3.771133,4.071133,...,3.397795,3.336711,4.622083,4.071133,3.901796,3.754796,3.357893,4.365136,3.055333,3.397795
최명재,4.503515,4.844227,4.031254,4.712291,3.556715,4.776515,4.866515,5.133515,4.613175,4.913175,...,7.0,4.323838,3.44571,4.913175,4.933,4.723,4.776515,4.76966,3.856715,5.023
이동훈,4.023798,4.3243,3.61236,4.161407,2.950998,4.023798,4.323798,4.023798,3.860458,4.517458,...,4.323838,7.0,3.436848,4.307458,4.170858,4.023858,4.023798,4.217518,2.950998,4.323838
나재철,3.14948,3.959827,2.957438,3.590739,2.904326,3.904775,3.445196,4.204775,3.563886,3.938856,...,3.44571,3.436848,7.0,3.938856,4.02174,3.66474,3.604775,4.0114,3.114326,3.44571
이득원,4.34966,5.483355,4.442226,4.782,4.1602,5.57966,5.36966,5.57966,5.443,6.19,...,4.913175,4.307458,3.938856,7.0,4.970175,4.403175,5.27966,5.733515,4.0702,4.913175
신인식,4.209515,4.75827,3.941254,4.324176,4.003715,4.776515,5.076515,4.776515,5.123175,4.970175,...,4.933,4.170858,4.02174,4.970175,7.0,5.533,5.076515,5.42666,3.913715,4.933
송혁,3.999515,4.33827,3.521254,4.534176,3.136715,4.503515,5.013515,4.356515,4.703175,4.403175,...,4.723,4.023858,3.66474,4.403175,5.533,7.0,4.356515,4.85966,3.556715,4.87
김호중,4.723,5.193695,4.239201,4.31866,4.3132,5.743,5.233,5.743,5.21666,5.27966,...,4.776515,4.023798,3.604775,5.27966,5.076515,4.356515,7.0,4.613175,3.9232,5.076515
김범철,4.346175,4.89493,4.444279,4.487516,3.703715,4.913175,4.613175,4.913175,5.286515,5.643515,...,4.76966,4.217518,4.0114,5.733515,5.42666,4.85966,4.613175,7.0,3.913715,5.06966
신재국,3.5032,3.526895,3.479301,3.5622,5.59,3.9232,3.7132,3.9232,3.9232,4.3702,...,3.856715,2.950998,3.114326,4.0702,3.913715,3.556715,3.9232,3.913715,7.0,3.556715
이정화,4.866515,4.844227,4.631254,4.622291,3.346715,5.133515,5.643515,4.776515,4.613175,4.913175,...,5.023,4.323838,3.44571,4.913175,4.933,4.87,5.076515,5.06966,3.556715,7.0

## 2019년

In [225]:
matrixs[5]

,최명재,진승욱,권택현,이재우,정연우,문병식,이환목,신재국,박동현,정태암,...,홍대한,길기모,이정화,송혁,이순남,신인식,임민수,김상원,이성근,오익근
최명재,7.0,4.809423,4.395309,4.644518,4.944518,4.644518,4.346348,3.724718,5.89,4.090619,...,4.804587,4.644518,5.17,4.976751,4.739751,5.076515,4.791518,4.502342,4.509423,4.509423
진승욱,4.809423,7.0,5.041288,5.177853,5.123175,4.970175,4.098632,4.213715,4.794279,4.71266,...,4.98311,5.019177,4.809423,4.55966,5.386411,5.12666,4.613175,5.213175,5.172122,5.59
권택현,4.395309,5.041288,7.0,4.604436,4.604436,4.304436,3.607078,3.084636,4.395407,4.457532,...,4.608964,4.304436,4.815309,4.395604,4.905016,4.605505,4.094436,4.694822,4.14256,4.441288
이재우,4.644518,5.177853,4.604436,7.0,6.4,5.743,4.19509,3.9232,4.423,5.023,...,4.697516,5.143,4.644518,4.403507,5.50064,4.622741,5.533,5.249751,5.237047,4.667853
정연우,4.944518,5.123175,4.604436,6.4,7.0,5.743,4.194577,3.9232,4.423,4.921193,...,4.695631,5.143,4.644518,4.403507,5.50064,4.613507,5.533,5.222342,5.230508,4.613175
문병식,4.644518,4.970175,4.304436,5.743,5.743,7.0,4.194577,4.0702,4.423,4.621193,...,5.442631,5.59,4.644518,4.403507,5.20064,4.760507,5.533,4.922342,5.677508,5.060175
이환목,4.346348,4.098632,3.607078,4.19509,4.194577,4.194577,7.0,3.434677,4.346902,3.77509,...,3.923083,4.017566,4.436348,3.628023,4.497717,3.901023,4.131577,3.897183,4.405768,3.889153
신재국,3.724718,4.213715,3.084636,3.9232,3.9232,4.0702,3.434677,7.0,3.4132,3.611393,...,3.622831,4.0702,3.424718,3.393707,3.68084,3.750707,3.7132,3.702542,3.721048,3.913715
박동현,5.89,4.794279,4.395407,4.423,4.423,4.423,4.346902,3.4132,7.0,4.077518,...,4.807018,4.423,5.17,5.013515,4.712342,5.431193,5.08,4.48064,4.3173,4.494279
정태암,4.090619,4.71266,4.457532,5.023,4.921193,4.621193,3.77509,3.611393,4.077518,7.0,...,4.130516,4.174193,4.810619,4.055741,4.802342,4.265741,4.411193,5.186751,4.22411,4.207953
조경순,5.12657,4.853678,4.608232,4.712231,5.012231,5.012231,3.917736,3.492431,4.82657,4.147587,...,5.767619,5.012231,4.82657,4.836695,4.871807,5.043176,4.502231,4.512123,4.89493,4.853678
배영훈,5.570477,4.749338,4.832226,4.612452,4.912452,4.312452,4.485274,3.302652,5.270593,4.255565,...,4.827799,4.312452,4.760477,4.760824,4.613133,4.823708,4.249452,4.402905,4.150833,4.149338
김병철,3.424718,4.003715,3.174636,3.7132,3.7132,3.8602,3.224677,5.59,3.4132,3.401393,...,3.412831,3.8602,3.214718,2.973707,3.77084,3.840707,4.0132,3.792542,3.511048,4.003715
정재중,4.87,4.509423,4.515309,4.944518,4.944518,4.944518,4.436348,3.424718,4.87,5.257619,...,4.504587,4.344518,5.8,4.713515,5.039751,4.776515,5.091518,4.712342,4.809423,4.299423
박성준,4.767579,5.406015,5.568116,5.266813,4.965576,4.665576,3.941254,3.445776,4.769046,4.401072,...,5.071735,4.665576,4.767579,4.562075,5.273348,4.982075,4.455576,5.061992,4.523529,4.806015
이동훈,4.980798,4.160318,4.337659,4.023638,4.023618,4.023618,3.970476,2.803818,4.980818,3.666638,...,4.624523,4.023618,4.470798,4.470858,4.023738,4.323858,4.170618,3.813718,3.860578,3.860338
홍종국,4.776515,4.759002,4.305114,5.482763,5.482763,5.482763,4.198256,3.662963,4.529751,4.62764,...,4.709945,4.882763,4.776515,4.48064,5.341193,4.712342,5.272763,5.343515,5.591178,4.549002
이지원,4.081718,4.066715,3.384636,4.2232,4.2232,3.9232,4.391677,5.443,4.0702,4.211393,...,3.475831,4.2232,3.871718,3.330707,3.98084,3.603707,3.8602,4.002542,3.574048,3.766715
정기동,4.224518,4.703175,4.751436,5.533,5.533,5.233,3.684577,3.7132,4.003,5.641193,...,4.275631,4.723,4.644518,4.193507,4.99064,4.193507,5.023,5.312342,4.720508,4.256175
정연규,4.649342,4.913175,4.814919,5.012342,5.012342,5.012342,4.134183,3.492542,4.62764,5.039751,...,4.49557,4.412342,5.279342,4.894619,5.533,4.972763,5.159342,5.233,4.759401,4.703175
김수창,4.944518,4.970175,4.094436,5.533,5.833,5.68,3.984577,3.8602,4.423,4.411193,...,4.632631,5.08,4.434518,4.193507,4.99064,4.550507,5.533,4.712342,5.377508,4.550175
김범철,4.613175,5.5,4.442264,4.750167,4.750167,4.597167,4.194048,3.750707,4.967853,4.599501,...,4.705783,4.556169,4.913175,4.55966,4.809423,5.12666,4.240167,4.647279,5.096751,5.29
양홍석,3.543542,4.216876,3.69699,3.759536,3.759535,3.606535,3.259982,3.054075,3.543542,3.521606,...,3.90057,3.802537,3.543542,3.753544,3.759539,3.900544,3.249535,3.656639,3.769886,4.336877
이어룡,3.939464,3.119103,3.074612,3.232015,3.232015,3.232015,3.176487,2.594566,4.086468,2.962018,...,3.429595,2.982436,3.219464,3.366475,3.232033,3.429475,3.379015,3.196735,3.068728,3.191133
김성원,4.734518,5.060175,4.394436,5.443,5.743,5.29,4.194577,4.2802,4.423,5.431193,...,4.632631,4.78,4.734518,4.193507,5.20064,4.760507,4.933,5.522342,4.784047,4.613175
나재철,3.499417,3.992233,3.905345,3.936304,3.936304,3.783304,2.943378,3.095434,3.646539,3.640707,...,4.007995,3.555334,3.499417,3.646784,3.936903,4.003661,3.426304,4.186362,3.621783,4.005133
이창세,3.424718,4.003715,3.174636,3.7132,3.7132,3.8602,3.224677,5.89,3.9232,3.401393,...,3.412831,4.1602,3.214718,2.973707,3.77084,3.540707,4.2232,3.792542,3.511048,4.003715
홍대한,4.804587,4.98311,4.608964,4.697516,4.695631,5.442631,3.923083,3.622831,4.807018,4.130516,...,7.0,5.142631,4.804587,4.812123,4.707726,5.169123,4.485631,4.49557,5.014129,4.985095
길기모,4.644518,5.019177,4.304436,5.143,5.143,5.59,4.017566,4.0702,4.423,4.174193,...,5.142631,7.0,4.644518,4.403507,4.60064,4.760507,4.933,4.412342,5.12651,5.019177
이정화,5.17,4.809423,4.815309,4.644518,4.644518,4.644518,4.436348,3.424718,5.17,4.810619,...,4.804587,4.644518,7.0,5.013515,4.739751,5.076515,4.791518,4.502342,4.509423,4.509423
송혁,4.976751,4.55966,4.395604,4.403507,4.403507,4.403507,3.628023,3.393707,5.013515,4.055741,...,4.812123,4.403507,5.013515,7.0,4.462763,5.533,4.340507,4.237619,4.366411,4.25966
이순남,4.739751,5.386411,4.905016,5.50064,5.50064,5.20064,4.497717,3.68084,4.712342,4.802342,...,4.707726,4.60064,4.739751,4.462763,7.0,4.90064,4.99064,5.641193,4.97966,4.876411
신인식,5.076515,5.12666,4.605505,4.622741,4.613507,4.760507,3.901023,3.750707,5.431193,4.265741,...,5.169123,4.760507,5.076515,5.533,4.90064,7.0,4.703507,4.657619,4.723411,4.82666
임민수,4.791518,4.613175,4.094436,5.533,5.533,5.533,4.131577,3.7132,5.08,4.411193,...,4.485631,4.933,4.791518,4.340507,4.99064,4.703507,7.0,4.712342,5.020508,4.403175
김상원,4.502342,5.213175,4.694822,5.249751,5.222342,4.922342,3.897183,3.702542,4.48064,5.186751,...,4.49557,4.412342,4.502342,4.237619,5.641193,4.657619,4.712342,7.0,4.669401,4.820853
이성근,4.509423,5.172122,4.14256,5.237047,5.230508,5.677508,4.405768,3.721048,4.3173,4.22411,...,5.014129,5.12651,4.509423,4.366411,4.97966,4.723411,5.020508,4.669401,7.0,5.052122
오익근,4.509423,5.59,4.441288,4.667853,4.613175,5.060175,3.889153,3.913715,4.494279,4.207953,...,4.985095,5.019177,4.509423,4.25966,4.876411,4.82666,4.403175,4.820853,5.052122,7.0

## 2020년

In [226]:
matrixs[6]

,김병철,오익근,이정화,진승욱,길기모,정재중,송혁,이재우,신인식,조경순,...,정연우,신재범,홍대한,이어룡,이지원,홍종국,양홍석,조홍희,강준규,문병식
김병철,7.0,3.479353,3.122721,3.7132,3.7132,3.779721,2.88677,3.364048,4.270376,3.184817,...,3.47084,3.320574,3.252275,3.249592,5.233,3.385322,3.202686,5.233,3.7132,3.332721
오익근,3.479353,7.0,3.787987,4.601148,4.181915,3.715957,3.832479,3.922267,4.001233,4.509501,...,3.916556,4.074885,4.469252,3.649512,3.536353,3.921082,3.765573,3.116353,3.913883,4.226593
이정화,3.122721,3.787987,7.0,4.741782,4.552521,5.443,4.462763,4.672763,5.012342,4.718597,...,4.577764,4.776515,4.817587,3.070535,3.632721,4.644518,3.539159,3.122721,4.909521,4.933
진승욱,3.7132,4.601148,4.741782,7.0,4.875662,4.450167,4.340411,5.0373,4.924424,4.757257,...,5.059002,4.784047,4.98311,3.117155,4.0702,4.786411,4.065491,3.3502,4.67966,4.651782
길기모,3.7132,4.181915,4.552521,4.875662,7.0,4.252521,4.16357,4.793848,4.533176,4.914617,...,4.90064,4.597374,5.129075,2.980462,4.3702,4.815122,3.651148,3.6502,4.843,5.062521
정재중,3.779721,3.715957,5.443,4.450167,4.252521,7.0,4.237619,4.99064,5.34764,4.417891,...,4.883848,5.039751,4.514807,3.677111,3.632721,4.944518,4.049159,3.122721,4.852521,5.233
송혁,2.88677,3.832479,4.462763,4.340411,4.16357,4.237619,7.0,4.17745,5.131193,4.423763,...,4.124227,4.949342,4.687374,3.289588,3.24377,4.163848,3.959163,3.03377,4.40657,4.252763
이재우,3.364048,3.922267,4.672763,5.0373,4.793848,4.99064,4.17745,7.0,4.613507,4.981473,...,5.732741,5.154518,4.709945,3.230094,3.874048,5.586515,3.755155,3.154048,5.093848,5.839763
신인식,4.270376,4.001233,5.012342,4.924424,4.533176,5.34764,5.131193,4.613507,7.0,4.932245,...,4.552521,5.076515,5.043176,4.084551,3.523376,4.59745,4.406162,2.893376,4.833176,4.712342
조경순,3.184817,4.509501,4.718597,4.757257,4.914617,4.417891,4.423763,4.981473,4.932245,7.0,...,4.917536,4.420032,5.556396,3.427889,3.394817,4.622506,3.749227,2.764817,4.404617,5.285597
김성원,3.492542,3.865591,4.809081,4.8273,4.412342,4.877764,3.973374,5.123507,4.54827,4.706942,...,5.743,4.771735,4.47854,3.194763,4.302542,4.854518,3.799248,3.282542,5.069342,4.782081
이순남,3.67765,4.221082,4.791518,5.386411,4.50745,4.944518,4.163848,5.586515,4.80745,4.622506,...,5.467619,5.123507,4.70557,3.230084,3.88765,5.443,3.755154,3.16765,5.25445,5.154518
강윤기,4.0132,4.060883,4.552521,5.33666,4.99,4.852521,4.25357,5.393848,4.833176,4.404617,...,5.50064,5.497374,4.619075,3.127141,4.3702,5.115122,3.755146,3.9502,5.743,5.062521
박성준,3.480943,4.626511,4.713811,5.353012,4.610743,4.413155,4.208597,5.366355,4.927193,5.314619,...,4.913485,4.625143,4.948297,3.280912,3.690943,4.618137,3.902231,2.970943,4.610743,4.770811
김범철,3.297787,4.417891,4.76966,5.419521,4.460249,4.549401,4.850175,4.720508,4.759002,4.471977,...,4.669836,4.641279,4.74193,3.189258,4.254787,4.403411,4.422505,3.234787,4.354247,4.46966
정연규,3.460587,4.083702,5.524619,5.149002,4.590387,5.167619,4.680387,4.831193,5.205122,4.713155,...,4.644518,4.922741,4.797726,3.070508,3.370587,4.831193,3.392155,3.160587,5.247387,4.657619
김호중,3.792542,4.079352,4.855741,4.90064,4.508004,4.714424,3.960887,4.969401,4.68493,4.244197,...,5.27966,5.208395,4.316909,2.963818,3.702542,4.991178,3.618488,3.582542,5.506002,4.918741
박현식,3.11847,3.420877,4.366,3.86711,3.68127,4.411193,4.02074,4.237619,3.962751,3.642311,...,4.152081,4.711193,3.743469,2.857216,3.11847,4.36,2.86023,3.41847,4.42827,4.513
임민수,4.0132,3.703883,4.699521,4.46966,4.933,4.647002,3.89657,5.183848,4.623176,4.404617,...,5.312342,4.844227,4.472075,3.230044,3.7132,5.205122,3.245146,3.5032,5.59,5.152521
김상원,3.475322,4.173838,4.67966,5.076515,4.190784,4.991178,4.300508,4.913175,4.73411,4.249166,...,4.794279,5.050167,4.33223,2.856744,3.385322,5.42666,3.408493,3.175322,5.041782,4.76966
정기동,3.401393,3.653988,4.557002,4.571178,4.621193,5.071735,3.962805,5.34445,4.116695,4.342768,...,5.339751,4.54827,4.265235,2.984753,3.911393,4.913507,3.442246,3.401393,4.831193,5.004002
나유석,3.02219,3.755564,4.693793,4.301391,4.15199,4.992,4.077726,4.920638,4.283474,4.400348,...,4.759355,5.08945,4.380387,2.917367,3.23219,4.769046,3.245189,3.32219,5.05199,4.930793
권택현,3.160085,3.977578,4.801409,5.027192,4.289885,4.501409,4.081928,4.737969,4.591779,4.746932,...,4.590244,4.291631,4.593828,3.073134,3.370085,4.290823,3.692643,2.860085,4.289885,4.438483
이창세,5.533,3.626353,3.122721,3.8602,4.1602,3.122721,3.03377,3.364048,3.313376,3.184817,...,3.47084,3.467574,3.399275,2.592592,5.89,3.385322,2.845686,5.68,3.7132,3.332721
김수창,3.611393,3.851409,4.347002,4.838178,4.978193,4.651735,4.046805,5.190387,4.326695,4.70519,...,5.612342,4.991227,4.620638,3.440044,3.758393,5.213507,3.245146,3.548393,5.131193,5.157002
최근영,3.5032,4.014223,4.599181,4.78,4.665662,4.899181,4.39023,4.720508,4.459836,4.031277,...,4.8273,5.424034,4.245735,2.753801,4.0702,4.741782,3.408486,4.1602,5.66966,4.689181
정연우,3.47084,3.916556,4.577764,5.059002,4.90064,4.883848,4.124227,5.732741,4.552521,4.917536,...,7.0,5.071735,4.690249,3.230061,3.98084,5.467619,3.755149,3.26084,5.20064,5.387764
신재범,3.320574,4.074885,4.776515,4.784047,4.597374,5.039751,4.949342,5.154518,5.076515,4.420032,...,5.071735,7.0,4.670461,3.127224,3.677574,5.123507,3.455161,3.557574,5.950374,5.286515
홍대한,3.252275,4.469252,4.817587,4.98311,5.129075,4.514807,4.687374,4.709945,5.043176,5.556396,...,4.690249,4.670461,7.0,3.427641,3.609275,4.70557,3.749179,2.979275,4.472075,5.327587
이어룡,3.249592,3.649512,3.070535,3.117155,2.980462,3.677111,3.289588,3.230094,4.084551,3.427889,...,3.230061,3.127224,3.427641,7.0,2.592592,3.230084,4.267366,2.279692,3.127141,3.230114
이지원,5.233,3.536353,3.632721,4.0702,4.3702,3.632721,3.24377,3.874048,3.523376,3.394817,...,3.98084,3.677574,3.609275,2.592592,7.0,3.595322,3.502686,5.38,3.9232,3.542721
홍종국,3.385322,3.921082,4.644518,4.786411,4.815122,4.944518,4.163848,5.586515,4.59745,4.622506,...,5.467619,5.123507,4.70557,3.230084,3.595322,7.0,3.455153,3.175322,5.115122,5.443
양홍석,3.202686,3.765573,3.539159,4.065491,3.651148,4.049159,3.959163,3.755155,4.406162,3.749227,...,3.755149,3.455161,3.749179,4.267366,3.502686,3.455153,7.0,2.335686,3.455146,3.455159
조홍희,5.233,3.116353,3.122721,3.3502,3.6502,3.122721,3.03377,3.154048,2.893376,2.764817,...,3.26084,3.557574,2.979275,2.279692,5.38,3.175322,2.335686,7.0,3.8032,3.122721
강준규,3.7132,3.913883,4.909521,4.67966,4.843,4.852521,4.40657,5.093848,4.833176,4.404617,...,5.20064,5.950374,4.472075,3.127141,3.9232,5.115122,3.455146,3.8032,7.0,5.062521
문병식,3.332721,4.226593,4.933,4.651782,5.062521,5.233,4.252763,5.839763,4.712342,5.285597,...,5.387764,5.286515,5.327587,3.230114,3.542721,5.443,3.455159,3.122721,5.062521,7.0

## 2021년

In [227]:
matrixs[7]

,이어룡,양홍석,강준규,김범철,김병철,이성영,원윤희,진승욱,이정훈,박정환,...,김호중,김창수,박성준,오익근,나유석,길기모,권택현,김수창,홍종국,송혁
이어룡,7.0,4.412007,3.124247,3.186544,2.589662,3.064265,2.933762,3.114343,2.788917,2.824211,...,3.011335,2.276762,3.278547,3.647128,2.914682,2.977605,3.070862,3.437208,3.227241,3.286841
양홍석,4.412007,7.0,3.34997,4.210265,2.543403,3.227523,2.990403,3.916232,3.026935,3.188965,...,3.616211,2.543403,3.753056,3.973395,3.140053,3.501879,3.54348,3.139982,3.349988,3.746917
강준규,3.124247,3.34997,7.0,4.264379,3.385322,4.99064,3.175322,4.548891,4.515122,4.605122,...,5.624853,3.385322,4.552409,3.857739,4.99659,4.523507,4.274177,4.861735,5.030469,4.020233
김범철,3.186544,4.210265,4.264379,7.0,3.345091,4.165685,2.988091,5.334579,4.003553,3.793553,...,4.638539,3.345091,4.711818,4.366057,4.106909,4.380011,4.415906,4.428989,4.294732,4.664047
김병철,2.589662,2.543403,3.385322,3.345091,7.0,3.703951,4.674805,3.704069,3.8602,3.7132,...,3.670587,5.031805,3.420084,3.567657,2.960584,3.471427,3.143718,3.442007,3.26965,2.935739
이성영,3.064265,3.227523,4.99064,4.165685,3.703951,7.0,3.436951,4.351467,4.923751,4.356751,...,4.702002,4.003951,4.196413,3.920038,4.189153,4.39064,3.917484,4.53445,4.840374,3.775429
원윤희,2.933762,2.990403,3.175322,2.988091,4.674805,3.436951,7.0,3.047069,3.8032,3.8032,...,3.160587,5.533,2.910084,2.910657,2.960584,3.114427,2.843718,3.085007,3.05965,2.641739
진승욱,3.114343,3.916232,4.548891,5.334579,3.704069,4.351467,3.047069,7.0,4.209531,4.062531,...,5.014587,3.404069,5.296963,4.548095,4.255257,4.775838,5.01282,4.760411,4.704279,4.265095
이정훈,2.788917,3.026935,4.515122,4.003553,3.8602,4.923751,3.8032,4.209531,7.0,5.233,...,4.176049,4.1602,4.039884,4.300768,4.090384,4.991227,3.763518,4.361807,4.39945,3.561539
박정환,2.824211,3.188965,4.605122,3.793553,3.7132,4.356751,3.8032,4.062531,5.233,7.0,...,4.176049,3.8032,4.186884,3.394189,4.327384,4.844227,3.910518,4.514807,4.48945,3.351539
정기동,3.638853,4.02494,4.933,4.207379,3.175322,4.69064,3.832322,4.428891,4.605122,4.095122,...,4.457853,3.385322,4.432409,3.597318,4.60659,4.403507,4.574177,4.651735,4.820469,3.873233
정연우,3.277653,3.752886,4.739805,4.80102,3.27577,4.40127,3.06577,5.269401,4.19557,4.19557,...,4.879836,3.27577,5.158057,3.935481,4.411863,5.087764,4.87563,5.244518,5.286515,4.263638
박현식,2.854319,2.807533,4.424227,3.616458,3.074787,4.656751,3.074787,3.860047,3.994587,3.994587,...,4.11793,3.074787,3.780183,3.356851,4.289355,3.738122,3.708419,4.292342,4.399763,3.797679
정연규,3.067714,3.242898,4.839,4.320453,3.333548,4.136474,3.033548,5.06966,3.953348,3.953348,...,4.769291,3.243548,4.952644,4.030125,4.636108,4.507018,5.086642,4.319805,4.577764,4.604807
이순남,3.227265,3.649993,5.154726,4.607205,3.555435,4.512123,3.045435,5.477853,4.385235,4.475235,...,4.695891,3.255435,5.160763,4.166191,4.720032,4.439805,4.876213,4.861735,5.154518,4.07557
이창세,3.246662,3.500403,3.385322,3.198091,5.533,3.346951,5.541805,3.557069,3.7132,4.0132,...,3.370587,4.674805,3.420084,3.420657,2.960584,3.624427,3.143718,3.295007,3.26965,2.788739
이정화,3.067699,3.389896,5.14645,4.613529,3.039246,4.445231,3.039246,4.8273,3.959046,3.959046,...,5.077134,3.249246,4.651696,3.729165,4.633,4.517587,4.786427,4.334227,4.605122,4.294587
김성원,3.227214,3.796983,5.209521,4.884139,3.289729,4.577764,3.079729,4.924424,4.419529,4.509529,...,4.750662,3.289729,4.856751,3.86213,4.708137,4.532741,4.575314,5.376515,5.154518,4.04473
김봉진,2.878917,3.367933,4.605122,4.197551,3.5032,4.866751,3.8032,4.403529,5.233,4.87,...,4.217047,4.0132,4.576884,3.594766,4.747384,4.034227,4.720518,4.304807,4.491435,3.714539
신재범,3.124338,3.349988,5.333461,4.440473,3.418635,4.691227,3.061635,4.838178,4.548435,4.491435,...,4.87323,3.418635,4.558499,4.010899,5.013155,4.623751,4.275735,5.069741,5.443,4.713869
이재우,3.277762,3.752907,4.668072,4.867129,3.223445,4.31773,3.013445,5.183355,4.143245,4.500245,...,4.806015,3.223445,5.613603,3.944137,4.587233,4.983638,5.024567,4.787516,5.022123,4.367764
김상원,3.227269,3.649993,5.007726,4.607205,3.553838,4.509529,3.043838,5.423175,4.383638,4.473638,...,4.546605,3.253838,5.160995,4.166191,4.720032,4.43657,4.876266,4.857002,5.5,4.077726
강윤기,3.124217,3.649964,5.432741,4.912971,3.703715,4.730848,3.346715,5.18566,4.833515,4.776515,...,4.960167,3.703715,4.850457,4.002765,4.991762,4.609521,4.573669,5.180461,5.00557,4.158063
임민수,3.227208,3.139982,5.218735,4.071989,3.595007,4.380387,3.295007,4.403411,4.214807,4.514807,...,4.850411,3.085007,4.346323,3.651697,4.496942,4.644518,4.06521,5.533,5.222741,3.831992
최근영,2.75108,3.303343,4.904239,4.439231,3.168034,4.250529,3.021034,4.713751,4.183496,4.126496,...,4.769046,3.378034,4.191496,3.970657,5.080345,4.218293,4.323844,4.575891,4.669836,4.407887
조홍희,2.276762,2.333403,3.475322,3.135091,5.59,3.493951,4.884805,3.194069,3.6502,3.5032,...,3.460587,5.541805,2.910084,3.057657,3.260584,3.261427,2.843718,3.232007,3.05965,2.935739
홍대한,4.081784,4.256911,4.449698,4.590887,3.217549,4.099813,3.454549,4.861467,4.227349,3.927349,...,4.58865,3.007549,4.868426,4.245986,4.237479,4.97473,4.577898,4.476869,4.707726,4.633
유창범,2.874632,3.291865,4.305122,4.003553,4.2232,4.209751,3.8032,4.362531,5.023,5.89,...,4.476049,3.8032,4.486884,3.466219,4.027384,5.144227,4.210518,4.214807,4.18945,3.561539
김호중,3.011335,3.616211,5.624853,4.638539,3.670587,4.702002,3.160587,5.014587,4.176049,4.176049,...,7.0,3.370587,4.689269,4.093311,4.533754,4.728662,4.410888,4.403411,4.57323,4.067882
김창수,2.276762,2.543403,3.385322,3.345091,5.031805,4.003951,5.533,3.404069,4.1602,3.8032,...,3.370587,7.0,3.120084,3.267657,3.170584,3.471427,3.053718,3.232007,3.26965,2.998739
박성준,3.278547,3.753056,4.552409,4.711818,3.420084,4.196413,2.910084,5.296963,4.039884,4.186884,...,4.689269,3.120084,7.0,4.663275,4.738917,4.554641,5.551217,4.346323,4.558721,4.151136
오익근,3.647128,3.973395,3.857739,4.366057,3.567657,3.920038,2.910657,4.548095,4.300768,3.394189,...,4.093311,3.267657,4.663275,7.0,3.687442,4.128028,3.970743,3.798697,3.864124,3.778353
나유석,2.914682,3.140053,4.99659,4.106909,2.960584,4.189153,2.960584,4.255257,4.090384,4.327384,...,4.533754,3.170584,4.738917,3.687442,7.0,4.102374,4.849126,4.496942,4.713811,4.038072
길기모,2.977605,3.501879,4.523507,4.380011,3.471427,4.39064,3.114427,4.775838,4.991227,4.844227,...,4.728662,3.471427,4.554641,4.128028,4.102374,7.0,4.274742,4.791518,4.771735,4.08899
권택현,3.070862,3.54348,4.274177,4.415906,3.143718,3.917484,2.843718,5.01282,3.763518,3.910518,...,4.410888,3.053718,5.551217,3.970743,4.849126,4.274742,7.0,4.06521,4.275735,4.068455
김수창,3.437208,3.139982,4.861735,4.428989,3.442007,4.53445,3.085007,4.760411,4.361807,4.514807,...,4.403411,3.232007,4.346323,3.798697,4.496942,4.791518,4.06521,7.0,5.222741,3.978992
홍종국,3.227241,3.349988,5.030469,4.294732,3.26965,4.840374,3.05965,4.704279,4.39945,4.48945,...,4.57323,3.26965,4.558721,3.864124,4.713811,4.771735,4.275735,5.222741,7.0,4.05854
송혁,3.286841,3.746917,4.020233,4.664047,2.935739,3.775429,2.641739,4.265095,3.561539,3.351539,...,4.067882,2.998739,4.151136,3.778353,4.038072,4.08899,4.068455,3.978992,4.05854,7.0

## 2022년

In [228]:
matrixs[8]

,박정환,강준규,최근영,이순남,김병철,이정화,최광철,이재우,길기모,김성호,...,김범철,이창세,신재범,김창수,송종원,박성준,김광혁,김경렬,원윤희,김호중
박정환,7.0,4.48945,4.094973,4.415819,3.7132,3.916909,4.933,4.420689,4.807018,3.7132,...,3.719277,4.0132,4.443245,3.8032,4.933,4.152505,4.723,4.723,3.8032,4.09268
강준규,4.48945,7.0,4.898652,4.96436,3.26965,4.776869,4.78945,4.58809,4.554518,3.26965,...,4.190025,3.26965,5.322123,3.26965,5.29945,4.519921,4.78945,4.78945,3.05965,5.291178
최근영,4.094973,4.898652,7.0,4.8273,3.136511,4.67966,4.492971,4.243012,4.183496,3.136511,...,4.307124,2.989511,5.266465,3.346511,4.702971,4.153589,4.912971,4.765971,2.989511,4.750834
이순남,4.415819,4.96436,4.8273,7.0,3.496019,4.583848,4.715819,4.919355,4.355329,3.196019,...,4.508761,3.496019,5.171807,3.196019,5.225819,5.127549,4.715819,5.162819,2.986019,4.638989
김병철,3.7132,3.26965,3.136511,3.496019,7.0,2.997109,4.0702,3.143889,3.434218,5.241805,...,3.270815,5.533,3.223445,5.031805,3.8602,3.385705,3.6502,3.5032,4.674805,3.587218
이정화,3.916909,4.776869,4.67966,4.583848,2.997109,7.0,4.006909,4.700743,4.463348,2.787109,...,4.503939,3.654109,4.572081,3.207109,4.516909,4.615713,4.426909,4.426909,3.654109,4.900008
최광철,4.933,4.78945,4.492971,4.715819,4.0702,4.006909,7.0,4.363689,4.354018,4.1602,...,3.907275,3.7132,4.743245,3.6502,5.68,4.305505,5.68,5.323,3.5032,4.343678
이재우,4.420689,4.58809,4.243012,4.919355,3.143889,4.700743,4.363689,7.0,4.885196,3.143889,...,4.783074,3.143889,4.601762,3.143889,4.573689,5.59216,4.363689,4.663689,2.933889,4.721504
길기모,4.807018,4.554518,4.183496,4.355329,3.434218,4.463348,4.354018,4.885196,7.0,3.434218,...,4.29389,3.587218,4.403474,3.434218,4.564018,4.51907,4.354018,4.207018,3.077218,5.028662
김성호,3.7132,3.26965,3.136511,3.196019,5.241805,2.787109,4.1602,3.143889,3.434218,7.0,...,3.060815,5.394805,3.223445,5.68,4.1602,3.085705,3.9502,3.8032,5.233,3.287218
송혁,3.271057,3.938691,4.241013,3.959592,2.855257,4.1638,3.928057,4.249355,3.993347,2.708257,...,4.630662,2.708257,4.248212,2.918257,3.928057,4.137183,4.138057,3.781057,2.561257,3.983007
김봉진,4.87,4.491435,4.466692,4.716502,3.5032,4.427719,4.723,4.60098,3.999529,3.5032,...,4.123479,3.5032,4.443245,4.0132,4.933,4.542505,5.143,5.443,3.8032,4.136189
정회민,3.787018,4.371518,3.86865,4.025329,3.077218,3.686348,4.387018,3.808196,4.066,3.377218,...,3.308221,3.077218,4.073474,3.077218,4.387018,3.74207,4.387018,4.387018,3.077218,4.20266
권택현,4.037476,4.102298,4.178294,4.705179,3.134016,4.614508,3.890476,4.857939,4.401961,2.834016,...,4.278736,3.134016,4.103715,3.044016,4.100517,5.391108,4.310476,4.910476,2.834016,4.265301
김수창,4.448579,4.82657,4.588467,4.802231,3.375779,4.33827,4.895579,4.689482,4.651587,3.375779,...,4.344243,3.228779,4.99064,3.165779,5.105579,4.313019,4.685579,4.538579,3.018779,4.341247
박석원,4.552521,4.84827,4.510074,4.731925,3.479721,4.026396,5.299521,4.370449,4.437387,3.779721,...,3.911717,3.332721,4.769046,3.269721,5.299521,4.307613,5.089521,4.942521,3.122721,4.43411
김성균,4.613507,5.024807,4.565199,5.233763,3.393707,4.373414,5.213507,4.877279,4.454227,3.693707,...,4.272557,3.540707,4.965576,3.393707,5.423507,4.816599,5.213507,5.513507,3.330707,4.590887
정연우,4.131925,4.695631,4.420508,5.067002,3.212125,4.99064,4.431925,5.507603,4.982075,3.212125,...,4.712116,3.212125,4.823507,3.212125,4.641925,5.124996,4.431925,4.731925,3.002125,4.818735
홍종국,4.437349,5.364726,4.689181,5.043176,3.217549,4.613507,4.737349,4.904613,4.692,3.217549,...,4.200349,3.217549,5.182763,3.217549,4.947349,4.52429,4.737349,4.737349,3.007549,4.52866
이정훈,4.866751,4.446695,4.166347,4.33937,3.493951,3.933245,4.413751,4.06948,5.019081,3.493951,...,3.933062,3.346951,4.37473,3.793951,4.623751,4.007307,4.413751,4.266751,3.436951,4.163426
오익근,3.34626,3.810617,3.916157,4.116269,3.519728,3.676956,3.744258,3.900584,4.078006,3.219728,...,4.324471,3.372728,3.813447,3.219728,3.954258,4.279458,3.744258,3.597258,2.862728,4.045344
김성원,4.443245,5.024807,4.666465,5.322123,3.223445,5.529081,4.533245,4.901762,4.403474,3.013445,...,4.798634,3.880445,5.443,3.223445,4.743245,4.823593,4.533245,4.833245,3.670445,4.540134
이성영,4.319805,4.883848,4.216905,4.438297,3.667005,4.39736,4.466805,4.225437,4.357619,3.667005,...,4.08338,3.310005,4.480249,3.967005,4.976805,4.161232,4.466805,4.319805,3.400005,4.647279
김상혁,4.87,3.97945,4.004973,3.905819,3.7132,3.706909,4.933,3.790689,4.087018,3.8032,...,3.152277,3.5032,3.933245,3.5032,4.723,3.942505,5.233,4.933,3.5032,3.67268
김상원,4.426108,4.983638,4.781178,5.85445,3.506308,4.831193,4.726108,4.911282,4.371992,3.206308,...,4.504248,3.506308,5.218735,3.206308,4.936108,5.125833,4.726108,5.173108,2.996308,4.655652
나유석,4.275943,4.947618,5.009485,4.664272,2.909143,4.570036,4.428943,4.564193,4.045897,2.909143,...,4.167034,2.909143,4.955587,3.119143,4.638943,4.714899,4.848943,4.848943,2.909143,4.482557
이어룡,2.822074,3.122196,2.749029,3.225283,2.587525,3.722661,3.122074,3.276047,2.975494,2.484625,...,3.184977,3.244525,3.122289,2.274625,3.122074,3.277092,2.912074,2.912074,2.931625,3.009254
양홍석,3.187887,3.34891,3.302284,3.648946,2.542325,4.045838,3.138885,3.751913,3.500807,2.542325,...,4.2093,3.499325,3.348928,2.542325,3.348885,3.752114,3.138885,3.438885,2.989325,3.615145
최대경,4.933,4.99945,4.555971,5.372819,3.7132,4.216909,5.533,4.873689,4.417018,4.0132,...,4.570275,3.7132,5.100245,3.7132,5.743,4.815505,5.533,5.98,3.5032,4.910678
임민수,4.459355,4.861735,4.420134,4.930793,3.539555,4.307587,4.759355,4.685582,4.529805,3.749555,...,3.984822,3.749555,5.247387,3.029555,4.759355,4.312002,4.549355,4.906355,3.239555,4.813465
정연규,3.913763,4.470544,5.019423,5.060507,3.293963,5.249751,4.213763,4.702374,4.459355,2.993963,...,4.204872,3.293963,5.209521,3.203963,4.423763,4.916196,4.633763,4.990763,2.993963,4.743015
강윤기,4.514807,5.432741,5.032239,5.253245,3.442007,4.460661,4.961807,4.884146,4.833515,3.442007,...,4.844423,3.295007,5.297516,3.442007,5.381807,4.818754,4.961807,5.114807,3.085007,5.123175
김범철,3.719277,4.190025,4.307124,4.508761,3.270815,4.503939,3.907275,4.783074,4.29389,3.060815,...,7.0,3.123815,4.198634,3.270815,4.327275,4.698591,3.907275,4.060275,2.913815,4.561228
이창세,4.0132,3.26965,2.989511,3.496019,5.533,3.654109,3.7132,3.143889,3.587218,5.394805,...,3.123815,7.0,3.223445,4.674805,3.7132,3.385705,3.5032,3.5032,5.541805,3.287218
신재범,4.443245,5.322123,5.266465,5.171807,3.223445,4.572081,4.743245,4.601762,4.403474,3.223445,...,4.198634,3.223445,7.0,3.223445,4.953245,4.523593,4.743245,5.100245,3.013445,4.987134
김창수,3.8032,3.26965,3.346511,3.196019,5.031805,3.207109,3.6502,3.143889,3.434218,5.68,...,3.270815,4.674805,3.223445,7.0,3.8602,3.085705,3.8602,3.7132,5.533,3.287218
송종원,4.933,5.29945,4.702971,5.225819,3.8602,4.516909,5.68,4.573689,4.564018,4.1602,...,4.327275,3.7132,4.953245,3.8602,7.0,4.515505,5.68,5.533,3.5032,4.853678
박성준,4.152505,4.519921,4.153589,5.127549,3.385705,4.615713,4.305505,5.59216,4.51907,3.085705,...,4.698591,3.385705,4.523593,3.085705,4.515505,7.0,4.305505,4.605505,2.875705,4.65573
김광혁,4.723,4.78945,4.912971,4.715819,3.6502,4.426909,5.68,4.363689,4.354018,3.9502,...,3.907275,3.5032,4.743245,3.8602,5.68,4.305505,7.0,5.743,3.5032,4.343678
김경렬,4.723,4.78945,4.765971,5.162819,3.5032,4.426909,5.323,4.663689,4.207018,3.8032,...,4.060275,3.5032,5.100245,3.7132,5.533,4.605505,5.743,7.0,3.5032,4.490678
원윤희,3.8032,3.05965,2.989511,2.986019,4.674805,3.654109,3.5032,2.933889,3.077218,5.233,...,2.913815,5.541805,3.013445,5.533,3.5032,2.875705,3.5032,3.5032,7.0,3.077218
김호중,4.09268,5.291178,4.750834,4.638989,3.587218,4.900008,4.343678,4.721504,5.028662,3.287218,...,4.561228,3.287218,4.987134,3.287218,4.853678,4.65573,4.343678,4.490678,3.077218,7.0

## 2023년

In [229]:
matrixs[9]

,김봉진,김성호,양홍석,강준규,최근영,권택현,신재범,정회민,이순남,박석원,...,윤태림,이정훈,김수창,김상원,이어룡,홍종국,길기모,김범철,김성균,한승희
김봉진,7.0,3.5032,3.438886,4.773638,4.747942,4.773412,5.090685,4.087018,5.156973,4.538579,...,4.513,4.52657,4.529258,5.166311,2.912074,4.72937,4.197726,4.262874,5.213507,3.7132
김성호,3.5032,7.0,2.542325,3.252275,3.117943,2.833572,3.213885,3.377218,3.190173,3.674679,...,3.8602,3.450661,3.365497,3.198797,2.484625,3.208739,3.424926,3.053414,3.685322,5.331805
양홍석,3.438886,2.542325,7.0,3.348915,3.3023,3.542505,3.348934,2.806454,3.648951,3.138926,...,2.913534,3.025874,3.138931,3.648944,4.411096,3.348937,3.500809,4.209322,3.795892,2.439425
강준규,4.773638,3.252275,3.348915,7.0,4.875918,4.265596,5.322123,4.299081,4.965576,4.861735,...,4.262075,4.450374,4.82657,4.985235,3.122224,5.364726,4.50745,4.183196,5.00557,3.252275
최근영,4.747942,3.117943,3.3023,4.875918,7.0,4.315814,5.21866,3.840423,4.720508,4.534321,...,3.964403,4.151259,4.547298,4.660121,2.749114,4.630134,4.159571,4.304279,4.544797,3.327943
권택현,4.773412,2.833572,3.542505,4.265596,4.315814,7.0,4.267012,3.697842,4.868429,4.056405,...,3.696372,3.754552,4.056794,4.867803,3.069206,4.267274,4.265009,4.417002,4.563897,3.043572
신재범,5.090685,3.213885,3.348934,5.322123,5.21866,4.267012,7.0,4.056869,5.171807,4.890387,...,4.223685,4.37614,4.99064,5.223751,3.122317,5.20064,4.393793,4.190756,4.955329,3.213885
정회민,4.087018,3.377218,2.806454,4.299081,3.840423,3.697842,4.056869,7.0,4.016414,4.594587,...,4.597018,4.162763,4.065631,4.030834,2.852172,4.194579,3.872751,3.299769,4.424227,3.077218
이순남,5.156973,3.190173,3.648951,4.965576,4.720508,4.868429,5.171807,4.016414,7.0,4.783793,...,4.199973,4.341063,4.802231,5.85445,3.225308,5.043176,4.350233,4.499485,5.227891,3.190173
박석원,4.538579,3.674679,3.138926,4.861735,4.534321,4.056405,4.890387,4.594587,4.783793,7.0,...,4.384479,4.33645,5.091518,4.814807,3.122278,5.161735,4.361807,3.914423,5.361992,3.164679
박정환,4.866515,3.519951,3.187889,4.476869,4.078036,3.900493,4.436414,3.794807,4.411863,4.450834,...,4.229751,4.833176,4.441222,4.421499,2.822083,4.431063,4.804587,3.712411,4.633,3.309951
송혁,3.774229,2.701235,3.745967,3.932644,4.239925,4.068793,4.241136,3.531599,3.950776,3.727377,...,3.461135,3.480183,3.876765,3.94636,3.285355,3.942825,3.986394,4.606836,3.776615,2.911235
강윤기,5.093474,3.418635,3.648909,5.432741,5.01303,4.565134,5.297516,4.252763,5.253245,4.967469,...,4.428435,4.65445,5.156945,5.269355,3.122193,4.986869,4.833515,4.837889,5.330469,3.418635
김창수,4.0132,5.023,3.199325,3.252275,3.180943,3.043572,3.213885,3.077218,3.190173,3.017679,...,3.5032,3.603661,3.008497,3.198797,2.931625,3.208739,3.277926,3.116414,3.532322,5.094805
이재우,4.661693,3.141614,3.751918,4.588836,4.257422,5.021075,4.602698,3.805437,4.919973,4.386427,...,4.004414,4.070449,4.690384,4.911825,3.27607,4.905594,4.8838,4.759166,4.875158,3.141614
최광철,4.921193,4.058393,3.138886,4.775235,4.475486,4.053452,4.734583,4.389529,4.710597,5.196698,...,4.978193,4.376805,4.887233,4.720032,3.122077,4.730211,4.346945,3.900052,5.222741,3.548393
김상혁,4.357619,3.527819,2.605861,3.975631,3.990852,4.110694,3.931222,4.319805,3.905143,4.246813,...,4.357619,4.642521,3.936396,3.914536,2.576802,3.925492,4.097587,3.146314,4.502342,3.227819
송종원,4.99064,3.899963,3.348888,5.292,4.687708,4.263614,4.949258,4.403461,5.223811,5.20136,...,4.609763,4.601227,5.101279,4.933,3.122091,4.943685,4.569123,4.320949,5.482763,3.599963
박성준,4.597699,3.077815,3.752163,4.512363,4.147121,5.561148,4.515505,3.733729,5.118754,4.304148,...,3.940615,4.000196,4.305016,5.117307,3.277352,4.516099,4.511087,4.688476,4.808717,3.077815
이성영,4.619805,3.66377,3.22645,4.836695,4.191551,3.907511,4.46473,4.747619,4.430211,4.724516,...,4.97357,5.188193,4.409075,4.442226,3.062152,4.756813,4.313507,4.075184,4.883848,3.66377
박성희,5.233,3.7132,3.245985,4.982075,4.537403,4.410372,4.943685,4.087018,4.919973,4.747479,...,5.023,4.433461,4.738297,4.928597,3.122074,4.938539,4.407726,3.962874,5.115122,4.0132
나유석,4.838615,2.898661,3.139108,4.93747,5.001249,4.850107,4.943819,3.914297,4.650763,4.431035,...,3.908461,4.033279,4.432809,4.647618,2.913216,4.645057,4.034986,4.110453,4.630496,3.108661
정연우,4.723763,3.2032,3.75184,4.695631,4.343678,4.867538,4.815122,3.891072,5.071735,4.533176,...,4.066,4.150834,5.172081,5.20064,3.275675,5.182763,4.973348,4.704037,4.943685,3.2032
조선영,3.7132,4.884805,3.306425,3.462275,3.180943,3.043572,3.423885,3.077218,3.400173,3.227679,...,4.0132,3.513661,3.218497,3.408797,3.141625,3.418739,3.487926,3.116414,3.742322,5.340344
원윤희,3.8032,5.59,2.332325,3.042275,3.117943,2.833572,3.003885,3.077218,2.980173,3.164679,...,3.6502,3.540661,3.155497,2.988797,2.274625,2.998739,3.214926,3.053414,3.175322,5.241805
임민수,4.90136,3.743365,3.138923,4.890387,4.38102,4.056191,5.218735,4.097587,4.922235,4.99064,...,4.243165,4.199945,5.19745,4.949231,3.225163,5.136695,4.529805,3.97628,4.769046,3.023365
오익근,3.597258,3.219728,3.97254,3.811432,3.918932,3.987547,3.814225,3.304338,4.117185,3.75002,...,3.658542,4.255078,3.750791,4.115907,3.646134,3.81475,4.078407,4.330496,3.808172,3.219728
김광혁,5.443,3.9502,3.138886,4.773638,4.894942,4.473412,4.733685,4.387018,4.709973,4.985579,...,4.66,4.37357,4.676258,4.719311,2.912074,4.72937,4.344726,3.899874,5.213507,3.8602
정연규,4.987762,2.990232,3.241843,4.476869,4.867129,5.077759,5.234764,3.886165,5.030848,4.310469,...,3.853032,3.935329,4.33827,5.278193,3.065687,4.622741,4.458072,4.195086,4.42937,3.200232
최대경,5.68,4.0132,3.648886,4.983638,4.537942,4.563412,5.090685,4.387018,5.366973,5.048579,...,4.723,4.43657,4.739258,5.376311,3.122074,4.93937,4.407726,4.562874,5.723507,3.7132
윤태림,4.513,3.8602,2.913534,4.262075,3.964403,3.696372,4.223685,4.597018,4.199973,4.384479,...,7.0,4.580461,4.375297,4.208597,3.062073,4.218539,3.987726,3.649974,4.395122,3.9502
이정훈,4.52657,3.450661,3.025874,4.450374,4.151259,3.754552,4.37614,4.162763,4.341063,4.33645,...,4.580461,7.0,4.320638,4.354279,2.786861,4.368072,5.069741,3.927282,4.487764,3.450661
김수창,4.529258,3.365497,3.138931,4.82657,4.547298,4.056794,4.99064,4.065631,4.802231,5.091518,...,4.375297,4.320638,7.0,4.844227,3.435203,5.213507,4.640474,4.336543,4.75199,3.155497
김상원,5.166311,3.198797,3.648944,4.985235,4.660121,4.867803,5.223751,4.030834,5.85445,4.814807,...,4.208597,4.354279,4.844227,7.0,3.225271,5.115122,4.365576,4.495618,5.238539,3.198797
이어룡,2.912074,2.484625,4.411096,3.122224,2.749114,3.069206,3.122317,2.852172,3.225308,3.122278,...,3.062073,2.786861,3.435203,3.225271,7.0,3.225234,2.975505,3.18509,3.269108,2.274625
홍종국,4.72937,3.208739,3.348937,5.364726,4.630134,4.267274,5.20064,4.194579,5.043176,5.161735,...,4.218539,4.368072,5.213507,5.115122,3.225234,7.0,4.683638,4.192247,5.249258,3.208739
길기모,4.197726,3.424926,3.500809,4.50745,4.159571,4.265009,4.393793,3.872751,4.350233,4.361807,...,3.987726,5.069741,4.640474,4.365576,2.975505,4.683638,7.0,4.286277,4.439805,3.424926
김범철,4.262874,3.053414,4.209322,4.183196,4.304279,4.417002,4.190756,3.299769,4.499485,3.914423,...,3.649974,3.927282,4.336543,4.495618,3.18509,4.192247,4.286277,7.0,4.265046,3.053414
김성균,5.213507,3.685322,3.795892,5.00557,4.544797,4.563897,4.955329,4.424227,5.227891,5.361992,...,4.395122,4.487764,4.75199,5.238539,3.269108,5.249258,4.439805,4.265046,7.0,3.385322
한승희,3.7132,5.331805,2.439425,3.252275,3.327943,3.043572,3.213885,3.077218,3.190173,3.164679,...,3.9502,3.450661,3.155497,3.198797,2.274625,3.208739,3.424926,3.053414,3.385322,7.0

중요인물 행만 뽑아서 네트워크 만들면 될듯..? 아마도..?

# 가중치 행렬 스케일 조정

In [254]:
# 인물 가중치행렬
col = []
row = []
matrixs = []
dataFrames = [df_2014, df_2015, df_2016, df_2017, df_2018, df_2019, df_2020, df_2021, df_2022, df_2023]

for dataframe in dataFrames:
  for i in range(len(dataframe)):
      col.append(dataframe.loc[i, '이름'])
      row.append(dataframe.loc[i, '이름'])
  weight_matrix = pd.DataFrame(columns=col, index=row)
  matrixs.append(weight_matrix)
  col=[]
  row=[]

In [255]:
#가중치 계산
for t, dataframe in enumerate(dataFrames):
  for i in range(0, len(dataframe)):
    for j in range(0, len(dataframe)):
      matrixs[t].iloc[i, j] = weight_sum(dataframe.iloc[i], dataframe.iloc[j])

In [256]:
matrixs[6]

,김병철,오익근,이정화,진승욱,길기모,정재중,송혁,이재우,신인식,조경순,...,정연우,신재범,홍대한,이어룡,이지원,홍종국,양홍석,조홍희,강준규,문병식
김병철,7.0,3.479353,3.122721,3.7132,3.7132,3.779721,2.88677,3.364048,4.270376,3.184817,...,3.47084,3.320574,3.252275,3.249592,5.233,3.385322,3.202686,5.233,3.7132,3.332721
오익근,3.479353,7.0,3.787987,4.601148,4.181915,3.715957,3.832479,3.922267,4.001233,4.509501,...,3.916556,4.074885,4.469252,3.649512,3.536353,3.921082,3.765573,3.116353,3.913883,4.226593
이정화,3.122721,3.787987,7.0,4.741782,4.552521,5.443,4.462763,4.672763,5.012342,4.718597,...,4.577764,4.776515,4.817587,3.070535,3.632721,4.644518,3.539159,3.122721,4.909521,4.933
진승욱,3.7132,4.601148,4.741782,7.0,4.875662,4.450167,4.340411,5.0373,4.924424,4.757257,...,5.059002,4.784047,4.98311,3.117155,4.0702,4.786411,4.065491,3.3502,4.67966,4.651782
길기모,3.7132,4.181915,4.552521,4.875662,7.0,4.252521,4.16357,4.793848,4.533176,4.914617,...,4.90064,4.597374,5.129075,2.980462,4.3702,4.815122,3.651148,3.6502,4.843,5.062521
정재중,3.779721,3.715957,5.443,4.450167,4.252521,7.0,4.237619,4.99064,5.34764,4.417891,...,4.883848,5.039751,4.514807,3.677111,3.632721,4.944518,4.049159,3.122721,4.852521,5.233
송혁,2.88677,3.832479,4.462763,4.340411,4.16357,4.237619,7.0,4.17745,5.131193,4.423763,...,4.124227,4.949342,4.687374,3.289588,3.24377,4.163848,3.959163,3.03377,4.40657,4.252763
이재우,3.364048,3.922267,4.672763,5.0373,4.793848,4.99064,4.17745,7.0,4.613507,4.981473,...,5.732741,5.154518,4.709945,3.230094,3.874048,5.586515,3.755155,3.154048,5.093848,5.839763
신인식,4.270376,4.001233,5.012342,4.924424,4.533176,5.34764,5.131193,4.613507,7.0,4.932245,...,4.552521,5.076515,5.043176,4.084551,3.523376,4.59745,4.406162,2.893376,4.833176,4.712342
조경순,3.184817,4.509501,4.718597,4.757257,4.914617,4.417891,4.423763,4.981473,4.932245,7.0,...,4.917536,4.420032,5.556396,3.427889,3.394817,4.622506,3.749227,2.764817,4.404617,5.285597
김성원,3.492542,3.865591,4.809081,4.8273,4.412342,4.877764,3.973374,5.123507,4.54827,4.706942,...,5.743,4.771735,4.47854,3.194763,4.302542,4.854518,3.799248,3.282542,5.069342,4.782081
이순남,3.67765,4.221082,4.791518,5.386411,4.50745,4.944518,4.163848,5.586515,4.80745,4.622506,...,5.467619,5.123507,4.70557,3.230084,3.88765,5.443,3.755154,3.16765,5.25445,5.154518
강윤기,4.0132,4.060883,4.552521,5.33666,4.99,4.852521,4.25357,5.393848,4.833176,4.404617,...,5.50064,5.497374,4.619075,3.127141,4.3702,5.115122,3.755146,3.9502,5.743,5.062521
박성준,3.480943,4.626511,4.713811,5.353012,4.610743,4.413155,4.208597,5.366355,4.927193,5.314619,...,4.913485,4.625143,4.948297,3.280912,3.690943,4.618137,3.902231,2.970943,4.610743,4.770811
김범철,3.297787,4.417891,4.76966,5.419521,4.460249,4.549401,4.850175,4.720508,4.759002,4.471977,...,4.669836,4.641279,4.74193,3.189258,4.254787,4.403411,4.422505,3.234787,4.354247,4.46966
정연규,3.460587,4.083702,5.524619,5.149002,4.590387,5.167619,4.680387,4.831193,5.205122,4.713155,...,4.644518,4.922741,4.797726,3.070508,3.370587,4.831193,3.392155,3.160587,5.247387,4.657619
김호중,3.792542,4.079352,4.855741,4.90064,4.508004,4.714424,3.960887,4.969401,4.68493,4.244197,...,5.27966,5.208395,4.316909,2.963818,3.702542,4.991178,3.618488,3.582542,5.506002,4.918741
박현식,3.11847,3.420877,4.366,3.86711,3.68127,4.411193,4.02074,4.237619,3.962751,3.642311,...,4.152081,4.711193,3.743469,2.857216,3.11847,4.36,2.86023,3.41847,4.42827,4.513
임민수,4.0132,3.703883,4.699521,4.46966,4.933,4.647002,3.89657,5.183848,4.623176,4.404617,...,5.312342,4.844227,4.472075,3.230044,3.7132,5.205122,3.245146,3.5032,5.59,5.152521
김상원,3.475322,4.173838,4.67966,5.076515,4.190784,4.991178,4.300508,4.913175,4.73411,4.249166,...,4.794279,5.050167,4.33223,2.856744,3.385322,5.42666,3.408493,3.175322,5.041782,4.76966
정기동,3.401393,3.653988,4.557002,4.571178,4.621193,5.071735,3.962805,5.34445,4.116695,4.342768,...,5.339751,4.54827,4.265235,2.984753,3.911393,4.913507,3.442246,3.401393,4.831193,5.004002
나유석,3.02219,3.755564,4.693793,4.301391,4.15199,4.992,4.077726,4.920638,4.283474,4.400348,...,4.759355,5.08945,4.380387,2.917367,3.23219,4.769046,3.245189,3.32219,5.05199,4.930793
권택현,3.160085,3.977578,4.801409,5.027192,4.289885,4.501409,4.081928,4.737969,4.591779,4.746932,...,4.590244,4.291631,4.593828,3.073134,3.370085,4.290823,3.692643,2.860085,4.289885,4.438483
이창세,5.533,3.626353,3.122721,3.8602,4.1602,3.122721,3.03377,3.364048,3.313376,3.184817,...,3.47084,3.467574,3.399275,2.592592,5.89,3.385322,2.845686,5.68,3.7132,3.332721
김수창,3.611393,3.851409,4.347002,4.838178,4.978193,4.651735,4.046805,5.190387,4.326695,4.70519,...,5.612342,4.991227,4.620638,3.440044,3.758393,5.213507,3.245146,3.548393,5.131193,5.157002
최근영,3.5032,4.014223,4.599181,4.78,4.665662,4.899181,4.39023,4.720508,4.459836,4.031277,...,4.8273,5.424034,4.245735,2.753801,4.0702,4.741782,3.408486,4.1602,5.66966,4.689181
정연우,3.47084,3.916556,4.577764,5.059002,4.90064,4.883848,4.124227,5.732741,4.552521,4.917536,...,7.0,5.071735,4.690249,3.230061,3.98084,5.467619,3.755149,3.26084,5.20064,5.387764
신재범,3.320574,4.074885,4.776515,4.784047,4.597374,5.039751,4.949342,5.154518,5.076515,4.420032,...,5.071735,7.0,4.670461,3.127224,3.677574,5.123507,3.455161,3.557574,5.950374,5.286515
홍대한,3.252275,4.469252,4.817587,4.98311,5.129075,4.514807,4.687374,4.709945,5.043176,5.556396,...,4.690249,4.670461,7.0,3.427641,3.609275,4.70557,3.749179,2.979275,4.472075,5.327587
이어룡,3.249592,3.649512,3.070535,3.117155,2.980462,3.677111,3.289588,3.230094,4.084551,3.427889,...,3.230061,3.127224,3.427641,7.0,2.592592,3.230084,4.267366,2.279692,3.127141,3.230114
이지원,5.233,3.536353,3.632721,4.0702,4.3702,3.632721,3.24377,3.874048,3.523376,3.394817,...,3.98084,3.677574,3.609275,2.592592,7.0,3.595322,3.502686,5.38,3.9232,3.542721
홍종국,3.385322,3.921082,4.644518,4.786411,4.815122,4.944518,4.163848,5.586515,4.59745,4.622506,...,5.467619,5.123507,4.70557,3.230084,3.595322,7.0,3.455153,3.175322,5.115122,5.443
양홍석,3.202686,3.765573,3.539159,4.065491,3.651148,4.049159,3.959163,3.755155,4.406162,3.749227,...,3.755149,3.455161,3.749179,4.267366,3.502686,3.455153,7.0,2.335686,3.455146,3.455159
조홍희,5.233,3.116353,3.122721,3.3502,3.6502,3.122721,3.03377,3.154048,2.893376,2.764817,...,3.26084,3.557574,2.979275,2.279692,5.38,3.175322,2.335686,7.0,3.8032,3.122721
강준규,3.7132,3.913883,4.909521,4.67966,4.843,4.852521,4.40657,5.093848,4.833176,4.404617,...,5.20064,5.950374,4.472075,3.127141,3.9232,5.115122,3.455146,3.8032,7.0,5.062521
문병식,3.332721,4.226593,4.933,4.651782,5.062521,5.233,4.252763,5.839763,4.712342,5.285597,...,5.387764,5.286515,5.327587,3.230114,3.542721,5.443,3.455159,3.122721,5.062521,7.0

In [259]:
#가중치 계산
for t, dataframe in enumerate(dataFrames):
  for i in range(0, len(dataframe)):
    for j in range(0, len(dataframe)):
      matrixs[t].iloc[i, j] = math.log2(1+ weight_sum(dataframe.iloc[i], dataframe.iloc[j])**3)

In [260]:
matrixs[6]

,김병철,오익근,이정화,진승욱,길기모,정재중,송혁,이재우,신인식,조경순,...,정연우,신재범,홍대한,이어룡,이지원,홍종국,양홍석,조홍희,강준규,문병식
김병철,8.426265,5.430308,4.975028,5.705897,5.705897,5.781312,4.647126,5.288001,6.301498,5.057614,...,5.419952,5.233173,5.145688,5.142217,7.172947,5.314593,5.081108,7.172947,5.705897,5.248559
오익근,5.430308,8.426265,5.790596,6.620717,6.212084,5.709047,5.840238,5.938776,6.023681,6.534551,...,5.932572,6.101444,6.496172,5.63249,5.499045,5.93749,5.765378,4.966474,5.929667,6.257468
이정화,4.975028,5.790596,8.426265,6.749756,6.575207,7.342125,6.489953,6.686899,6.987866,6.728741,...,6.598891,6.781054,6.817778,4.904463,5.612936,6.660915,5.502402,4.975028,6.898887,6.919364
진승욱,5.705897,6.620717,6.749756,8.426265,6.869188,6.477856,6.371031,7.009195,6.911896,6.763728,...,7.027658,6.787811,6.962752,4.967552,6.096538,6.78993,6.091601,5.270608,6.693221,6.667612
길기모,5.705897,6.212084,6.575207,6.869188,8.426265,6.283594,6.193314,6.796589,6.556971,6.903339,...,6.891117,6.617202,7.086748,4.780095,6.40028,6.815582,5.63439,5.633289,6.840348,7.030645
정재중,5.781312,5.709047,7.342125,6.477856,6.283594,8.426265,6.268597,6.969235,7.26611,6.446709,...,6.876387,7.011285,6.539586,5.664447,5.612936,6.929375,6.074436,4.975028,6.848775,7.172947
송혁,4.647126,5.840238,6.489953,6.371031,6.193314,6.268597,8.426265,6.207523,7.088523,6.452392,...,6.152792,6.933561,6.700281,5.19369,5.134676,6.193599,5.978648,4.8541,6.435731,6.283837
이재우,5.288001,5.938776,6.686899,7.009195,6.796589,6.969235,6.207523,8.426265,6.632209,6.961341,...,7.565313,7.108009,6.720873,5.116914,5.886127,7.454097,5.753609,5.016876,7.057142,7.644956
신인식,6.301498,6.023681,6.987866,6.911896,6.556971,7.26611,7.088523,6.632209,8.426265,6.918708,...,6.575207,7.042501,7.014202,6.11155,5.483488,6.617273,6.435335,4.656626,6.831637,6.723054
조경순,5.057614,6.534551,6.728741,6.763728,6.903339,6.446709,6.452392,6.961341,6.918708,8.426265,...,6.905889,6.448782,7.430834,5.367341,5.326412,6.640558,5.746897,4.468247,6.433834,7.215936
김성원,5.446306,5.876829,6.810197,6.826418,6.441332,6.871038,5.993911,7.082082,6.571206,6.718138,...,7.57301,6.77676,6.505057,5.070706,6.333569,6.85054,5.803213,5.184664,7.036428,6.786048
이순남,5.66507,6.251895,6.794504,7.297175,6.532603,6.929375,6.193599,7.454097,6.808742,6.640558,...,7.361537,7.082082,6.716889,5.116901,5.901042,7.342125,5.753607,5.03493,7.19053,7.108009
강윤기,6.036409,6.086765,6.575207,7.257272,6.968684,6.848775,6.284648,7.303109,6.831637,6.433834,...,7.387441,7.384886,6.637377,4.980955,6.40028,7.075045,5.753598,5.968995,7.57301,7.030645
박성준,5.43224,6.64427,6.72439,7.270428,6.629641,6.44212,6.239243,7.281133,6.914309,7.239478,...,6.902351,6.643002,6.932654,5.182573,5.680379,6.636507,5.916975,4.766756,6.629641,6.775929
김범철,5.20417,6.446709,6.774894,7.323531,6.487541,6.572271,6.8467,6.730477,6.765301,6.498781,...,6.684214,6.657925,6.74989,5.063465,6.285871,6.432663,6.451175,5.123017,6.384641,6.496562
정연규,5.407449,6.110663,7.406155,7.103408,6.610686,7.118916,6.693887,6.829877,7.14999,6.723794,...,6.660915,6.910429,6.800057,4.904427,5.296192,6.829877,5.323102,5.025564,7.184748,6.672986
김호중,5.795704,6.106117,6.851621,6.891117,6.533129,6.724948,5.980502,6.950925,6.698045,6.275223,...,7.211105,7.152692,6.347819,4.756746,5.693695,6.969698,5.596295,5.553991,7.391633,6.90694
박현식,4.969319,5.358695,6.396168,5.878501,5.669243,6.440218,6.044409,6.268597,5.982507,5.624114,...,6.181519,6.722009,5.74037,4.604392,4.969319,6.390287,4.608767,5.355722,6.456748,6.537871
임민수,6.036409,5.695232,6.711375,6.496562,6.919364,6.663206,5.910795,7.13239,6.64118,6.433834,...,7.237635,6.841435,6.498874,5.116849,5.705897,7.14999,5.136459,5.459192,7.456781,7.106344
김상원,5.425407,6.20383,6.693221,7.042501,6.22113,6.969698,6.331547,6.902081,6.742814,6.280222,...,6.796974,7.020151,6.362965,4.603706,5.314593,7.329193,5.343382,5.045081,7.013014,6.774894
정기동,5.334581,5.637688,6.57942,6.592724,6.639342,7.038455,5.982564,7.263545,6.144992,6.373353,...,7.259762,6.571206,6.29635,4.786095,5.926958,6.90237,5.384995,5.334581,6.829877,6.980715
나유석,4.838123,5.754071,6.706147,6.332424,6.181425,6.970405,6.104417,6.908594,6.314585,6.429686,...,6.765619,7.053431,6.410239,4.690964,5.11964,6.774342,5.136515,5.235222,7.021701,6.917444
권택현,5.024898,5.998416,6.803349,7.000569,6.320976,6.526861,6.108809,6.746307,6.611985,6.754411,...,6.610552,6.322715,6.613896,4.908004,5.295563,6.32191,5.682333,4.608558,6.320976,6.466606
이창세,7.412678,5.605498,4.975028,5.870892,6.189858,4.975028,4.8541,5.288001,5.224032,5.057614,...,5.419952,5.415974,5.33195,4.203686,7.681846,5.314593,4.587614,7.525524,5.705897,5.248559
김수창,5.587976,5.861193,6.377519,6.836075,6.958514,6.667569,6.071956,7.137807,6.357499,6.716543,...,7.473947,6.96974,6.638826,5.382292,5.75727,7.156908,5.13646,5.513433,7.088523,7.110078
최근영,5.459192,6.037495,6.618885,6.784181,6.680381,6.889839,6.419839,6.730477,6.487145,6.055565,...,6.826418,7.327111,6.276771,4.451754,6.096538,6.749756,5.343373,6.189858,7.517681,6.701933
정연우,5.419952,5.932572,6.598891,7.027658,6.891117,6.876387,6.152792,7.565313,6.575207,6.905889,...,8.426265,7.038455,6.702909,5.116871,6.001908,7.361537,5.753602,5.156751,7.146288,7.298256
신재범,5.233173,6.101444,6.781054,6.787811,6.617202,7.011285,6.933561,7.108009,7.042501,6.448782,...,7.038455,8.426265,6.684787,4.981066,5.664982,7.082082,5.400817,5.524372,7.725773,7.216683
홍대한,5.145688,6.496172,6.817778,6.962752,7.086748,6.539586,6.700281,6.720873,7.014202,7.430834,...,6.702909,6.684787,8.426265,5.367036,5.585489,6.716889,5.746844,4.778433,6.498874,7.249956
이어룡,5.142217,5.63249,4.904463,4.967552,4.780095,5.664447,5.19369,5.116914,6.11155,5.367341,...,5.116871,4.981066,5.367036,8.426265,4.203686,5.116901,6.298485,3.683421,4.980955,5.11694
이지원,7.172947,5.499045,5.612936,6.096538,6.40028,5.612936,5.134676,5.886127,5.483488,5.326412,...,6.001908,5.664982,5.585489,4.203686,8.426265,5.569076,5.458571,7.292054,5.939789,5.50666
홍종국,5.314593,5.93749,6.660915,6.78993,6.815582,6.929375,6.193599,7.454097,6.617273,6.640558,...,7.361537,7.082082,6.716889,5.116901,5.569076,8.426265,5.400808,5.045081,7.075045,7.342125
양홍석,5.081108,5.765378,5.502402,6.091601,5.63439,6.074436,5.978648,5.753609,6.435335,5.746897,...,5.753602,5.400817,5.746844,6.298485,5.458571,5.400808,8.426265,3.780537,5.400799,5.400815
조홍희,7.172947,4.966474,4.975028,5.270608,5.633289,4.975028,4.8541,5.016876,4.656626,4.468247,...,5.156751,5.524372,4.778433,3.683421,7.292054,5.045081,3.780537,8.426265,5.807632,4.975028
강준규,5.705897,5.929667,6.898887,6.693221,6.840348,6.848775,6.435731,7.057142,6.831637,6.433834,...,7.146288,7.725773,6.498874,4.980955,5.939789,7.075045,5.400799,5.807632,8.426265,7.030645
문병식,5.248559,6.257468,6.919364,6.667612,7.030645,7.172947,6.283837,7.644956,6.723054,7.215936,...,7.298256,7.216683,7.249956,5.11694,5.50666,7.342125,5.400815,4.975028,7.030645,8.426265

In [261]:
#가중치 계산
for t, dataframe in enumerate(dataFrames):
  for i in range(0, len(dataframe)):
    for j in range(0, len(dataframe)):
      matrixs[t].iloc[i, j] = math.sqrt(weight_sum(dataframe.iloc[i], dataframe.iloc[j])**3)

In [262]:
matrixs[6]

,김병철,오익근,이정화,진승욱,길기모,정재중,송혁,이재우,신인식,조경순,...,정연우,신재범,홍대한,이어룡,이지원,홍종국,양홍석,조홍희,강준규,문병식
김병철,18.520259,6.490046,5.51823,7.155212,7.155212,7.348347,4.904765,6.170115,8.824686,5.683641,...,6.466241,6.050897,5.865173,5.857917,11.970881,6.228736,5.731542,11.970881,7.155212,6.08413
오익근,6.490046,18.520259,7.372465,9.869596,8.551904,7.163182,7.502736,7.767936,8.0037,9.576191,...,7.750977,8.225703,9.44827,6.971918,6.65018,7.764419,7.307126,5.501359,7.743045,8.689318
이정화,5.51823,7.372465,18.520259,10.32553,9.713549,12.698648,9.4277,10.100913,11.221762,10.249894,...,9.794452,10.439189,10.574124,5.38048,6.923857,10.009468,6.658097,5.51823,10.878241,10.95637
진승욱,7.155212,9.869596,10.32553,18.520259,10.765901,9.387814,9.042661,11.305681,10.927812,10.376118,...,11.378822,10.46389,11.123736,5.503483,8.211521,10.471648,8.197276,6.132056,10.123285,10.032958
길기모,7.155212,8.551904,9.713549,10.765901,18.520259,8.769397,8.495692,10.496061,9.651703,10.895181,...,10.848737,9.857455,11.616051,5.145474,9.135913,10.566008,6.976604,6.973888,10.657902,11.390696
정재중,7.348347,7.163182,12.698648,9.387814,8.769397,18.520259,8.723341,11.14896,12.366398,9.285869,...,10.793025,11.313935,9.593097,7.051151,6.923857,10.994765,8.147929,5.51823,10.689346,11.970881
송혁,4.904765,7.502736,9.4277,9.042661,8.495692,8.723341,18.520259,8.538212,11.62325,9.304389,...,8.37556,11.010859,10.148327,5.966399,5.842181,8.496543,7.877804,5.284135,9.250196,8.770145
이재우,6.170115,7.767936,10.100913,11.305681,10.496061,11.14896,8.538212,18.520259,9.909387,11.118257,...,13.725985,11.702593,10.221715,5.805274,7.625134,13.204182,7.276823,5.601475,11.496588,14.112139
신인식,8.824686,8.0037,11.221762,10.927812,9.651703,12.366398,11.62325,9.909387,18.520259,10.953855,...,9.713549,11.437959,11.32547,8.25499,6.61361,9.857699,9.248914,4.921612,10.62549,10.229519
조경순,5.683641,9.576191,10.249894,10.376118,10.895181,9.285869,9.304389,11.118257,10.953855,18.520259,...,10.904892,9.292619,13.097541,6.346585,6.254959,9.938394,7.259597,4.597264,9.244047,12.151813
김성원,6.526983,7.600179,10.54613,10.606117,9.268379,10.772865,7.920256,11.597143,9.699947,10.211939,...,13.762845,10.423523,9.477736,5.710287,8.924578,10.695946,7.405366,5.94724,11.413725,10.45744
이순남,7.052704,8.672329,10.488411,12.50113,9.569658,10.994765,8.496543,13.204182,10.540767,9.938394,...,12.7849,11.597143,10.207476,5.805247,7.665329,12.698648,7.27682,5.63775,12.04456,11.702593
강윤기,8.039633,8.183343,9.713549,12.328332,11.146816,10.689346,8.77264,12.527028,10.62549,9.244047,...,12.900895,12.889407,9.92733,5.52995,9.135913,11.568684,7.276796,7.851066,13.762845,11.390696
박성준,6.494494,9.951315,10.234301,12.385039,9.900482,9.27094,8.633881,12.431373,10.93703,12.252034,...,10.89142,9.946898,11.007371,5.942811,7.090975,9.924307,7.708493,5.120843,9.900482,10.420493
김범철,5.988719,9.285869,10.416724,12.616572,9.419735,9.703566,10.681596,10.25612,10.381829,9.456913,...,10.091425,9.998998,10.326014,5.695535,8.776407,9.240252,9.30042,5.817931,9.085935,9.449563
정연규,6.43761,8.252414,12.985344,11.683813,9.834991,11.747236,10.125644,10.618951,11.875348,10.232166,...,10.009468,10.92221,10.508801,5.380411,6.188114,10.618951,6.247603,5.618904,12.020282,10.051848
김호중,7.385767,8.239232,10.699987,10.848737,9.571422,10.2363,7.882949,11.077866,10.14039,8.743659,...,12.131345,11.886553,8.969318,5.102432,7.124428,11.150764,6.883206,6.780894,12.919764,10.908899
박현식,5.506965,6.327123,9.122746,7.604661,7.063119,9.264759,8.0623,8.723341,7.888515,6.951291,...,8.460552,10.225779,7.242882,4.829639,5.506965,9.103947,4.837281,6.320445,9.31861,9.587337
임민수,8.039633,7.128299,10.1878,9.449563,10.95637,10.017497,7.691724,11.802618,9.940557,9.244047,...,12.244162,10.661952,9.457221,5.80514,7.155212,11.875348,5.845899,6.556882,13.216538,11.695793
김상원,6.47877,8.527141,10.123285,11.437959,8.579123,11.150764,8.918249,10.890389,10.300482,8.75902,...,10.497477,11.349027,9.017108,4.828442,6.228736,12.641509,6.292796,5.658243,11.320773,10.416724
정기동,6.273145,6.984746,9.727892,9.773322,9.934162,11.421809,7.888675,12.355336,8.352627,9.05003,...,12.339045,9.699947,8.808754,5.15659,7.735658,10.891492,6.3865,6.273145,10.618951,11.193764
나유석,5.253909,7.278012,10.169181,8.920995,8.460273,11.153518,8.234307,10.91521,8.865316,9.230613,...,10.382983,11.481701,9.167876,4.982951,5.810925,10.414713,5.846016,6.055313,11.355171,10.949019
권택현,5.617566,7.932829,10.520904,11.271669,8.885226,9.550425,8.247038,10.313077,9.839465,10.342356,...,9.83453,8.89065,9.846051,5.387314,6.186732,8.888139,7.095874,4.836915,8.885226,9.350865
이창세,13.014905,6.905659,5.51823,7.584286,8.48538,5.51823,5.284135,6.170115,6.031234,5.683641,...,6.466241,6.457117,6.267284,4.174469,14.294631,6.228736,4.800433,13.537002,7.155212,6.08413
김수창,6.862972,7.558391,9.063265,10.641988,11.107278,10.032808,8.140825,11.824958,8.999834,10.206239,...,13.295853,11.150927,9.93237,6.380373,7.286238,11.904056,5.845901,6.684172,11.62325,11.711051
최근영,6.556882,8.042707,9.863267,10.450615,10.077897,10.843893,9.198793,10.25612,9.418428,8.094013,...,10.606117,12.632335,8.748413,4.569817,8.211521,10.32553,6.292775,8.48538,13.500055,10.154195
정연우,6.466241,7.750977,9.794452,11.378822,10.848737,10.793025,8.37556,13.725985,9.713549,10.904892,...,18.520259,11.421809,10.157666,5.805185,7.942589,12.7849,7.276805,5.888358,11.860013,12.505841
신재범,6.050897,8.225703,10.439189,10.46389,9.857455,11.313935,11.010859,11.702593,11.437959,9.292619,...,11.421809,18.520259,10.093449,5.53017,7.052485,11.597143,6.422475,6.71013,14.514979,12.15498
홍대한,5.865173,9.44827,10.574124,11.123736,11.616051,9.593097,10.148327,10.221715,11.32547,13.097541,...,10.157666,10.093449,18.520259,6.345897,6.856933,10.207476,7.25946,5.142399,9.457221,12.296906
이어룡,5.857917,6.971918,5.38048,5.503483,5.145474,7.051151,5.966399,5.805274,8.25499,6.346585,...,5.805185,5.53017,6.345897,18.520259,4.174469,5.805247,8.815357,3.442027,5.52995,5.805328
이지원,11.970881,6.65018,6.923857,8.211521,9.135913,6.923857,5.842181,7.625134,6.61361,6.254959,...,7.942589,7.052485,6.856933,4.174469,18.520259,6.81721,6.555438,12.478817,7.770709,6.668151
홍종국,6.228736,7.764419,10.009468,10.471648,10.566008,10.994765,8.496543,13.204182,9.857699,9.938394,...,12.7849,11.597143,10.207476,5.805247,6.81721,18.520259,6.422454,5.658243,11.568684,12.698648
양홍석,5.731542,7.307126,6.658097,8.197276,6.976604,8.147929,7.877804,7.276823,9.248914,7.259597,...,7.276805,6.422475,7.25946,8.815357,6.555438,6.422454,18.520259,3.569617,6.422432,6.42247
조홍희,11.970881,5.501359,5.51823,6.132056,6.973888,5.51823,5.284135,5.601475,4.921612,4.597264,...,5.888358,6.71013,5.142399,3.442027,12.478817,5.658243,3.569617,18.520259,7.416923,5.51823
강준규,7.155212,7.743045,10.878241,10.123285,10.657902,10.689346,9.250196,11.496588,10.62549,9.244047,...,11.860013,14.514979,9.457221,5.52995,7.770709,11.568684,6.422432,7.416923,18.520259,11.390696
문병식,6.08413,8.689318,10.95637,10.032958,11.390696,11.970881,8.770145,14.112139,10.229519,12.151813,...,12.505841,12.15498,12.296906,5.805328,6.668151,12.698648,6.42247,5.51823,11.390696,18.520259

In [257]:
#가중치 계산
for t, dataframe in enumerate(dataFrames):
  for i in range(0, len(dataframe)):
    for j in range(0, len(dataframe)):
      matrixs[t].iloc[i, j] = weight_sum(dataframe.iloc[i], dataframe.iloc[j])**2

In [258]:
matrixs[6]

,김병철,오익근,이정화,진승욱,길기모,정재중,송혁,이재우,신인식,조경순,...,정연우,신재범,홍대한,이어룡,이지원,홍종국,양홍석,조홍희,강준규,문병식
김병철,49.0,12.105898,9.751387,13.787854,13.787854,14.286292,8.333439,11.316818,18.236115,10.143057,...,12.04673,11.026213,10.57729,10.559848,27.384289,11.460404,10.257195,27.384289,13.787854,11.10703
오익근,12.105898,49.0,14.348845,21.170566,17.488414,13.808336,14.687895,15.384175,16.009867,20.335602,...,15.339407,16.604688,19.974214,13.31894,12.505793,15.374887,14.17954,9.711656,15.318481,17.86409
이정화,9.751387,14.348845,49.0,22.484495,20.725448,29.626249,19.916254,21.834715,25.123574,22.265159,...,20.955927,22.815099,23.209147,9.428184,13.196663,21.571549,12.525647,9.751387,24.103397,24.334489
진승욱,13.787854,21.170566,22.484495,49.0,23.77208,19.803988,18.839167,25.374391,24.249956,22.631493,...,25.593503,22.887107,24.831383,9.716656,16.566528,22.909734,16.52822,11.22384,21.899218,21.639074
길기모,13.787854,17.488414,20.725448,23.77208,49.0,18.083936,17.335312,22.980977,20.549689,24.153456,...,24.016272,21.13585,26.307406,8.883153,19.098648,23.185398,13.330879,13.32396,23.454649,25.62912
정재중,14.286292,13.808336,29.626249,19.803988,18.083936,49.0,17.957413,24.906487,28.597253,19.517764,...,23.85197,25.399094,20.383486,13.521142,13.196663,24.448259,16.395689,9.751387,23.546961,27.384289
송혁,8.333439,14.687895,19.916254,18.839167,17.335312,17.957413,49.0,17.451091,26.329146,19.569683,...,17.009249,24.495988,21.971477,10.82139,10.522042,17.337629,15.674976,9.203758,19.417856,18.085994
이재우,11.316818,15.384175,21.834715,25.374391,22.980977,24.906487,17.451091,49.0,21.284448,24.815075,...,32.864323,26.569057,22.183582,10.433507,15.008247,31.209154,14.101191,9.948018,25.947286,34.102833
신인식,18.236115,16.009867,25.123574,24.249956,20.549689,28.597253,26.329146,21.284448,49.0,24.327044,...,20.725448,25.771008,25.433629,16.683561,12.414182,21.13655,19.414265,8.371627,23.359595,22.206169
조경순,10.143057,20.335602,22.265159,22.631493,24.153456,19.517764,19.569683,24.815075,24.327044,49.0,...,24.182165,19.536684,30.873535,11.750421,11.524779,21.36756,14.0567,7.644211,19.400647,27.937538
김성원,12.197851,14.942793,23.127259,23.302825,19.468763,23.792586,15.787703,26.250326,20.686759,22.1553,...,32.982049,22.769459,20.057316,10.206509,18.511869,23.566346,14.434287,10.775083,25.69823,22.868298
이순남,13.525112,17.817536,22.958646,29.013428,20.317108,24.448259,17.337629,31.209154,23.111579,21.36756,...,29.894855,26.250326,22.14239,10.433443,15.113825,29.626249,14.101181,10.034009,27.609248,26.569057
강윤기,16.105774,16.490771,20.725448,28.47994,24.9001,23.546961,18.092855,29.093594,23.359595,19.400647,...,30.257039,30.221123,21.335849,9.77901,19.098648,26.164471,14.101119,15.60408,32.982049,25.62912
박성준,12.116963,21.404608,22.220011,28.654741,21.258949,19.475937,17.71229,28.797766,24.277233,28.245173,...,24.142338,21.391944,24.48564,10.764385,13.623059,21.327189,15.227408,8.826501,21.258949,22.760635
김범철,10.875401,19.517764,22.749657,29.371209,19.893823,20.697052,23.524201,22.283194,22.648102,19.998582,...,21.807373,21.541469,22.4859,10.171367,18.103214,19.390027,19.558554,10.463848,18.959469,19.977861
정연규,11.975663,16.676619,30.521413,26.512224,21.071653,26.704284,21.906023,23.34043,27.093293,22.21383,...,21.571549,24.233382,23.018175,9.428021,11.360857,23.34043,11.506713,9.989311,27.535071,21.693413
김호중,14.383376,16.641111,23.57822,24.016272,20.322102,22.225798,15.688627,24.69495,21.948569,18.013204,...,27.87481,27.127383,18.635707,8.784214,13.708819,24.911859,13.093457,12.834608,30.31606,24.194012
박현식,9.724855,11.702403,19.061956,14.954543,13.551748,19.458627,16.166349,17.957413,15.703399,13.266427,...,17.239776,22.195343,14.013562,8.163684,9.724855,19.0096,8.180914,11.685937,19.609575,20.367169
임민수,16.105774,13.71875,22.085498,19.977861,24.334489,21.594623,15.183255,26.872278,21.37376,19.400647,...,28.220979,23.466536,19.999451,10.433186,13.787854,27.093293,10.53097,12.27241,31.2481,26.548474
김상원,12.077862,17.420927,21.899218,25.771008,17.562669,24.911859,18.494368,24.139292,22.411801,18.05541,...,22.985109,25.504189,18.768218,8.160987,11.460404,29.448639,11.617826,10.082669,25.419564,22.749657
정기동,11.569477,13.351625,20.766263,20.89567,21.355429,25.7225,15.703823,28.563149,16.947181,18.859638,...,28.512945,20.686759,18.192231,8.90875,15.298998,24.142553,11.84906,11.569477,23.34043,25.040031
나유석,9.13363,14.104262,22.031697,18.50196,17.239018,24.920065,16.627849,24.212675,18.34815,19.363062,...,22.651459,25.902499,19.187791,8.51103,10.44705,22.743802,10.531252,11.036944,25.522599,24.312724
권택현,9.986138,15.821129,23.053528,25.272662,18.403114,20.262682,16.662135,22.448346,21.084434,22.533362,...,21.070336,18.418093,21.103256,9.444155,11.357473,18.411159,13.635609,8.180087,18.403114,19.700129
이창세,30.614089,13.150436,9.751387,14.901144,17.307264,9.751387,9.203758,11.316818,10.978463,10.143057,...,12.04673,12.024071,11.555067,6.721533,34.6921,11.460404,8.097927,32.2624,13.787854,11.10703
김수창,13.042162,14.833348,18.896422,23.407968,24.78241,21.638642,16.37663,26.940118,18.720293,22.138812,...,31.498385,24.912348,21.350292,11.833904,14.125521,27.180657,10.530974,12.591096,26.329146,26.594665
최근영,12.27241,16.113987,21.152467,22.8484,21.768402,24.001976,19.274117,22.283194,19.890141,16.251191,...,23.302825,29.420147,18.026262,7.58342,16.566528,22.484495,11.617774,17.307264,32.145045,21.98842
정연우,12.04673,15.339407,20.955927,25.593503,24.016272,23.85197,17.009249,32.864323,20.725448,24.182165,...,49.0,25.7225,21.99844,10.433293,15.847086,29.894855,14.101143,10.633077,27.046656,29.028005
신재범,11.026213,16.604688,22.815099,22.887107,21.13585,25.399094,24.495988,26.569057,25.771008,19.536684,...,25.7225,49.0,21.813203,9.779529,13.524552,26.250326,11.938137,12.656334,35.406953,27.947244
홍대한,10.57729,19.974214,23.209147,24.831383,26.307406,20.383486,21.971477,22.183582,25.433629,30.873535,...,21.99844,21.813203,49.0,11.748725,13.026863,22.14239,14.056346,8.876077,19.999451,28.383186
이어룡,10.559848,13.31894,9.428184,9.716656,8.883153,13.521142,10.82139,10.433507,16.683561,11.750421,...,10.433293,9.779529,11.748725,49.0,6.721533,10.433443,18.210417,5.196995,9.77901,10.433636
이지원,27.384289,12.505793,13.196663,16.566528,19.098648,13.196663,10.522042,15.008247,12.414182,11.524779,...,15.847086,13.524552,13.026863,6.721533,49.0,12.926339,12.268807,28.9444,15.391498,12.550873
홍종국,11.460404,15.374887,21.571549,22.909734,23.185398,24.448259,17.337629,31.209154,21.13655,21.36756,...,29.894855,26.250326,22.14239,10.433443,12.926339,49.0,11.938084,10.082669,26.164471,29.626249
양홍석,10.257195,14.17954,12.525647,16.52822,13.330879,16.395689,15.674976,14.101191,19.414265,14.0567,...,14.101143,11.938137,14.056346,18.210417,12.268807,11.938084,49.0,5.455427,11.938032,11.938124
조홍희,27.384289,9.711656,9.751387,11.22384,13.32396,9.751387,9.203758,9.948018,8.371627,7.644211,...,10.633077,12.656334,8.876077,5.196995,28.9444,10.082669,5.455427,49.0,14.46433,9.751387
강준규,13.787854,15.318481,24.103397,21.899218,23.454649,23.546961,19.417856,25.947286,23.359595,19.400647,...,27.046656,35.406953,19.999451,9.77901,15.391498,26.164471,11.938032,14.46433,49.0,25.62912
문병식,11.10703,17.86409,24.334489,21.639074,25.62912,27.384289,18.085994,34.102833,22.206169,27.937538,...,29.028005,27.947244,28.383186,10.433636,12.550873,29.626249,11.938124,9.751387,25.62912,49.0



---
너무 가중치 차이가 안나서 네트워크 그리기 힘들면

alpha 값을 조정하거나
스케일을 조절해야될듯.

그나마 가중치 차이 많이 볼 수 있는 스케일 조정..?
1. 가중치 제곱
2. 루트(가중치 세제곱)

=> 그 후 threshold(임계값) 조정